Repository ESMValGroup/ESMValCore, pull requests merged in 2019-10, with the labels that each got.

#257 Retrieve properly the activity for exps linked to multiple ids
  esmvalcore/_config.py
  esmvalcore/cmor/table.py
  tests/integration/test_recipe.py
Labels: preprocessor

#206 Add option to expand ensembles
  doc/esmvalcore/recipe.rst
  esmvalcore/_recipe.py
  tests/integration/test_recipe.py
Labels: enhancement

#256 fix ec_earth: missing_height
  esmvalcore/cmor/_fixes/cmip5/ec_earth.py
  tests/integration/cmor/_fixes/cmip5/test_ec_earth.py
Labels: fix for dataset

#290 Extend statistics preproc
  doc/esmvalcore/preprocessor.rst
  esmvalcore/preprocessor/_area.py
  esmvalcore/preprocessor/_shared.py
  esmvalcore/preprocessor/_time.py
  tests/unit/preprocessor/_area/test_area.py
  tests/unit/preprocessor/_time/test_time.py
Labels: enhancement

#231 Check parent_time_unit format
  esmvalcore/cmor/check.py
  tests/unit/cmor/test_cmor_check.py
Labels: cmor, workshop

#288 Added vegfrac as a derived variable
  esmvalcore/cmor/tables/custom/CMOR_vegfrac.dat
  esmvalcore/preprocessor/_derive/vegfrac.py
Labels: variable derivation, workshop

#210 Use glob in datafinder
  esmvalcore/_data_finder.py
  esmvalcore/config-developer.yml
  tests/integration/test_recipe.py
Labels: enhancement, workshop

#297 Find various fx files for OBS projects for preprocessor masking
  esmvalcore/_recipe.py
Labels: workshop

#306 Fix Fgoals fix
  esmvalcore/cmor/_fixes/cmip5/fgoals_g2.py
  tests/integration/cmor/_fixes/cmip5/test_fgoals_g2.py
Labels: bug, fix for dataset

#308 GFDL fixes for areacello
  esmvalcore/cmor/_fixes/cmip5/gfdl_cm2p1.py
  esmvalcore/cmor/_fixes/cmip5/gfdl_cm3.py
  esmvalcore/cmor/_fixes/cmip5/gfdl_esm2g.py
  esmvalcore/cmor/_fixes/cmip5/gfdl_esm2m.py
  tests/integration/cmor/_fixes/cmip5/test_gfdl_cm2p1.py
  tests/integration/cmor/_fixes/cmip5/test_gfdl_cm3.py
  tests/integration/cmor/_fixes/cmip5/test_gfdl_esm2g.py
  tests/integration/cmor/_fixes/cmip5/test_gfdl_esm2m.py
Labels: fix for dataset

#314 reinstated correct latestversion for CMIP5 files
  esmvalcore/config-developer.yml
Labels: bug

#293 Minor edit to fix a typo
  esmvalcore/preprocessor/__init__.py
Labels: enhancement

#292 Add descriptive title requirement to pull request template
  .github/pull_request_template.md
Labels: enhancement

#271 CMIP6 updates for variable derivation (lwp)
  esmvalcore/preprocessor/_derive/lwp.py
Labels: variable derivation, workshop

#305 Make obs4mips not cmor strict
  esmvalcore/config-developer.yml
  tests/integration/cmor/test_read_cmor_tables.py
  tests/integration/cmor/test_table.py
Labels: cmor

#276 Support Windows Subsystem for Linux
  esmvalcore/_task.py
Labels: enhancement, installation
