Repository ESMValGroup/ESMValCore, pull requests merged in 2019-07, with the labels that each got.

#148 Dev emac import clt
  esmvalcore/cmor/tables/custom/CMOR_AIRC_NO_s.dat
  esmvalcore/cmor/tables/custom/CMOR_ANTHNT_AER_TC_s.dat
  esmvalcore/cmor/tables/custom/CMOR_ANTHNT_CO_s.dat
  esmvalcore/cmor/tables/custom/CMOR_ANTHNT_NO_s.dat
  esmvalcore/cmor/tables/custom/CMOR_ANTHNT_SO2_s.dat
  esmvalcore/cmor/tables/custom/CMOR_BB_AER_TC_s.dat
  esmvalcore/cmor/tables/custom/CMOR_BB_CO_s.dat
  esmvalcore/cmor/tables/custom/CMOR_BB_NO_s.dat
  esmvalcore/cmor/tables/custom/CMOR_BB_SO2_s.dat
  esmvalcore/cmor/tables/custom/CMOR_ROAD_AER_BC.dat
  esmvalcore/cmor/tables/custom/CMOR_ROAD_NO.dat
  esmvalcore/cmor/tables/custom/CMOR_SHIP_AER_BC_s.dat
  esmvalcore/cmor/tables/custom/CMOR_SHIP_NO_s.dat
  esmvalcore/cmor/tables/custom/CMOR_SHIP_SO2_s.dat
  esmvalcore/cmor/tables/custom/CMOR_TN_GHG_CH4.dat
  esmvalcore/cmor/tables/custom/CMOR_TN_GHG_CO2.dat
  esmvalcore/cmor/tables/custom/CMOR_TN_GHG_N2O.dat
  esmvalcore/cmor/tables/custom/CMOR_VOLC_SO2_s.dat
  esmvalcore/preprocessor/_emac/_derive/clt.py
  esmvalcore/preprocessor/_emac/_derive/evspsbl.py
  esmvalcore/preprocessor/_emac/_derive/lnox.py
  esmvalcore/preprocessor/_emac/_derive/pr.py
  esmvalcore/preprocessor/_emac/_derive/rlds.py
  esmvalcore/preprocessor/_emac/_derive/rsds.py
  esmvalcore/preprocessor/_emac/_derive/rsdt.py
  esmvalcore/preprocessor/_emac/_derive/rsutcs.py
  esmvalcore/preprocessor/_emac/_derive/rtmt.py
Labels: cmor, enhancement

#75 Do not fail if we get multiple cubes from file
  esmvalcore/cmor/fix.py
  tests/unit/cmor/test_fix.py
Labels: enhancement, paper

#155 Create recipe templates for emac quicklooks
  esmvalcore/config-user.yml
  esmvalcore/preprocessor/_emac/var_mapping.yml
  esmvalcore/quicklook/template_recipe_emac.yml
  esmvalcore/quicklook/template_recipe_emac_atmos_chem.yml
  esmvalcore/quicklook/template_recipe_emac_atmos_dynamics.yml
  esmvalcore/quicklook/template_recipe_emac_forcings.yml
  esmvalcore/quicklook/template_recipe_emac_ocean.yml
Labels: enhancement

#97 Add usi and vsi fix for GFDL
  esmvalcore/cmor/_fixes/cmip5/gfdl_esm2g.py
  tests/integration/cmor/_fixes/cmip5/test_gfdl_esm2g.py
Labels: fix for dataset

#110 Automatic fixes for standard and long name
  esmvalcore/cmor/check.py
  tests/unit/cmor/test_cmor_check.py
Labels: cmor

#105 Added several fixes and derivations
  esmvalcore/cmor/_fixes/cmip5/ccsm4.py
  esmvalcore/cmor/_fixes/cmip5/miroc5.py
  esmvalcore/cmor/_fixes/cmip5/noresm1_me.py
  esmvalcore/cmor/_fixes/cmip6/cesm2.py
  esmvalcore/cmor/_fixes/cmip6/cesm2_waccm.py
  esmvalcore/cmor/_fixes/shared.py
  esmvalcore/cmor/tables/custom/CMOR_rlntcs.dat
  esmvalcore/cmor/tables/custom/CMOR_rsntcs.dat
  esmvalcore/preprocessor/_derive/rlntcs.py
  esmvalcore/preprocessor/_derive/rsntcs.py
  esmvalcore/recipe_schema.yml
  tests/integration/cmor/_fixes/cmip5/test_miroc5.py
  tests/integration/cmor/_fixes/cmip6/test_cesm2.py
  tests/integration/cmor/_fixes/cmip6/test_cesm2_waccm.py
  tests/integration/cmor/_fixes/test_shared.py
  tests/unit/preprocessor/_derive/test_rlntcs.py
  tests/unit/preprocessor/_derive/test_rsntcs.py
Labels: fix for dataset

#147 Landvariables
  esmvalcore/cmor/tables/custom/CMOR_albDiff.dat
  esmvalcore/cmor/tables/custom/CMOR_bdalb.dat
  esmvalcore/cmor/tables/custom/CMOR_bhalb.dat
  esmvalcore/cmor/tables/custom/CMOR_coordinates.dat
  esmvalcore/cmor/tables/custom/CMOR_fapar.dat
Labels: cmor, paper

#175 Check time is monotonic
  esmvalcore/cmor/check.py
  tests/unit/cmor/test_cmor_check.py
Labels: bug, cmor

#176 Demoted logger info message for fixes to debug message
  esmvalcore/cmor/_fixes/shared.py
Labels: fix for dataset

#177 Ignore known iris warnings
  esmvalcore/preprocessor/_io.py
  esmvalcore/preprocessor/_time.py
Labels: enhancement

#169 [EMAC] Adjust commandline interface for quicklooks
  esmvalcore/_config.py
  esmvalcore/_data_finder.py
  esmvalcore/_main.py
  esmvalcore/_quicklook.py
  esmvalcore/_recipe.py
  esmvalcore/cmor/check.py
  esmvalcore/config-developer.yml
  esmvalcore/config-user.yml
  esmvalcore/preprocessor/_emac/_derive/TN_GHG_CH4.py
  esmvalcore/preprocessor/_emac/_derive/TN_GHG_CO2.py
  esmvalcore/preprocessor/_emac/_derive/TN_GHG_N2O.py
  esmvalcore/preprocessor/_emac/_derive/_shared.py
  esmvalcore/preprocessor/_emac/_derive/evspsbl.py
  esmvalcore/preprocessor/_emac/_derive/rlds.py
  esmvalcore/preprocessor/_emac/_derive/rlut.py
  esmvalcore/preprocessor/_emac/_derive/rsds.py
  esmvalcore/preprocessor/_emac/_derive/rsdt.py
  esmvalcore/preprocessor/_emac/_derive/rtmt.py
  esmvalcore/preprocessor/_emac/var_mapping.yml
  esmvalcore/preprocessor/_io.py
  esmvalcore/quicklook/_logging.py
  esmvalcore/quicklook/diagnostics_atmos_chem.yml
  esmvalcore/quicklook/diagnostics_atmos_dynamics.yml
  esmvalcore/quicklook/diagnostics_forcings.yml
  esmvalcore/quicklook/diagnostics_ocean.yml
  esmvalcore/quicklook/diagnostics_test.yml
  esmvalcore/quicklook/general.yml
  esmvalcore/quicklook/template_recipe_emac.yml
  esmvalcore/quicklook/template_recipe_emac_atmos_chem.yml
  esmvalcore/quicklook/template_recipe_emac_atmos_dynamics.yml
  esmvalcore/quicklook/template_recipe_emac_forcings.yml
  esmvalcore/quicklook/template_recipe_emac_ocean.yml
Labels: enhancement

#108 Convert units of troubling attributes in time coordinate
  esmvalcore/cmor/check.py
  tests/unit/cmor/test_cmor_check.py
Labels: preprocessor

#187 add hourly support for regrid_time
  doc/esmvalcore/preprocessor.rst
  esmvalcore/preprocessor/_time.py
  tests/unit/preprocessor/_time/test_time.py
Labels: preprocessor

#180 Added a bit of documentation about the alias
  doc/esmvalcore/recipe.rst
Labels: documentation
