Repository ESMValGroup/ESMValCore, pull requests merged in 2019-06, with the labels that each got.

#6 Remove legacy code
  doc/sphinx/source/requirements.txt
  esmvalcore/_config.py
  esmvalcore/_data_finder.py
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_io.py
  esmvalcore/preprocessor/_mapping.py
  esmvalcore/preprocessor/_multimodel.py
  esmvalcore/preprocessor/_regrid.py
  meta.yaml
  setup.py
  tests/integration/test_diagnostic_run.py
  tests/integration/test_recipe.py
Labels: enhancement

#7 Update _recipe.py
  esmvalcore/_recipe.py
Labels: enhancement, preprocessor

#14 Reduce time required for provenance recording
  esmvalcore/_provenance.py
Labels: enhancement

#20 Add multimodel unit tests
  tests/unit/preprocessor/_multimodel/__init__.py
  tests/unit/preprocessor/_multimodel/test_multimodel.py
Labels: preprocessor

#82 Make sm derivation lazy
  esmvalcore/preprocessor/_derive/sm.py
Labels: preprocessor

#81 Use float32 for toz derivation instead of float64
  esmvalcore/preprocessor/_derive/toz.py
Labels: preprocessor

#80 Make fixes lazy
  esmvalcore/cmor/_fixes/CMIP5/MIROC5.py
  esmvalcore/cmor/_fixes/CMIP5/MRI_CGCM3.py
  esmvalcore/cmor/_fixes/CMIP5/MRI_ESM1.py
Labels: preprocessor

#73 Version2 preprocessor convert units
  doc/sphinx/source/esmvalcore/preprocessor.inc
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_units.py
  tests/unit/preprocessor/_units/__init__.py
  tests/unit/preprocessor/_units/test_convert_units.py
Labels: paper, preprocessor

#120 Pin prospector to skip broken versions
  setup.py
Labels: installation
