Repository ESMValGroup/ESMValCore, pull requests merged in 2019-08, with the labels that each got.

#113 Adding a dumpload of documentation
  doc/esmvalcore/config.rst
  doc/esmvalcore/datafinder.rst
  doc/esmvalcore/index.rst
  doc/esmvalcore/preprocessor.rst
  doc/esmvalcore/recipe.rst
  doc/esmvalcore/utils.rst
Labels: documentation

#179 Add fixes for tos (sea surface temperature) for some cmip5 models
  esmvalcore/cmor/_fixes/cmip5/ec_earth.py
  esmvalcore/cmor/_fixes/cmip5/gfdl_cm2p1.py
  esmvalcore/cmor/_fixes/cmip5/gfdl_cm3.py
  esmvalcore/cmor/_fixes/cmip5/gfdl_esm2m.py
  esmvalcore/cmor/_fixes/cmip5/miroc5.py
Labels: fix for dataset, paper

#197 Added a dataset specific variable (Duveiller2018)
  esmvalcore/cmor/tables/custom/CMOR_albDiffiTr13.dat
Labels: cmor

#205 Always check monotonicity and direction
  esmvalcore/cmor/check.py
  tests/integration/cmor/_fixes.1/__init__.py
  tests/integration/cmor/_fixes.1/cmip5/__init__.py
  tests/integration/cmor/_fixes.1/cmip5/test_access1_0.py
  tests/integration/cmor/_fixes.1/cmip5/test_access1_3.py
  tests/integration/cmor/_fixes.1/cmip5/test_bcc_csm1_1.py
  tests/integration/cmor/_fixes.1/cmip5/test_bcc_csm1_1_m.py
  tests/integration/cmor/_fixes.1/cmip5/test_bnu_esm.py
  tests/integration/cmor/_fixes.1/cmip5/test_canesm2.py
  tests/integration/cmor/_fixes.1/cmip5/test_ccsm4.py
  tests/integration/cmor/_fixes.1/cmip5/test_cesm1_bgc.py
  tests/integration/cmor/_fixes.1/cmip5/test_cnrm_cm5.py
  tests/integration/cmor/_fixes.1/cmip5/test_ec_earth.py
  tests/integration/cmor/_fixes.1/cmip5/test_fgoals_g2.py
  tests/integration/cmor/_fixes.1/cmip5/test_fio_esm.py
  tests/integration/cmor/_fixes.1/cmip5/test_gfdl_cm2p1.py
  tests/integration/cmor/_fixes.1/cmip5/test_gfdl_cm3.py
  tests/integration/cmor/_fixes.1/cmip5/test_gfdl_esm2g.py
  tests/integration/cmor/_fixes.1/cmip5/test_gfdl_esm2m.py
  tests/integration/cmor/_fixes.1/cmip5/test_hadgem2_cc.py
  tests/integration/cmor/_fixes.1/cmip5/test_hadgem2_es.py
  tests/integration/cmor/_fixes.1/cmip5/test_inmcm4.py
  tests/integration/cmor/_fixes.1/cmip5/test_miroc5.py
  tests/integration/cmor/_fixes.1/cmip5/test_miroc_esm.py
  tests/integration/cmor/_fixes.1/cmip5/test_miroc_esm_chem.py
  tests/integration/cmor/_fixes.1/cmip5/test_mpi_esm_lr.py
  tests/integration/cmor/_fixes.1/cmip5/test_mri_cgcm3.py
  tests/integration/cmor/_fixes.1/cmip5/test_mri_esm1.py
  tests/integration/cmor/_fixes.1/cmip5/test_noresm1_me.py
  tests/integration/cmor/_fixes.1/primavera/__init__.py
  tests/integration/cmor/_fixes.1/primavera/test_ec_earth3_hr.py
  tests/integration/cmor/_fixes.1/test_fix.py
Labels: bug, cmor

#196 Consistent use of the name "ESMValCore" in the documentation
  CONTRIBUTING.md
  NOTICE
  README.md
  doc/api/esmvalcore.rst
  doc/esmvalcore/index.rst
  esmvalcore/utils/doc/gensidebar.py
  meta.yaml
  setup.py
Labels: documentation

#201 Allow non str keys in alias.
  esmvalcore/_recipe.py
  tests/integration/test_recipe.py
Labels: bug, paper

#96 Add sispeed derivation
  esmvalcore/cmor/table.py
  esmvalcore/cmor/tables/custom/CMOR_sispeed.dat
  esmvalcore/cmor/tables/custom/CMOR_sithick.dat
  esmvalcore/preprocessor/_derive/sispeed.py
  esmvalcore/preprocessor/_derive/sithick.py
  tests/integration/preprocessor/_derive/test_sispeed.py
  tests/integration/preprocessor/_derive/test_sithick.py
Labels: enhancement, preprocessor

#191 Fixed NE masking and added possibility to always use them
  esmvalcore/preprocessor/_mask.py
  tests/integration/preprocessor/_mask/test_mask.py
Labels: bug, enhancement

#190 Add derivations and fixes
  esmvalcore/cmor/_fixes/cmip5/cesm1_bgc.py
  esmvalcore/cmor/_fixes/cmip5/miroc_esm.py
  esmvalcore/cmor/tables/custom/CMOR_asr.dat
  esmvalcore/cmor/tables/custom/CMOR_cSoil_grid.dat
  esmvalcore/cmor/tables/custom/CMOR_cVeg_grid.dat
  esmvalcore/cmor/tables/custom/CMOR_gpp_grid.dat
  esmvalcore/cmor/tables/custom/CMOR_lai_grid.dat
  esmvalcore/cmor/tables/custom/CMOR_uajet.dat
  esmvalcore/preprocessor/_derive/asr.py
  esmvalcore/preprocessor/_derive/cSoil_grid.py
  esmvalcore/preprocessor/_derive/cVeg_grid.py
  esmvalcore/preprocessor/_derive/et.py
  esmvalcore/preprocessor/_derive/gpp_grid.py
  esmvalcore/preprocessor/_derive/lai_grid.py
  esmvalcore/preprocessor/_derive/uajet.py
  tests/integration/cmor/_fixes/cmip5/test_miroc_esm.py
  tests/unit/preprocessor/_derive/test_asr.py
  tests/unit/preprocessor/_derive/test_cSoil_grid.py
  tests/unit/preprocessor/_derive/test_cVeg_grid.py
  tests/unit/preprocessor/_derive/test_et.py
  tests/unit/preprocessor/_derive/test_gpp_grid.py
  tests/unit/preprocessor/_derive/test_lai_grid.py
  tests/unit/preprocessor/_derive/test_uajet.py
Labels: fix for dataset, variable derivation
