Repository ESMValGroup/ESMValCore, pull requests merged in 2020-04, with the labels that each got.

#610 make ncl or R tests not fail if package not installed
  tests/integration/test_diagnostic_run.py
Labels: enhancement, testing

#620 Fix derived variable ctotal calculation depending on project and standard name
  esmvalcore/preprocessor/_derive/ctotal.py
  tests/unit/preprocessor/_derive/test_ctotal.py
Labels: enhancement, preprocessor

#623 pin flake8<3.8.0
  setup.py
Labels: installation

#604 Extended fix for cl-like variables of CESM2 models
  esmvalcore/cmor/_fixes/cmip6/cesm2.py
  esmvalcore/cmor/_fixes/cmip6/cesm2_waccm.py
  esmvalcore/cmor/_fixes/shared.py
  esmvalcore/iris_helpers.py
  esmvalcore/preprocessor/_derive/_shared.py
  esmvalcore/preprocessor/_derive/alb.py
  esmvalcore/preprocessor/_derive/lwp.py
  tests/integration/cmor/_fixes/cmip6/test_cesm2.py
  tests/integration/cmor/_fixes/cmip6/test_cesm2_waccm.py
  tests/integration/cmor/_fixes/test_common.py
  tests/integration/cmor/_fixes/test_shared.py
  tests/unit/test_iris_helpers.py
Labels: fix for dataset
