Repository ESMValGroup/ESMValCore, pull requests merged in 2020-09, with the labels that each got.

#745 Run tests in parallel and when building conda package
  .circleci/config.yml
  doc/contributing.rst
  package/meta.yaml
  setup.cfg
  setup.py
  tests/integration/cmor/test_table.py
  tests/unit/preprocessor/_area/test_area.py
Labels: enhancement, testing

#629 Fix cmip6 models
  esmvalcore/cmor/_fixes/cmip6/bcc_csm2_mr.py
  esmvalcore/cmor/_fixes/cmip6/cesm2.py
  esmvalcore/cmor/_fixes/cmip6/fgoals_g3.py
  esmvalcore/cmor/_fixes/cmip6/gfdl_esm4.py
  esmvalcore/cmor/_fixes/cmip6/noresm2_lm.py
  esmvalcore/cmor/_fixes/common.py
  tests/integration/cmor/_fixes/cmip6/test_bcc_csm2_mr.py
  tests/integration/cmor/_fixes/cmip6/test_cesm2.py
  tests/integration/cmor/_fixes/cmip6/test_gfdl_esm4.py
  tests/integration/cmor/_fixes/cmip6/test_noresm2_lm.py
Labels: fix for dataset

#780 Replace vmprof with vprof
  doc/quickstart/configure.rst
  environment.yml
  esmvalcore/_task.py
  package/meta.yaml
  setup.py
  tests/unit/task/test_diagnostic_task.py
Labels: installation

#706 Update CMIP6 tables to 6.9.32
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_3hr.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_6hrLev.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_6hrPlev.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_6hrPlevPt.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_AERday.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_AERhr.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_AERmon.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_AERmonZ.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_Amon.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_CF3hr.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_CFday.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_CFmon.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_CFsubhr.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_CV.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_E1hr.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_E1hrClimMon.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_E3hr.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_E3hrPt.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_E6hrZ.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_Eday.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_EdayZ.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_Efx.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_Emon.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_EmonZ.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_Esubhr.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_Eyr.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_IfxAnt.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_IfxGre.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_ImonAnt.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_ImonGre.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_IyrAnt.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_IyrGre.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_LImon.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_Lmon.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_Oclim.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_Oday.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_Odec.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_Ofx.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_Omon.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_Oyr.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_SIday.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_SImon.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_coordinate.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_day.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_formula_terms.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_fx.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_grids.json
  esmvalcore/cmor/tables/cmip6/Tables/CMIP6_input_example.json
  esmvalcore/cmor/tables/cmip6/VERSION
  esmvalcore/cmor/tables/cmip6/ci-support/checkout_merge_commit.sh
  esmvalcore/cmor/tables/cmip6/scripts/CMIP6_CV_cron_github.sh
  esmvalcore/cmor/tables/cmip6/scripts/README.md
  esmvalcore/cmor/tables/cmip6/scripts/createCMIP6CV.py
  tests/integration/cmor/test_table.py
  tests/integration/test_recipe.py
Labels: cmor

#791 Default config-user path now set in config-user read function
  esmvalcore/_config.py
  esmvalcore/_main.py
Labels: enhancement
