Repository ESMValGroup/ESMValCore, pull requests merged in 2020-02, with the labels that each got.

#98 Enhance error when input files are not found
  esmvalcore/_data_finder.py
  esmvalcore/_recipe.py
  esmvalcore/_recipe_checks.py
  esmvalcore/preprocessor/_derive/__init__.py
  tests/integration/data_finder.yml
  tests/integration/test_data_finder.py
Labels: documentation, enhancement

#460 Added custom CMOR table for hurStderr
  esmvalcore/cmor/tables/custom/CMOR_hurStderr.dat
Labels: cmor

#467 Update alias to include also activity if necessary
  esmvalcore/_recipe.py
  tests/integration/test_recipe.py
Labels: enhancement

#465 Better default configuration
  doc/esmvalcore/config.rst
  esmvalcore/_config.py
  esmvalcore/_main.py
  esmvalcore/_recipe.py
  esmvalcore/_task.py
  esmvalcore/config-user.yml
  tests/integration/test_recipe.py
Labels: enhancement

#358 Support for ERA5 data in native format
  doc/esmvalcore/fixing_data.rst
  esmvalcore/_data_finder.py
  esmvalcore/_recipe.py
  esmvalcore/cmor/_fixes/cmip5/gfdl_esm2g.py
  esmvalcore/cmor/_fixes/fix.py
  esmvalcore/cmor/_fixes/native6/__init__.py
  esmvalcore/cmor/_fixes/native6/era5.py
  esmvalcore/cmor/fix.py
  esmvalcore/cmor/table.py
  esmvalcore/config-developer.yml
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_io.py
  esmvalcore/preprocessor/_regrid.py
  tests/integration/cmor/_fixes/cmip5/test_access1_0.py
  tests/integration/cmor/_fixes/cmip5/test_access1_3.py
  tests/integration/cmor/_fixes/cmip5/test_bcc_csm1_1.py
  tests/integration/cmor/_fixes/cmip5/test_bcc_csm1_1_m.py
  tests/integration/cmor/_fixes/cmip5/test_bnu_esm.py
  tests/integration/cmor/_fixes/cmip5/test_canesm2.py
  tests/integration/cmor/_fixes/cmip5/test_ccsm4.py
  tests/integration/cmor/_fixes/cmip5/test_cesm1_bgc.py
  tests/integration/cmor/_fixes/cmip5/test_cnrm_cm5.py
  tests/integration/cmor/_fixes/cmip5/test_ec_earth.py
  tests/integration/cmor/_fixes/cmip5/test_fgoals_g2.py
  tests/integration/cmor/_fixes/cmip5/test_fio_esm.py
  tests/integration/cmor/_fixes/cmip5/test_gfdl_cm2p1.py
  tests/integration/cmor/_fixes/cmip5/test_gfdl_cm3.py
  tests/integration/cmor/_fixes/cmip5/test_gfdl_esm2g.py
  tests/integration/cmor/_fixes/cmip5/test_gfdl_esm2m.py
  tests/integration/cmor/_fixes/cmip5/test_hadgem2_cc.py
  tests/integration/cmor/_fixes/cmip5/test_hadgem2_es.py
  tests/integration/cmor/_fixes/cmip5/test_inmcm4.py
  tests/integration/cmor/_fixes/cmip5/test_miroc5.py
  tests/integration/cmor/_fixes/cmip5/test_miroc_esm.py
  tests/integration/cmor/_fixes/cmip5/test_miroc_esm_chem.py
  tests/integration/cmor/_fixes/cmip5/test_mpi_esm_lr.py
  tests/integration/cmor/_fixes/cmip5/test_mri_cgcm3.py
  tests/integration/cmor/_fixes/cmip5/test_mri_esm1.py
  tests/integration/cmor/_fixes/cmip5/test_noresm1_me.py
  tests/integration/cmor/_fixes/cmip6/test_cesm2.py
  tests/integration/cmor/_fixes/cmip6/test_cesm2_waccm.py
  tests/integration/cmor/_fixes/cmip6/test_hadgem3_gc31_ll.py
  tests/integration/cmor/_fixes/cmip6/test_ipsl_cm6a_lr.py
  tests/integration/cmor/_fixes/cmip6/test_mcm_ua_1_0.py
  tests/integration/cmor/_fixes/cmip6/test_ukesm1_0_ll.py
  tests/integration/cmor/_fixes/native6/test_era5.py
  tests/integration/cmor/_fixes/obs4mips/test_ssmi.py
  tests/integration/cmor/_fixes/obs4mips/test_ssmi_meris.py
  tests/integration/cmor/_fixes/test_fix.py
  tests/integration/preprocessor/_regrid/test_get_file_levels.py
  tests/integration/test_recipe.py
  tests/unit/cmor/test_fix.py
  tests/unit/data_finder/test_get_start_end_year.py
Labels: cmor, enhancement

#468 Try to add is-enes3 community and is-enes3 grant to zenodo and update authors
  .zenodo.json
  CITATION.cff
Labels: enhancement

#280 Attempt concatenation when cubes have overlapping data
  doc/esmvalcore/datafinder.rst
  esmvalcore/preprocessor/_io.py
  tests/integration/preprocessor/_io/test_concatenate.py
Labels: enhancement, preprocessor

#457 Fix areacello in CMIP5 EC-Earth
  esmvalcore/cmor/_fixes/cmip5/ec_earth.py
  esmvalcore/cmor/_fixes/shared.py
  tests/integration/cmor/_fixes/cmip5/test_ec_earth.py
  tests/integration/cmor/_fixes/test_shared.py
Labels: fix for dataset

#455 Added test for check of data availability and fixed some checks for _recipe.py
  esmvalcore/_recipe_checks.py
  tests/integration/cmor/_fixes/cmip5/test_ec_earth.py
  tests/integration/test_recipe.py
  tests/integration/test_recipe_checks.py
Labels: enhancement

#482 Fix extract month
  esmvalcore/preprocessor/_time.py
  tests/unit/preprocessor/_time/test_time.py
Labels: bug, preprocessor

#473 Fix sithick derivation when units of siconc are %
  esmvalcore/preprocessor/_derive/sithick.py
  tests/integration/preprocessor/_derive/test_sithick.py
Labels: variable derivation

#404 Add preprocessor to clip values to a given minimum and/or maximum value
  doc/esmvalcore/preprocessor.rst
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_other.py
  tests/unit/preprocessor/_other/__init__.py
  tests/unit/preprocessor/_other/test_other.py
Labels: preprocessor

#472 Add regrid to sispeed derivation when siu and siv are not in the same grid
  esmvalcore/preprocessor/_derive/sispeed.py
  tests/integration/preprocessor/_derive/test_sispeed.py
Labels: variable derivation

#166 Added warning and automatic fix for no bounds
  esmvalcore/cmor/check.py
  tests/unit/cmor/test_cmor_check.py
Labels: cmor, enhancement

#323 Improve extract levels
  .gitignore
  doc/esmvalcore/config.rst
  doc/esmvalcore/datafinder.rst
  doc/esmvalcore/preprocessor.rst
  esmvalcore/preprocessor/_regrid.py
  tests/unit/preprocessor/_regrid/test__create_cube.py
  tests/unit/preprocessor/_regrid/test_extract_levels.py
Labels: preprocessor

#495 Remove attributes DimCoord and/or AuxCoord attribute from time coordinate
  esmvalcore/cmor/check.py
  tests/unit/cmor/test_cmor_check.py
Labels: cmor, data issue, enhancement

#475 Extend checks to Iris aux coords
  esmvalcore/cmor/check.py
  tests/unit/cmor/test_cmor_check.py
Labels: preprocessor

#500 minor bugfix in CMOR fix for CMIP5 model HadGEM2-ES
  esmvalcore/cmor/_fixes/cmip5/hadgem2_es.py
Labels: bug, fix for dataset

#335 time filter preprocessor
  doc/esmvalcore/preprocessor.rst
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_time.py
  tests/unit/preprocessor/_time/test_time.py
Labels: preprocessor

#499 Include alias in MultiModel attributes
  esmvalcore/_recipe.py
Labels: enhancement, preprocessor

#492 added test for simple mask combination for a small threshold for mask_fillvalues
  doc/esmvalcore/preprocessor.rst
  esmvalcore/preprocessor/_mask.py
  tests/integration/preprocessor/_mask/test_mask.py
Labels: documentation, enhancement

#300 Add option to standardize to anomalies preprocessor function
  doc/esmvalcore/preprocessor.rst
  esmvalcore/preprocessor/_time.py
  tests/unit/preprocessor/_time/test_time.py
Labels: preprocessor

#478 Add preprocessor extract_point function
  doc/esmvalcore/preprocessor.rst
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_regrid.py
  tests/integration/preprocessor/_regrid/test_extract_point.py
  tests/unit/preprocessor/_regrid/test_extract_point.py
Labels: preprocessor

#476 Add option to round only specified coordinates
  esmvalcore/cmor/_fixes/shared.py
  tests/integration/cmor/_fixes/test_shared.py
Labels: enhancement, preprocessor

#523 Minor improvements to installation
  .stickler.yml
  CONTRIBUTING.md
  environment.yml
  setup.py
Labels: installation

#506 Added documentation to avoid using leading 0s to specify years in recipe
  doc/esmvalcore/recipe.rst
Labels: documentation
