Repository ESMValGroup/ESMValCore, pull requests merged in 2020-10, with the labels that each got.

#729 Fix crash for FGOALS-g2 variables without longitude coordinate
  esmvalcore/cmor/_fixes/shared.py
  tests/integration/cmor/_fixes/cmip5/test_fgoals_g2.py
Labels: bug, fix for dataset

#692 Add custom variable lweGrace
  esmvalcore/cmor/tables/custom/CMOR_lweGrace.dat
Labels: cmor

#702 fix siconca variable in EC-Earth3 and EC-Earth3-Veg models in amip simulation
  esmvalcore/cmor/_fixes/cmip6/ec_earth3.py
  esmvalcore/cmor/_fixes/cmip6/ec_earth3_veg.py
  tests/integration/cmor/_fixes/cmip6/test_ec_earth3.py
  tests/integration/cmor/_fixes/cmip6/test_ec_earth3_veg.py
Labels: fix for dataset

#720 Add surface chlorophyll concentration as a derived variable
  esmvalcore/cmor/tables/custom/CMOR_chlora.dat
  esmvalcore/preprocessor/_derive/chlora.py
Labels: preprocessor

#595 Improve variable alias managament
  doc/recipe/overview.rst
  esmvalcore/_data_finder.py
  esmvalcore/_recipe.py
  esmvalcore/cmor/table.py
  esmvalcore/cmor/variable_alt_names.yml
  esmvalcore/preprocessor/_io.py
  tests/integration/cmor/test_table.py
  tests/integration/data_finder.yml
  tests/integration/preprocessor/_io/test_save.py
  tests/integration/test_recipe.py
Labels: bug, cmor

#776 Use dask to reduce memory consumption of extract_levels for masked data
  esmvalcore/preprocessor/_regrid.py
  tests/unit/preprocessor/_regrid/test_extract_levels.py
Labels: enhancement, preprocessor

#721 Improve command line run documentation
  doc/quickstart/run.rst
  esmvalcore/_main.py
Labels: documentation

#810 Update the zenodo file with contributors (continued)
  .zenodo.json
Labels: documentation

#811 Release notes v2.1
  .zenodo.json
  CITATION.cff
  doc/changelog.rst
  esmvalcore/_version.py
  package/meta.yaml
Labels: documentation

#754 Fix units after derivation
  doc/changelog.rst
  esmvalcore/cmor/check.py
  esmvalcore/preprocessor/_derive/__init__.py
  esmvalcore/preprocessor/_derive/_shared.py
  esmvalcore/preprocessor/_derive/lvp.py
  esmvalcore/preprocessor/_derive/ohc.py
  esmvalcore/preprocessor/_derive/sispeed.py
  esmvalcore/preprocessor/_derive/sm.py
  esmvalcore/preprocessor/_derive/toz.py
  esmvalcore/preprocessor/_derive/vegfrac.py
  tests/integration/preprocessor/_derive/test_interface.py
Labels: bug, variable derivation

#820 Create Github Actions workflow to build and deploy on Test PyPi and PyPi
  .github/workflows/action-pypi-build-and-deploy.yml
  pyproject.toml
  setup.py
Labels: deployment

#759 Add trend preprocessor
  doc/recipe/preprocessor.rst
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_trend.py
  tests/unit/preprocessor/_trend/test_trend.py
Labels: enhancement, preprocessor

#824 Remove duplicate entries from v2.1.0 changelog
  .pre-commit-config.yaml
  doc/changelog.rst
  doc/conf.py
Labels: documentation

#825 Build and publish the esmvalcore package to conda via Github Actions workflow
  .github/workflows/action-conda-publish.yml
  doc/changelog.rst
Labels: testing

#827 Trigger pypi on release and conditional conda build on master
  .github/workflows/action-conda-publish.yml
  .github/workflows/action-pypi-build-and-deploy.yml
Labels: installation, testing

#813 Update instructions for making a release
  doc/contributing.rst
Labels: documentation

#838 Fix numbering of steps in release instructions
  doc/contributing.rst
Labels: documentation

#850 Add requests as a dependency
  package/meta.yaml
  setup.py
Labels: installation
