Repository ESMValGroup/ESMValCore, pull requests merged in 2020-01, with the labels that each got.

#421 Use alias instead of dataset in max datasets log
  esmvalcore/_recipe.py
Labels: enhancement

#413 Consistently use dimension/coordinate names in VariableInfo.coordinates
  esmvalcore/cmor/table.py
Labels: cmor, enhancement

#351 Fix regrid time function to add year yr frequency and remove resetting calendars
  doc/esmvalcore/preprocessor.rst
  esmvalcore/preprocessor/_time.py
  tests/unit/preprocessor/_time/test_time.py
Labels: bug, documentation, enhancement, preprocessor

#426 Fixes for MCM-UA-1-0 (CMIP6)
  esmvalcore/cmor/_fixes/cmip6/mcm_ua_1_0.py
  tests/integration/cmor/_fixes/cmip6/test_mcm_ua_1_0.py
  tests/integration/cmor/_fixes/test_shared.py
Labels: fix for dataset

#269 Support CMIP3
  .gitignore
  esmvalcore/_data_finder.py
  esmvalcore/_recipe.py
  esmvalcore/cmor/check.py
  esmvalcore/cmor/table.py
  esmvalcore/cmor/tables/cmip3/.gitignore
  esmvalcore/cmor/tables/cmip3/README.md
  esmvalcore/cmor/tables/cmip3/Tables/IPCC_table_A1
  esmvalcore/cmor/tables/cmip3/Tables/IPCC_table_A2
  esmvalcore/cmor/tables/cmip3/Tables/IPCC_table_A3
  esmvalcore/cmor/tables/cmip3/Tables/IPCC_table_A4
  esmvalcore/cmor/tables/cmip3/Tables/IPCC_table_A5
  esmvalcore/cmor/tables/cmip3/Tables/IPCC_table_O1
  esmvalcore/config-developer.yml
  tests/integration/cmor/test_table.py
  tests/integration/test_recipe.py
  tests/unit/data_finder/test_get_start_end_year.py
Labels: cmor, enhancement, workshop

#433 [URGENT] Rename zonal_means to zonal_statistics
  doc/esmvalcore/preprocessor.rst
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_area.py
Labels: help wanted, preprocessor

#366 Support downloading fx files using synda
  esmvalcore/preprocessor/_download.py
Labels: enhancement

#432 Allowed arbitrary CMIP6 fx variables in special preprocessors and added a catch on project not found in config-developer (invalid project)
  esmvalcore/_config.py
  esmvalcore/_recipe.py
  tests/integration/test_recipe.py
Labels: bug, preprocessor

#427 Log max memory used by the recipe in the main log
  esmvalcore/_task.py
Labels: enhancement

#183 Add the CORDEX project to ESMValTool
  .codacy.yml
  esmvalcore/cmor/tables/cordex/Lib/gen_table_md5s.py
  esmvalcore/cmor/tables/cordex/Lib/tables_manip_tools.py
  esmvalcore/cmor/tables/cordex/RELEASE-NOTES
  esmvalcore/cmor/tables/cordex/Tables/CORDEX_3h
  esmvalcore/cmor/tables/cordex/Tables/CORDEX_6h
  esmvalcore/cmor/tables/cordex/Tables/CORDEX_day
  esmvalcore/cmor/tables/cordex/Tables/CORDEX_fx
  esmvalcore/cmor/tables/cordex/Tables/CORDEX_grids
  esmvalcore/cmor/tables/cordex/Tables/CORDEX_mon
  esmvalcore/cmor/tables/cordex/Tables/CORDEX_sem
  esmvalcore/cmor/tables/cordex/Tables/md5s
  esmvalcore/cmor/tables/cordex/VERSION
  esmvalcore/config-developer.yml
  esmvalcore/config-user.yml
  tests/integration/cmor/test_table.py
  tests/integration/test_recipe.py
Labels: enhancement

#396 Fix unit tests to check for numpy array mask equality as well
  tests/__init__.py
  tests/integration/preprocessor/_mask/test_mask.py
  tests/integration/preprocessor/_regrid/test_extract_levels.py
  tests/integration/preprocessor/_regrid/test_regrid.py
  tests/unit/preprocessor/_area/test_area.py
  tests/unit/preprocessor/_mask/test_mask.py
  tests/unit/preprocessor/_multimodel/test_multimodel.py
  tests/unit/preprocessor/_regrid/test__stock_cube.py
  tests/unit/preprocessor/_regrid/test_extract_levels.py
  tests/unit/preprocessor/_regrid_esmpy/test_regrid_esmpy.py
  tests/unit/preprocessor/_time/test_time.py
  tests/unit/preprocessor/_units/test_convert_units.py
  tests/unit/preprocessor/_volume/test_volume.py
Labels: bug
