Repository ESMValGroup/ESMValCore, pull requests merged in 2020-11, with the labels that each got.

#852 Fix path settings for DKRZ/Mistral
  esmvalcore/config-user.yml
Labels: documentation

#598 CMOR check generic level coordinates in CMIP6
  esmvalcore/cmor/check.py
  esmvalcore/cmor/table.py
  tests/unit/cmor/test_cmor_check.py
Labels: cmor

#870 Pin Python to less than 3.9
  environment.yml
  package/meta.yaml
Labels: installation

#878 Pin cftime>=1.3.0 to have newer string formatting in and fix two tests
  environment.yml
  package/meta.yaml
  tests/integration/cmor/_fixes/cmip5/test_access1_0.py
  tests/integration/cmor/_fixes/cmip5/test_access1_3.py
Labels: installation, testing

#796 Added clip_start_end_year preprocessor
  esmvalcore/_recipe.py
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_time.py
  tests/integration/test_recipe.py
  tests/unit/preprocessor/_time/test_time.py
Labels: preprocessor

#880 Remove numba dependendy
  doc/requirements.txt
  esmvalcore/preprocessor/_derive/_shared.py
  esmvalcore/preprocessor/_derive/toz.py
  package/meta.yaml
  setup.py
  tests/unit/preprocessor/_derive/test_p_level_widths.py
  tests/unit/preprocessor/_derive/test_shared.py
  tests/unit/preprocessor/_derive/test_toz.py
Labels: enhancement, installation, variable derivation

#873 switched miniconda conda setup hooks for Github Actions workflows
  .github/workflows/action-conda-publish.yml
  .github/workflows/action-install-from-conda.yml
  .github/workflows/action-install-from-pypi.yml
  .github/workflows/action-install-from-source.yml
  .github/workflows/action-test.yml
Labels: testing

#699 Add support for downloading CMIP6 data with Synda
  esmvalcore/preprocessor/_download.py
  tests/unit/data_finder/test_get_start_end_year.py
  tests/unit/data_finder/test_select_files.py
  tests/unit/preprocessor/test_download.py
Labels: preprocessor
