Repository ESMValGroup/ESMValCore, pull requests merged in 2021-10, with the labels that each got.

#1259 Move institutes from config-developer.yml to default extra facets config and add wildcard support for extra facets
  doc/quickstart/configure.rst
  doc/quickstart/find_data.rst
  esmvalcore/_config/_config.py
  esmvalcore/_config/extra_facets/cmip3-institutes.yml
  esmvalcore/_config/extra_facets/cmip5-institutes.yml
  esmvalcore/_config/extra_facets/cmip5-product.yml
  esmvalcore/_recipe.py
  esmvalcore/config-developer.yml
  tests/unit/config/test_config.py
Labels: enhancement, backwards incompatible change

#1321 Add support for re-using preprocessor output from previous runs
  doc/quickstart/run.rst
  doc/recipe/overview.rst
  esmvalcore/_config/_config.py
  esmvalcore/_main.py
  esmvalcore/_provenance.py
  esmvalcore/_recipe.py
  esmvalcore/_task.py
  esmvalcore/experimental/config/_config_object.py
  esmvalcore/experimental/config/_config_validators.py
  esmvalcore/preprocessor/__init__.py
  tests/integration/test_recipe.py
  tests/unit/config/test_config.py
  tests/unit/main/test_esmvaltool.py
  tests/unit/main/test_parse_resume.py
  tests/unit/provenance/__init__.py
  tests/unit/provenance/test_trackedfile.py
  tests/unit/task/test_resume_task.py
  tests/unit/test_recipe.py
Labels: enhancement

#1296 Log fewer messages to screen and hide stack trace for known recipe errors
  doc/api/esmvalcore.exceptions.rst
  doc/api/esmvalcore.rst
  esmvalcore/_config/_config.py
  esmvalcore/_data_finder.py
  esmvalcore/_main.py
  esmvalcore/_recipe.py
  esmvalcore/_recipe_checks.py
  esmvalcore/cmor/check.py
  esmvalcore/exceptions.py
  esmvalcore/preprocessor/_area.py
  esmvalcore/preprocessor/_time.py
  esmvalcore/preprocessor/_volume.py
  tests/integration/test_main.py
  tests/integration/test_recipe.py
  tests/integration/test_recipe_checks.py
  tests/sample_data/experimental/test_run_recipe.py
  tests/unit/config/test_config.py
  tests/unit/data_finder/test_replace_tags.py
  tests/unit/test_main.py
  tests/unit/test_recipe.py
Labels: UX

#1177 Automatically fix small deviations in vertical levels
  doc/recipe/preprocessor.rst
  esmvalcore/cmor/check.py
  esmvalcore/preprocessor/_regrid.py
  tests/integration/preprocessor/_regrid/test_extract_levels.py
  tests/unit/cmor/test_cmor_check.py
  tests/unit/preprocessor/_regrid/test_extract_levels.py
Labels: cmor

#1344 Add fix for CIESM pr
  esmvalcore/cmor/_fixes/cmip6/ciesm.py
  tests/integration/cmor/_fixes/cmip6/test_ciesm.py
Labels: fix for dataset

#1304 Fix DRS for IPSLCM : split attribute 'freq' into : 'out' and 'freq'
  doc/develop/fixing_data.rst
  esmvalcore/config-developer.yml
Labels: fix for dataset, backwards incompatible change

#1356 Add "grid" as a tag to the output file template for CMIP6
  esmvalcore/config-developer.yml
Labels: enhancement, backwards incompatible change
