Repository ESMValGroup/ESMValCore, pull requests merged in 2021-05, with the labels that each got.

#1095 Supported `mip`-level fixes
  esmvalcore/cmor/_fixes/cmip6/cesm2.py
  esmvalcore/cmor/_fixes/fix.py
  esmvalcore/cmor/_fixes/shared.py
  tests/integration/cmor/_fixes/cmip6/test_cesm2.py
  tests/integration/cmor/_fixes/test_fix.py
  tests/integration/cmor/_fixes/test_shared.py
Labels: enhancement, fix for dataset

#1092 Fix erroneous use of `grid_latitude` and `grid_longitude` and cleaned ocean grid fixes
  esmvalcore/cmor/_fixes/cmip5/bcc_csm1_1.py
  esmvalcore/cmor/_fixes/cmip5/bcc_csm1_1_m.py
  esmvalcore/cmor/_fixes/cmip6/bcc_csm2_mr.py
  esmvalcore/cmor/_fixes/cmip6/bcc_esm1.py
  esmvalcore/cmor/_fixes/cmip6/fgoals_g3.py
  esmvalcore/cmor/_fixes/common.py
  tests/integration/cmor/_fixes/cmip5/test_bcc_csm1_1.py
  tests/integration/cmor/_fixes/cmip5/test_bcc_csm1_1_m.py
  tests/integration/cmor/_fixes/cmip6/test_bcc_csm2_mr.py
  tests/integration/cmor/_fixes/cmip6/test_bcc_esm1.py
  tests/integration/cmor/_fixes/cmip6/test_fgoals_g3.py
  tests/integration/cmor/_fixes/test_common.py
Labels: cmor, fix for dataset

#1098 ocean depth fix for cnrm_esm2_1, gfdl_esm4, ipsl_cm6a_lr datasets + mcm_ua_1_0
  doc/develop/fixing_data.rst
  esmvalcore/cmor/_fixes/cmip6/cnrm_esm2_1.py
  esmvalcore/cmor/_fixes/cmip6/gfdl_esm4.py
  esmvalcore/cmor/_fixes/cmip6/ipsl_cm6a_lr.py
  esmvalcore/cmor/_fixes/cmip6/mcm_ua_1_0.py
  tests/integration/cmor/_fixes/cmip6/test_cesm2.py
  tests/integration/cmor/_fixes/cmip6/test_cnrm_esm2_1.py
  tests/integration/cmor/_fixes/cmip6/test_gfdl_esm4.py
  tests/integration/cmor/_fixes/cmip6/test_ipsl_cm6a_lr.py
  tests/integration/cmor/_fixes/cmip6/test_mcm_ua_1_0.py
Labels: AR6, fix for dataset

#1087 Added additional test cases for integration tests of data_finder.py
  tests/integration/data_finder.yml
Labels: testing

#1093 Fixed --skip-nonexistent option
  esmvalcore/_recipe.py
  esmvalcore/preprocessor/_io.py
  tests/integration/preprocessor/_io/test_concatenate.py
  tests/integration/preprocessor/_io/test_save.py
  tests/unit/test_recipe.py
Labels: bug

#1102 Fix for uas variable of the MCM_UA_1_0 dataset
  esmvalcore/cmor/_fixes/cmip6/mcm_ua_1_0.py
  tests/integration/cmor/_fixes/cmip6/test_mcm_ua_1_0.py
Labels: AR6, fix for dataset

#771 Find files for CMIP6 DCPP startdates
  doc/recipe/overview.rst
  esmvalcore/_data_finder.py
  esmvalcore/_recipe.py
  tests/unit/data_finder/test_replace_tags.py
  tests/unit/test_recipe.py
Labels: DCPP support, cmor

#507 Check horizontal grid before regridding
  doc/recipe/preprocessor.rst
  esmvalcore/preprocessor/_regrid.py
  tests/unit/preprocessor/_regrid/test_regrid.py
Labels: preprocessor

#1090 Fixes for sos and siconc of BCC models
  esmvalcore/cmor/_fixes/cmip6/bcc_csm2_mr.py
  esmvalcore/cmor/_fixes/cmip6/bcc_esm1.py
  tests/integration/cmor/_fixes/cmip6/test_bcc_csm2_mr.py
  tests/integration/cmor/_fixes/cmip6/test_bcc_esm1.py
Labels: AR6, fix for dataset

#1140 Pin cf-units and fix tests (cf-units>=2.1.5)
  package/meta.yaml
  setup.py
  tests/integration/cmor/_fixes/cmip5/test_access1_0.py
  tests/integration/cmor/_fixes/cmip5/test_access1_3.py
Labels: testing

#1108 Run fgco2 fix for all CESM2 models
  esmvalcore/cmor/_fixes/cmip6/cesm2_fv2.py
  esmvalcore/cmor/_fixes/cmip6/cesm2_waccm.py
  esmvalcore/cmor/_fixes/cmip6/cesm2_waccm_fv2.py
  tests/integration/cmor/_fixes/cmip6/test_cesm2_fv2.py
  tests/integration/cmor/_fixes/cmip6/test_cesm2_waccm.py
  tests/integration/cmor/_fixes/cmip6/test_cesm2_waccm_fv2.py
Labels: AR6, fix for dataset

#1033 Do not consider CMIP5 variable sit to be the same as sithick from CMIP6
  esmvalcore/cmor/variable_alt_names.yml
Labels: bug
