Repository ESMValGroup/ESMValCore, pull requests merged in 2021-04, with the labels that each got.

#1047 Update contribution guidelines
  .github/pull_request_template.md
  doc/api/esmvalcore.api.config.rst
  doc/api/esmvalcore.rst
  doc/contributing.rst
  doc/develop/derivation.rst
  doc/develop/fixing_data.rst
  doc/develop/index.rst
  doc/develop/preprocessor_function.rst
  doc/interfaces.rst
  doc/quickstart/configure.rst
  doc/quickstart/install.rst
  doc/quickstart/recipes.rst
  doc/recipe/overview.rst
Labels: documentation

#1071 Add key to id_prop
  esmvalcore/preprocessor/_area.py
Labels: AR6, EUCP, bug

#1075 test installation of esmvalcore from conda-forge
  .github/workflows/action-conda-publish.yml
  .github/workflows/action-install-from-conda.yml
Labels: installation, testing

#1061 Fix bounds after reversing coordinate values
  esmvalcore/cmor/check.py
  tests/unit/cmor/test_cmor_check.py
Labels: bug, cmor

#999 Load fx variables as cube cell measures / ancillary variables
  doc/recipe/preprocessor.rst
  esmvalcore/_recipe.py
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_ancillary_vars.py
  esmvalcore/preprocessor/_area.py
  esmvalcore/preprocessor/_mask.py
  esmvalcore/preprocessor/_volume.py
  esmvalcore/preprocessor/_weighting.py
  tests/integration/preprocessor/_ancillary_vars/__init__.py
  tests/integration/preprocessor/_ancillary_vars/test_add_fx_variables.py
  tests/integration/preprocessor/_mask/test_mask.py
  tests/integration/test_recipe.py
  tests/unit/preprocessor/_area/test_area.py
  tests/unit/preprocessor/_mask/test_mask.py
  tests/unit/preprocessor/_other/test_other.py
  tests/unit/preprocessor/_volume/test_volume.py
  tests/unit/preprocessor/_weighting/test_weighting_landsea_fraction.py
Labels: enhancement, preprocessor
