Repository ESMValGroup/ESMValCore, pull requests merged in 2021-02, with the labels that each got.

#973 Fix duplication in preprocessors DEFAULT_ORDER
  esmvalcore/preprocessor/__init__.py
  tests/unit/preprocessor/test_configuration.py
Labels: bug

#917 Improve error messages when data is missing
  esmvalcore/_recipe.py
  esmvalcore/_recipe_checks.py
  tests/integration/test_recipe.py
  tests/integration/test_recipe_checks.py
Labels: UX, enhancement

#966 Fix links to Iris documentation
  README.md
  doc/quickstart/find_data.rst
  doc/recipe/preprocessor.rst
  esmvalcore/preprocessor/_time.py
Labels: bug, documentation

#965 Remove monotonicity coordinate check for unstructured grids
  esmvalcore/cmor/check.py
  tests/unit/cmor/test_cmor_check.py
Labels: cmor

#969 Dataset fixes for MSWEP
  doc/develop/fixing_data.rst
  esmvalcore/cmor/_fixes/native6/mswep.py
  tests/integration/cmor/_fixes/native6/mswep_day.nc
  tests/integration/cmor/_fixes/native6/mswep_month.nc
  tests/integration/cmor/_fixes/native6/test_mswep.py
Labels: fix for dataset

#979 Set remove_preproc_dir to false in default config-user
  esmvalcore/config-user.yml
Labels: UX

#977 Set version to 2.2.0
  CITATION.cff
  doc/contributing.rst
  esmvalcore/_version.py
  package/meta.yaml
Labels: release

#947 Dataset fixes for: ACCESS-ESM1-5, CanESM5, CanESM5 for carbon cycle
  esmvalcore/cmor/_fixes/cmip6/access_esm1_5.py
  esmvalcore/cmor/_fixes/cmip6/canesm5.py
  esmvalcore/cmor/_fixes/cmip6/canesm5_canoe.py
  tests/integration/cmor/_fixes/cmip6/test_access_esm1_5.py
  tests/integration/cmor/_fixes/cmip6/test_canesm5.py
  tests/integration/cmor/_fixes/cmip6/test_canesm5_canoe.py
Labels: fix for dataset

#981 Restore task summary in debug log
  esmvalcore/_task.py
  esmvalcore/preprocessor/__init__.py
  tests/unit/task/test_print.py
Labels: bug

#983 Add first draft of v2.2.0 changelog
  doc/changelog.rst
Labels: documentation

#987 Move fiona to be installed from conda forge
  environment.yml
  setup.py
Labels: installation, release

#986 Bugfix: Fix units for MSWEP data
  esmvalcore/cmor/_fixes/native6/mswep.py
Labels: bug, fix for dataset

#985 Add checkbox in PR template to assign labels
  .github/pull_request_template.md
  doc/contributing.rst
Labels: documentation

#904 Fixes for KIOST-ESM (CMIP6)
  esmvalcore/cmor/_fixes/cmip6/kiost_esm.py
  tests/integration/cmor/_fixes/cmip6/test_kiost_esm.py
Labels: fix for dataset

#848 Update install.rst
  doc/quickstart/install.rst
Labels: documentation

#990 re-added fiona in setup.py
  setup.py
Labels: installation, release

#984 Change the order of the publication steps
  doc/contributing.rst
Labels: documentation

#911 Fixes for AWI-ESM-1-1-LR (CMIP6, piControl)
  esmvalcore/cmor/_fixes/cmip6/awi_esm_1_1_lr.py
  tests/integration/cmor/_fixes/cmip6/test_awi_esm_1_1_lr.py
Labels: fix for dataset

#841 Add instructions how to use esmvaltool from HPC central installations
  doc/quickstart/install.rst
Labels: documentation

#996 Final changelog for 2.2.0
  doc/changelog.rst
Labels: documentation

#994 Report coverage for tests that run on any pull request
  .circleci/config.yml
Labels: testing

#998 Install ESMValTool sample data from PyPI
  setup.py
Labels: testing

#976 Format cmor related files
  esmvalcore/cmor/check.py
  esmvalcore/cmor/fix.py
  esmvalcore/cmor/table.py
Labels: cmor, testing

#1000 Support multiple paths in input_dir
  doc/quickstart/configure.rst
  esmvalcore/_data_finder.py
  tests/unit/data_finder/test_replace_tags.py
Labels: enhancement

#1006 Fix documentation build
  doc/api/esmvalcore.api.config.rst
  esmvalcore/experimental/config/__init__.py
Labels: documentation

#1003 Fix tests for multi-processing with spawn method (i.e. macOSX with Python>3.8)
  tests/integration/test_task.py
Labels: testing

#1010 Extend preprocessor multi_model_statistics to handle data with "altitude" coordinate
  esmvalcore/preprocessor/_multimodel.py
Labels: bug, preprocessor

#1011 Remove scripts included with CMOR tables
  esmvalcore/cmor/tables/cmip6/ci-support/checkout_merge_commit.sh
  esmvalcore/cmor/tables/cmip6/scripts/CMIP6_CV_cron_github.sh
  esmvalcore/cmor/tables/cmip6/scripts/README.md
  esmvalcore/cmor/tables/cmip6/scripts/cleanupTags.py
  esmvalcore/cmor/tables/cmip6/scripts/createCMIP6CV.py
  esmvalcore/cmor/tables/cordex/Lib/gen_table_md5s.py
  esmvalcore/cmor/tables/cordex/Lib/tables_manip_tools.py
Labels: bear at a dinner party

#1017 Added fixes for various CMIP5 datasets, variable cl (3-dim cloud fraction)
  esmvalcore/cmor/_fixes/cmip5/bnu_esm.py
  esmvalcore/cmor/_fixes/cmip5/ccsm4.py
  esmvalcore/cmor/_fixes/cmip5/cesm1_bgc.py
  esmvalcore/cmor/_fixes/cmip5/cesm1_cam5.py
  esmvalcore/cmor/_fixes/cmip5/cesm1_fastchem.py
  esmvalcore/cmor/_fixes/cmip5/cesm1_waccm.py
  esmvalcore/cmor/_fixes/cmip5/fio_esm.py
  esmvalcore/cmor/_fixes/cmip5/gfdl_cm2p1.py
  tests/integration/cmor/_fixes/cmip5/test_bnu_esm.py
  tests/integration/cmor/_fixes/cmip5/test_ccsm4.py
  tests/integration/cmor/_fixes/cmip5/test_cesm1_bgc.py
  tests/integration/cmor/_fixes/cmip5/test_cesm1_cam5.py
  tests/integration/cmor/_fixes/cmip5/test_cesm1_fastchem.py
  tests/integration/cmor/_fixes/cmip5/test_cesm1_waccm.py
  tests/integration/cmor/_fixes/cmip5/test_fio_esm.py
  tests/integration/cmor/_fixes/cmip5/test_gfdl_cm2p1.py
Labels: fix for dataset

#1019 Avoid side effects in extract_season
  esmvalcore/preprocessor/_time.py
  tests/unit/preprocessor/_time/test_time.py
Labels: bug

#1021 Use nearest scheme to avoid interpolation errors with masked data in regression test
  tests/sample_data/multimodel_statistics/test_multimodel.py
  tests/sample_data/multimodel_statistics/timeseries_daily_365_day-full-mean.nc
  tests/sample_data/multimodel_statistics/timeseries_daily_365_day-overlap-mean.nc
  tests/sample_data/multimodel_statistics/timeseries_daily_gregorian-full-mean.nc
  tests/sample_data/multimodel_statistics/timeseries_daily_gregorian-overlap-mean.nc
  tests/sample_data/multimodel_statistics/timeseries_daily_proleptic_gregorian-full-mean.nc
  tests/sample_data/multimodel_statistics/timeseries_daily_proleptic_gregorian-overlap-mean.nc
  tests/sample_data/multimodel_statistics/timeseries_monthly-full-mean.nc
  tests/sample_data/multimodel_statistics/timeseries_monthly-overlap-mean.nc
Labels: bug, testing

#1022 Switch to running the Github Action test workflow every 3 hours in single thread mode to observe if Sementation Faults occur
  .github/workflows/action-test.yml
Labels: testing

#991 Generate HTML report with recipe output
  doc/api/esmvalcore.api.recipe_output.rst
  doc/quickstart/output.rst
  doc/requirements.txt
  esmvalcore/_config/_diagnostics.py
  esmvalcore/_main.py
  esmvalcore/_recipe.py
  esmvalcore/experimental/config/_config_object.py
  esmvalcore/experimental/recipe.py
  esmvalcore/experimental/recipe_info.py
  esmvalcore/experimental/recipe_metadata.py
  esmvalcore/experimental/recipe_output.py
  esmvalcore/experimental/templates/RecipeInfo.j2
  esmvalcore/experimental/templates/RecipeOutput.j2
  esmvalcore/experimental/templates/TaskOutput.j2
  esmvalcore/experimental/templates/__init__.py
  esmvalcore/experimental/templates/head.j2
  esmvalcore/experimental/templates/recipe_output_page.j2
  package/meta.yaml
  setup.py
  tests/integration/config/test_diagnostic.py
  tests/integration/test_diagnostic_run.py
  tests/integration/test_recipe.py
  tests/sample_data/experimental/recipe_api_test.yml
  tests/sample_data/experimental/test_run_recipe.py
  tests/unit/experimental/references/doe2021.bibtex
  tests/unit/experimental/test_output_file.py
  tests/unit/experimental/test_recipe.py
  tests/unit/experimental/test_recipe_info.py
  tests/unit/experimental/test_utils.py
Labels: UX, enhancement
