Repository ESMValGroup/ESMValCore, pull requests merged in 2021-07, with the labels that each got.

#1192 Enhancing MIROC5 fix for hfls and evspsbl
  esmvalcore/cmor/_fixes/cmip5/miroc5.py
Labels: bug, fix for dataset

#1212 Fix alignment of daily data with inconsistent calendars in multimodel statistics
  esmvalcore/preprocessor/_multimodel.py
  tests/unit/preprocessor/_multimodel/test_multimodel.py
Labels: bug, enhancement, preprocessor

#1197 pin cf-units, remove github actions test for Python 3.6 and fix test_access1_0 and test_access1_3 to use cf-units for comparisons
  .github/workflows/action-conda-publish.yml
  .github/workflows/action-install-from-conda.yml
  .github/workflows/action-install-from-pypi.yml
  .github/workflows/action-install-from-source.yml
  .github/workflows/action-test.yml
  environment.yml
  package/meta.yaml
  setup.py
  tests/integration/cmor/_fixes/cmip5/test_access1_0.py
  tests/integration/cmor/_fixes/cmip5/test_access1_3.py
Labels: bug, testing

#1206 Pin lower bound for iris to 3.0.2
  environment.yml
  package/meta.yaml
  setup.py
Labels: deployment, installation, iris

#1215 Filter warnings about collapsing multi-model dimension in multimodel statistics preprocessor function
  esmvalcore/preprocessor/_multimodel.py
  tests/unit/preprocessor/_multimodel/test_multimodel.py
Labels: preprocessor

#1216 Fixed search for fx files when no ``mip`` is given
  doc/recipe/preprocessor.rst
  esmvalcore/_recipe.py
  tests/integration/test_recipe.py
Labels: bug

#1220 Remove fx variables before computing multimodel statistics
  esmvalcore/preprocessor/_multimodel.py
  tests/unit/preprocessor/_multimodel/test_multimodel.py
Labels: enhancement, preprocessor

#1209 Add test to verify behaviour for scalar height coord for tas in multi-model
  tests/unit/preprocessor/_multimodel/test_multimodel.py
Labels: enhancement

#1228 Fix curl install in CircleCI
  .circleci/config.yml
Labels: testing

#1225 Sort missing years in "No input data available for years" message
  esmvalcore/_recipe_checks.py
  tests/integration/test_recipe_checks.py
Labels: enhancement

#1237 Make sure climate statistics always returns original dtype
  esmvalcore/preprocessor/_time.py
  tests/unit/preprocessor/_time/test_time.py
Labels: bug, preprocessor

#1231 Bugfix for regional regridding when non-integer range is passed
  esmvalcore/preprocessor/_regrid.py
  tests/unit/preprocessor/_regrid/test_extract_regional_grid.py
Labels: bug

#1239 Make sure area_statistics preprocessor always returns original dtype
  esmvalcore/preprocessor/_area.py
  tests/unit/preprocessor/_area/test_area.py
Labels: bug, preprocessor

#1233 Add a more friendly and useful message when using default config file
  .circleci/config.yml
  esmvalcore/_config/_config.py
  esmvalcore/_main.py
  esmvalcore/_recipe_checks.py
  esmvalcore/config-user.yml
  tests/integration/test_main.py
  tests/unit/experimental/test_config.py
Labels: UX

#1248 Add "." (dot) as allowed separation character for the time range group
  esmvalcore/_data_finder.py
  tests/unit/data_finder/test_get_start_end_year.py
Labels: bug

#1252 Pin `iris<3.0.4` to ensure we still (sort of) support Python 3.6
  environment.yml
  package/meta.yaml
  setup.py
Labels: deployment, installation, iris, release, testing

#1253 Bugfix release: set version to 2.3.1
  CITATION.cff
  doc/contributing.rst
  esmvalcore/_version.py
  package/meta.yaml
Labels: release

#1255 Changelog 2.3.1
  doc/changelog.rst
Labels: documentation

#1200 Drop support for Python 3.6
  doc/recipe/preprocessor.rst
  environment.yml
  package/meta.yaml
  setup.py
  tests/integration/preprocessor/_io/test_concatenate.py
Labels: deployment, installation, testing

#1182 Allow more recent version of `scipy`
  environment.yml
  package/meta.yaml
  tests/integration/cmor/_fixes/cmip5/test_bcc_csm1_1.py
  tests/integration/cmor/_fixes/test_common.py
Labels: installation, testing

#1243 Speed up conda build `conda_build` Circle test by using `mamba` solver via `boa` (and use it for Github Actions test too)
  .circleci/config.yml
  .github/workflows/action-conda-publish.yml
  package/meta.yaml
Labels: deployment, enhancement, installation, testing
