Repository ESMValGroup/ESMValCore, pull requests merged in 2021-08, with the labels that each got.

#1261 Replace os.walk by glob.glob in data finder (only look for data in the specified locations)
  esmvalcore/_data_finder.py
  setup.py
  tests/sample_data/experimental/test_run_recipe.py
Labels: backwards incompatible change

#1274 Fix numpy deprecation warnings
  tests/integration/preprocessor/_regrid/test_extract_point.py
Labels: testing

#1275 Unpin upper bound for iris (previously was at <3.0.4)
  .github/workflows/action-install-from-source.yml
  .github/workflows/action-test.yml
  environment.yml
  package/meta.yaml
  setup.py
Labels: installation, iris, testing

#1280 modernize `conda_install` test on Circle CI by installing from conda-forge with Python 3.9 and change install instructions in documentation
  .circleci/config.yml
  doc/contributing.rst
  doc/quickstart/install.rst
Labels: testing

#1292 Add fix for differing latitude coordinate between historical and ssp585 in MPI-ESM1-2-HR r2i1p1f1
  esmvalcore/cmor/_fixes/cmip6/mpi_esm1_2_hr.py
  tests/integration/cmor/_fixes/cmip6/test_mpi_esm1_2_hr.py
Labels: fix for dataset

#1290 Add fixes for time and latitude coordinate of EC-Earth3 r3i1p1f1
  esmvalcore/cmor/_fixes/cmip6/ec_earth3.py
  tests/integration/cmor/_fixes/cmip6/test_ec_earth3.py
Labels: fix for dataset

#1284 Run a nightly Github Actions workflow to monitor tests memory per test (configurable for other metrics too)
  .github/workflows/action-test-monitor.yml
  .gitignore
  tests/integration/cmor/_fixes/cmip6/__init__.py
  tests/integration/cmor/_fixes/ipslcm/__init__.py
  tests/integration/cmor/_fixes/native6/__init__.py
  tests/integration/cmor/_fixes/obs4mips/__init__.py
  tests/integration/cmor/_fixes/test_data/__init__.py
  tests/integration/config/__init__.py
  tests/integration/esgf/__init__.py
  tests/parse_pymon.py
  tests/sample_data/__init__.py
  tests/sample_data/experimental/__init__.py
  tests/sample_data/multimodel_statistics/__init__.py
  tests/unit/data_finder/__init__.py
  tests/unit/experimental/__init__.py
  tests/unit/preprocessor/_cycles/__init__.py
  tests/unit/preprocessor/_detrend/__init__.py
  tests/unit/preprocessor/_trend/__init__.py
  tests/unit/preprocessor/_weighting/__init__.py
Labels: enhancement, testing
