Repository ESMValGroup/ESMValCore, pull requests merged in 2021-01, with the labels that each got.

#900 Refer to ESMValTool GitHub discussions page in the error message
  esmvalcore/_main.py
Labels: documentation

#922 Support automatically closing issues
  .github/pull_request_template.md
Labels: documentation

#924 Adding custom variables for tas uncertainty
  esmvalcore/cmor/tables/custom/CMOR_tasConf5.dat
  esmvalcore/cmor/tables/custom/CMOR_tasConf95.dat
  tests/integration/cmor/test_table.py
Labels: cmor

#916 Changed latitude longitude fix from Tas to AllVars.
  esmvalcore/cmor/_fixes/cmip6/cesm2.py
Labels: fix for dataset

#879 Fix for precipitation (pr) to use ERA5-Land cmorizer
  esmvalcore/cmor/_fixes/native6/era5_land.py
Labels: fix for dataset

#860 Skip variables that don't have dataset or additional_dataset keys
  esmvalcore/_recipe.py
  tests/integration/test_recipe.py
Labels: enhancement

#837 Cmip6 fix ec earth3
  esmvalcore/cmor/_fixes/cmip6/ec_earth3.py
  tests/integration/cmor/_fixes/cmip6/test_ec_earth3.py
Labels: fix for dataset

#831 cmip6_fix_fgoals_f3_l_Amon_time_bnds
  esmvalcore/cmor/_fixes/cmip6/fgoals_f3_l.py
  tests/integration/cmor/_fixes/cmip6/test_fgoals_f3_l.py
Labels: fix for dataset

#921 Avoid hardcoded year in tests and add improvement to plev test case
  tests/integration/cmor/_fixes/native6/test_era5.py
Labels: testing

#667 Fix for FGOALS-f3-L sftlf
  esmvalcore/cmor/_fixes/cmip6/fgoals_f3_l.py
Labels: fix for dataset

#928 Pin scipy to less than 1.6.0 until ESMValGroup/ESMValCore/issues/927 gets resolved
  environment.yml
  package/meta.yaml
  tests/integration/cmor/test_table.py
Labels: installation, testing

#930 Github Actions: change time when conda install test runs
  .github/workflows/action-install-from-conda.yml
Labels: testing

#935 remove redundant test line from test_utils.py
  tests/unit/experimental/test_utils.py
Labels: testing

#685 Simplify time handling in multi-model statistics preprocessor
  doc/recipe/preprocessor.rst
  esmvalcore/preprocessor/_multimodel.py
  tests/sample_data/multimodel_statistics/timeseries_daily_365_day-full-mean.nc
  tests/sample_data/multimodel_statistics/timeseries_daily_365_day-overlap-mean.nc
  tests/sample_data/multimodel_statistics/timeseries_daily_gregorian-full-mean.nc
  tests/sample_data/multimodel_statistics/timeseries_daily_gregorian-overlap-mean.nc
  tests/sample_data/multimodel_statistics/timeseries_daily_proleptic_gregorian-full-mean.nc
  tests/sample_data/multimodel_statistics/timeseries_daily_proleptic_gregorian-overlap-mean.nc
  tests/sample_data/multimodel_statistics/timeseries_monthly-full-mean.nc
  tests/sample_data/multimodel_statistics/timeseries_monthly-overlap-mean.nc
  tests/unit/preprocessor/_multimodel/test_multimodel.py
Labels: preprocessor

#913 xco2 derivation
  esmvalcore/preprocessor/_derive/xco2.py
  tests/unit/preprocessor/_derive/test_xco2.py
Labels: enhancement, variable derivation

#635 New / updated model fixes
  esmvalcore/cmor/_fixes/cmip6/access_cm2.py
  esmvalcore/cmor/_fixes/cmip6/access_esm1_5.py
  esmvalcore/cmor/_fixes/cmip6/cesm2_waccm_fv2.py
  esmvalcore/cmor/_fixes/cmip6/ciesm.py
  tests/integration/cmor/_fixes/cmip6/test_access_cm2.py
  tests/integration/cmor/_fixes/cmip6/test_access_esm1_5.py
  tests/integration/cmor/_fixes/cmip6/test_cesm2_waccm_fv2.py
  tests/integration/cmor/_fixes/cmip6/test_ciesm.py
Labels: fix for dataset

#938 Removed netCDF4 package from integration tests of fixes
  tests/integration/cmor/_fixes/cmip6/test_cesm2.py
  tests/integration/cmor/_fixes/cmip6/test_cesm2_waccm.py
  tests/integration/cmor/_fixes/cmip6/test_cnrm_cm6_1.py
  tests/integration/cmor/_fixes/cmip6/test_gfdl_cm4.py
  tests/integration/cmor/_fixes/cmip6/test_gfdl_esm4.py
  tests/integration/cmor/_fixes/cmip6/test_noresm2_lm.py
  tests/integration/cmor/_fixes/conftest.py
  tests/integration/cmor/_fixes/test_common.py
  tests/integration/cmor/_fixes/test_data/cesm2_cl.nc
  tests/integration/cmor/_fixes/test_data/cesm2_waccm_cl.nc
  tests/integration/cmor/_fixes/test_data/cnrm_cm6_1_cl.nc
  tests/integration/cmor/_fixes/test_data/common_cl_a.nc
  tests/integration/cmor/_fixes/test_data/common_cl_ap.nc
  tests/integration/cmor/_fixes/test_data/common_cl_hybrid_height.nc
  tests/integration/cmor/_fixes/test_data/create_test_data.py
  tests/integration/cmor/_fixes/test_data/gfdl_cm4_cl.nc
Labels: testing

#885 Working environment for Python 3.9 (pin to !=3.9.0)
  .github/workflows/action-conda-publish.yml
  .github/workflows/action-install-from-conda.yml
  .github/workflows/action-install-from-pypi.yml
  .github/workflows/action-install-from-source.yml
  .github/workflows/action-pypi-build-and-deploy.yml
  .github/workflows/action-test.yml
  environment.yml
  package/meta.yaml
  setup.py
  tests/unit/preprocessor/_regrid_esmpy/test_regrid_esmpy.py
Labels: installation

#958 Change in config-user defaults and documentation with new location for esmeval OBS data on JASMIN
  doc/quickstart/find_data.rst
  esmvalcore/config-user.yml
Labels: bear at a dinner party, documentation

#960 Print source file when using config get_config_user command
  esmvalcore/_main.py
Labels: enhancement

#955 Added necessary fixes for recipe schlund20esd
  esmvalcore/cmor/_fixes/cmip6/cas_esm2_0.py
  esmvalcore/cmor/_fixes/cmip6/cesm2_waccm_fv2.py
  esmvalcore/cmor/_fixes/cmip6/cmcc_cm2_sr5.py
  esmvalcore/cmor/_fixes/cmip6/e3sm_1_0.py
  esmvalcore/cmor/_fixes/cmip6/mpi_esm1_2_lr.py
  esmvalcore/cmor/_fixes/cmip6/mpi_esm_1_2_ham.py
  esmvalcore/cmor/_fixes/cmip6/noresm2_mm.py
  esmvalcore/cmor/_fixes/cmip6/taiesm1.py
  tests/integration/cmor/_fixes/cmip6/test_cas_esm2_0.py
  tests/integration/cmor/_fixes/cmip6/test_cesm2_waccm_fv2.py
  tests/integration/cmor/_fixes/cmip6/test_cmcc_cm2_sr5.py
  tests/integration/cmor/_fixes/cmip6/test_e3sm_1_0.py
  tests/integration/cmor/_fixes/cmip6/test_mpi_esm1_2_lr.py
  tests/integration/cmor/_fixes/cmip6/test_mpi_esm_1_2_ham.py
  tests/integration/cmor/_fixes/cmip6/test_noresm2_mm.py
  tests/integration/cmor/_fixes/cmip6/test_taiesm1.py
Labels: fix for dataset

#942 Update Core Team info
  CODE_OF_CONDUCT.md
  NOTICE
  esmvalcore/_main.py
Labels: documentation

#964 Update iris documentation URL for sphinx
  doc/conf.py
Labels: documentation

#808 Deprecate defining write_plots and write_netcdf in config-user file
  doc/quickstart/configure.rst
  doc/quickstart/output.rst
  esmvalcore/_config.py
  esmvalcore/_recipe.py
  esmvalcore/_task.py
  esmvalcore/config-user.yml
  esmvalcore/experimental/config/_config_validators.py
  tests/integration/test_recipe.py
Labels: deprecated feature
