Repository ESMValGroup/ESMValCore, pull requests merged in 2021-11, with the labels that each got.

#1384 Update version number for third release candidate 2.4.0rc3
  CITATION.cff
  esmvalcore/_version.py
  package/meta.yaml
Labels: documentation, release

#1385 Update changelog for 2.4.0rc3
  doc/changelog.rst
Labels: documentation, release

#1386 Adding standard names to the custom tables of the `rlns` and `rsns` variables
  esmvalcore/cmor/tables/custom/CMOR_rlns.dat
  esmvalcore/cmor/tables/custom/CMOR_rsns.dat
Labels: cmor

#1389 Update version number to final 2.4.0 release
  CITATION.cff
  esmvalcore/_version.py
  package/meta.yaml
Labels: documentation, release

#1390 Update changelog for 2.4.0
  doc/changelog.rst
Labels: documentation, release

#1402 add `pandas` as dependency :panda_face:
  environment.yml
  setup.py
Labels: installation, testing
