Repository ESMValGroup/ESMValCore, pull requests merged in 2021-09, with the labels that each got.

#1268 Machine-specific directories for auxiliary data in the `config-user.yml` file
  doc/quickstart/configure.rst
  esmvalcore/config-user.yml
Labels: enhancement

#1276 Remove history attribute from coords
  esmvalcore/preprocessor/_io.py
  tests/integration/preprocessor/_io/test_load.py
Labels: enhancement, cmor

#1302 Speed up tests of tasks
  tests/integration/test_task.py
Labels: testing

#1300 Remove write_netcdf and write_plots from config-user.yml
  doc/api/esmvalcore.api.config.rst
  doc/quickstart/configure.rst
  esmvalcore/_config/_config.py
  esmvalcore/_recipe.py
  esmvalcore/_task.py
  esmvalcore/experimental/config/_config_validators.py
Labels: deprecated feature

#1301 Speed up multimodel statistics and fix bug in peak computation
  esmvalcore/preprocessor/_multimodel.py
  tests/unit/preprocessor/_multimodel/test_multimodel.py
Labels: bug

#1307 No longer make plots of provenance
  doc/interfaces.rst
  doc/requirements.txt
  environment.yml
  esmvalcore/_provenance.py
  package/meta.yaml
  setup.py
  tests/integration/test_recipe.py
Labels: bug, backwards incompatible change

#1305 Update the documentation of the provenance interface
  doc/interfaces.rst
Labels: documentation

#1306 No longer embed provenance in output files
  esmvalcore/_provenance.py
  tests/integration/test_recipe.py
Labels: bug, backwards incompatible change

#1310 Pin esmpy to anything but 8.1.0 since that particular one changes the CPU affinity
  .github/workflows/action-install-from-source.yml
  .github/workflows/action-pypi-build-and-deploy.yml
  environment.yml
  package/meta.yaml
  setup.py
Labels: installation

#1299 Run the multimodel statistics preprocessor last
  doc/api/esmvalcore.preprocessor.rst
  esmvalcore/preprocessor/__init__.py
  tests/integration/test_recipe.py
Labels: preprocessor, backwards incompatible change

#1316 Removed automatic addition of areacello to obs4mips datasets
  esmvalcore/_recipe.py
  tests/integration/test_recipe.py
Labels: bug

#1320 Pin docutils <0.17 to fix bullet lists on readthedocs
  doc/requirements.txt
Labels: bug, documentation

#1032 Increased flexibility of CMOR checks for datasets with generic alevel coordinates
  esmvalcore/cmor/check.py
  tests/unit/cmor/test_cmor_check.py
Labels: enhancement, cmor

#1330 Fix Python 3.7 tests
  .github/workflows/action-install-from-source.yml
  .github/workflows/action-pypi-build-and-deploy.yml
  .github/workflows/action-test-monitor.yml
  .github/workflows/action-test.yml
  tests/integration/esgf/test_search_download.py
Labels: bug, deprecated feature

#1332 Improve results web page
  doc/recipe/overview.rst
  esmvalcore/_recipe.py
  esmvalcore/experimental/recipe_info.py
  esmvalcore/experimental/recipe_output.py
  esmvalcore/experimental/templates/RecipeInfo.j2
  esmvalcore/experimental/templates/RecipeOutput.j2
  esmvalcore/experimental/templates/TaskOutput.j2
  esmvalcore/experimental/templates/head.j2
  esmvalcore/experimental/templates/recipe_output_page.j2
  esmvalcore/recipe_schema.yml
  tests/integration/test_diagnostic_run.py
  tests/integration/test_main.py
  tests/integration/test_recipe.py
  tests/sample_data/experimental/recipe_api_test.yml
  tests/unit/experimental/test_output_file.py
  tests/unit/experimental/test_recipe_info.py
  tests/unit/experimental/test_recipe_output.py
  tests/unit/test_recipe.py
Labels: enhancement, backwards incompatible change
