Repository ESMValGroup/ESMValCore, pull requests merged in 2021-12, with the labels that each got.

#1403 Fix `extract_shape` when fx vars are present
  esmvalcore/preprocessor/_area.py
  tests/unit/preprocessor/_area/test_area.py
Labels: bug, preprocessor

#1399 Added support of `extra_facets` to fx variables added by the preprocessor
  esmvalcore/_recipe.py
  tests/unit/test_recipe.py
Labels: bug

#1406 Added bias preprocessor
  doc/recipe/preprocessor.rst
  esmvalcore/_recipe.py
  esmvalcore/_recipe_checks.py
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_bias.py
  tests/integration/test_recipe_checks.py
  tests/unit/preprocessor/_bias/test_bias.py
Labels: preprocessor

#1409 Documentation on how to use HPC central installations
  doc/quickstart/install.rst
Labels: documentation

#1408 Improve error messages when a preprocessor is failing
  esmvalcore/_provenance.py
  esmvalcore/preprocessor/__init__.py
  tests/unit/preprocessor/test_error_logging.py
Labels: preprocessor

#1410 Fixed tests for python 3.7
  tests/unit/preprocessor/test_error_logging.py
Labels: testing

#1412 Augmented input for derived variables with extra_facets
  esmvalcore/_recipe.py
  tests/integration/test_recipe.py
Labels: bug

#1414 Correctly use masked arrays after `unstructured_nearest` regridding
  esmvalcore/preprocessor/_regrid.py
  tests/integration/preprocessor/_regrid/test_regrid.py
  tests/unit/preprocessor/_regrid/test_regrid.py
Labels: bug, preprocessor

#1133 Allow to load all files, first X years or last X years in an experiment
  doc/conf.py
  doc/recipe/overview.rst
  doc/requirements.txt
  esmvalcore/_data_finder.py
  esmvalcore/_main.py
  esmvalcore/_recipe.py
  esmvalcore/_recipe_checks.py
  esmvalcore/config-developer.yml
  esmvalcore/esgf/_search.py
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_time.py
  package/meta.yaml
  setup.py
  tests/__init__.py
  tests/integration/conftest.py
  tests/integration/data_finder.yml
  tests/integration/test_data_finder.py
  tests/integration/test_main.py
  tests/integration/test_recipe.py
  tests/integration/test_recipe_checks.py
  tests/unit/data_finder/test_get_start_end_year.py
  tests/unit/data_finder/test_select_files.py
  tests/unit/esgf/test_search.py
  tests/unit/preprocessor/_bias/test_bias.py
  tests/unit/preprocessor/_time/test_time.py
  tests/unit/test_recipe.py
Labels: enhancement, ISENES
