Repository ESMValGroup/ESMValCore, pull requests merged in 2021-06, with the labels that each got.

#245 Clip irregular grids
  doc/recipe/preprocessor.rst
  esmvalcore/preprocessor/_area.py
  tests/unit/preprocessor/_area/test_area.py
Labels: preprocessor

#1105 Fixes for the siconc variable of CMIP6 models
  esmvalcore/cmor/_fixes/cmip6/cesm2.py
  esmvalcore/cmor/_fixes/cmip6/cesm2_fv2.py
  esmvalcore/cmor/_fixes/cmip6/cesm2_waccm.py
  esmvalcore/cmor/_fixes/cmip6/cesm2_waccm_fv2.py
  esmvalcore/cmor/_fixes/cmip6/gfdl_cm4.py
  esmvalcore/cmor/_fixes/cmip6/gfdl_esm4.py
  esmvalcore/cmor/_fixes/cmip6/kiost_esm.py
  esmvalcore/cmor/_fixes/common.py
  esmvalcore/cmor/_fixes/shared.py
  tests/integration/cmor/_fixes/cmip6/test_cesm2.py
  tests/integration/cmor/_fixes/cmip6/test_cesm2_fv2.py
  tests/integration/cmor/_fixes/cmip6/test_cesm2_waccm.py
  tests/integration/cmor/_fixes/cmip6/test_cesm2_waccm_fv2.py
  tests/integration/cmor/_fixes/cmip6/test_gfdl_cm4.py
  tests/integration/cmor/_fixes/cmip6/test_gfdl_esm4.py
  tests/integration/cmor/_fixes/cmip6/test_kiost_esm.py
  tests/integration/cmor/_fixes/test_common.py
  tests/integration/cmor/_fixes/test_shared.py
Labels: AR6, fix for dataset

#1155 Add instructions how to use the central installation at DKRZ-Mistral
  doc/quickstart/install.rst
Labels: documentation

#1113 Fix wrong sign for land surface flux
  esmvalcore/cmor/_fixes/cmip6/sam0_unicon.py
  tests/integration/cmor/_fixes/cmip6/test_sam0_unicon.py
Labels: AR6, fix for dataset

#1150 Use native iris functions in multi-model statistics
  esmvalcore/_recipe_checks.py
  esmvalcore/preprocessor/_multimodel.py
  tests/sample_data/multimodel_statistics/test_multimodel.py
  tests/sample_data/multimodel_statistics/timeseries_daily_365_day-full-mean.nc
  tests/sample_data/multimodel_statistics/timeseries_daily_365_day-overlap-mean.nc
  tests/unit/preprocessor/_multimodel/test_multimodel.py
Labels: enhancement, preprocessor

#1116 Fix for pr of EC_EARTH
  esmvalcore/cmor/_fixes/cmip5/ec_earth.py
  tests/integration/cmor/_fixes/cmip5/test_ec_earth.py
Labels: AR6, fix for dataset

#1145 Improve finding date range in filenames (enforces separators)
  .zenodo.json
  CITATION.cff
  doc/contributing.rst
  esmvalcore/_data_finder.py
  tests/unit/data_finder/test_get_start_end_year.py
Labels: bug

#583 Add SYNDA drs for CMIP5 and CMIP6 (closes #582)
  doc/quickstart/find_data.rst
  esmvalcore/config-developer.yml
Labels: enhancement

#1167 Fix failing CircleCI tests
  .circleci/config.yml
  setup.py
Labels: installation, testing

#1124 Add basic support for variable mappings
  .circleci/config.yml
  doc/develop/fixing_data.rst
  doc/quickstart/configure.rst
  doc/quickstart/find_data.rst
  doc/requirements.txt
  esmvalcore/_config/__init__.py
  esmvalcore/_config/_config.py
  esmvalcore/_recipe.py
  esmvalcore/cmor/_fixes/fix.py
  esmvalcore/cmor/fix.py
  esmvalcore/experimental/config/_config_validators.py
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_ancillary_vars.py
  setup.py
  tests/integration/test_recipe.py
  tests/sample_data/experimental/test_run_recipe.py
  tests/sample_data/extra_facets/override/test6-01.yml
  tests/sample_data/extra_facets/override/test6-02.yml
  tests/sample_data/extra_facets/simple/test6-01.yml
  tests/unit/test_config.py
Labels: enhancement

#1169 Fix test failing due to fx files chosen differently on different OS's
  tests/integration/test_recipe.py
Labels: release, testing

#1172 fix lru cache decorator with explicit call to method
  esmvalcore/_config/_config.py
Labels: bug, deployment, testing

#1153 Handle IPSL-CM6
  doc/develop/fixing_data.rst
  doc/develop/index.rst
  doc/quickstart/configure.rst
  doc/quickstart/find_data.rst
  doc/quickstart/index.rst
  esmvalcore/_config/extra_facets/ipslcm-mappings.yml
  esmvalcore/cmor/_fixes/fix.py
  esmvalcore/cmor/_fixes/ipslcm/__init__.py
  esmvalcore/cmor/_fixes/ipslcm/ipsl_cm6.py
  esmvalcore/config-developer.yml
  esmvalcore/config-user.yml
  esmvalcore/preprocessor/_io.py
  tests/integration/cmor/_fixes/ipslcm/test_ipsl_cm6.py
Labels: enhancement

#1173 Compare datetimes instead of strings in _fixes/cmip5/test_access1_X.py
  tests/integration/cmor/_fixes/cmip5/test_access1_0.py
  tests/integration/cmor/_fixes/cmip5/test_access1_3.py
Labels: deployment, release, testing

#1176 Pin Python to 3.9 in environment.yml on CircleCI and skip mypy tests in conda build
  .circleci/config.yml
  environment.yml
  package/meta.yaml
Labels: installation, testing

#1162 Set version to 2.3.0
  CITATION.cff
  doc/contributing.rst
  esmvalcore/_version.py
  package/meta.yaml
Labels: documentation, release

#1163 Final changelog for 2.3.0
  doc/changelog.rst
Labels: documentation

#1178 Set circular attribute in MCM-UA-1-0 fix
  esmvalcore/cmor/_fixes/cmip6/mcm_ua_1_0.py
  tests/integration/cmor/_fixes/cmip6/test_mcm_ua_1_0.py
Labels: fix for dataset

#1184 update config-user.yml template with correct drs entries for CEDA-JASMIN
  esmvalcore/config-user.yml
Labels: bug, documentation, installation

#514 Improving test coverage for _task.py
  tests/integration/test_task.py
  tests/unit/task/test_diagnostic_task.py
Labels: enhancement, testing

#1151 Crop on the ID-selected region(s) and not on the whole shapefile
  esmvalcore/preprocessor/_area.py
  tests/unit/preprocessor/_area/test_area.py
Labels: bug

#1195 Improve codecov status checks
  codecov.yml
Labels: testing

#1194 Implemented fully lazy climate_statistics
  esmvalcore/preprocessor/_time.py
  tests/unit/preprocessor/_time/test_time.py
Labels: preprocessor

#1188 Fixed time coordinate of MIRCO-ESM
  esmvalcore/cmor/_fixes/cmip5/miroc_esm.py
  tests/integration/cmor/_fixes/cmip5/test_miroc_esm.py
Labels: fix for dataset
