Repository ESMValGroup/ESMValCore, pull requests merged in 2022-07, with the labels that each got.

#1650 Improve esmvalcore.esgf unit test
  tests/unit/esgf/test_search.py
Labels: testing

#1647 Update documentation on ESMValTool module at DKRZ
  doc/quickstart/install.rst
Labels: documentation

#1658 Expanded information on deprecations in changelog
  doc/changelog.rst
Labels: documentation, release

#1659 Pin cf-units to lower than 3.1.0 to temporarily avoid changes within new version related to calendars
  environment.yml
  setup.py
Labels: installation, testing

#1661 update conda lock file manually - test failed due to cf-units issue which is now fixed
  conda-linux-64.lock
Labels: condalock

#1662 Add changelog for rc4
  CITATION.cff
  doc/changelog.rst
Labels: release

#1666 Set final version of ESMValCore for 2.6
  CITATION.cff
  doc/changelog.rst
Labels: release

#1670 Add support for regions stored as MultiPolygon to extract_shape preprocessor
  esmvalcore/preprocessor/_area.py
Labels: bug
