Repository ESMValGroup/ESMValCore, pull requests merged in 2022-12, with the labels that each got.

#1821 Update pre-commit configuration
  .pre-commit-config.yaml
Labels: testing

#1839 Fix LWP of ICON on-the-fly CMORizer
  esmvalcore/cmor/_fixes/icon/icon.py
  esmvalcore/config/extra_facets/icon-mappings.yml
  tests/integration/cmor/_fixes/icon/test_icon.py
  tests/integration/test_recipe.py
Labels: bug

#1838 Update CEDA ESGF index node hostname
  doc/quickstart/configure.rst
  esmvalcore/config/_esgf_pyclient.py
  tests/integration/esgf/search_results/Amon_r1i1p1_historical,rcp85_INM-CM4_CMIP5_tas.json
  tests/integration/esgf/search_results/Amon_r1i1p1_historical_FIO-ESM_CMIP5_tas.json
  tests/integration/esgf/search_results/Amon_r1i1p1_rcp85_HadGEM2-CC_CMIP5_tas.json
  tests/unit/config/test_esgf_pyclient.py
Labels: documentation, testing

#1845 Fixed issue in irregular regridding regarding scalar coordinates
  esmvalcore/preprocessor/_regrid_esmpy.py
Labels: bug

#1822 Support searching ESGF for a specific version of a file
  esmvalcore/esgf/_download.py
  esmvalcore/esgf/_search.py
  esmvalcore/esgf/facets.py
  tests/integration/esgf/test_search_download.py
  tests/integration/test_recipe_checks.py
  tests/unit/esgf/test_download.py
  tests/unit/esgf/test_search.py
  tests/unit/test_recipe.py
Labels: enhancement, api

#1850 Extension of ERA5 CMORizer (variable cl)
  doc/quickstart/find_data.rst
  esmvalcore/cmor/_fixes/native6/era5.py
  tests/integration/cmor/_fixes/native6/test_era5.py
Labels: fix for dataset, observations

#1854 Set the version number on the development branches to one minor version more than the previous release
  pyproject.toml
Labels: installation, release

#1856 [v2.7.1 bugfix release] fix esgf search as from PR 1834 and include change for v2.7.1 bugfix release
  esmvalcore/esgf/_search.py
  setup.py
Labels: release

#1857 [v2.7.1 bugfix release] remove unnecessary test in regrid to allow install of iris 3.4 - feature from PR 1846
  tests/integration/preprocessor/_regrid/test_regrid.py
Labels: release

#1829 Fix siconc in KIOST-ESM
  esmvalcore/cmor/_fixes/cmip6/kiost_esm.py
  tests/integration/cmor/_fixes/cmip6/test_kiost_esm.py
Labels: fix for dataset, cmor, data issue

#1855 [v2.7.1 bugfix release] Unpin cf-units and port changes from PR 1770 into v2.7.x
  environment.yml
  esmvalcore/cmor/check.py
  esmvalcore/preprocessor/_multimodel.py
  setup.py
  tests/integration/cmor/_fixes/cmip5/test_access1_0.py
  tests/integration/cmor/_fixes/cmip5/test_access1_3.py
  tests/integration/cmor/_fixes/cmip5/test_fgoals_g2.py
  tests/sample_data/multimodel_statistics/test_multimodel.py
  tests/sample_data/multimodel_statistics/timeseries_daily_standard-full-mean.nc
  tests/sample_data/multimodel_statistics/timeseries_daily_standard-overlap-mean.nc
  tests/unit/preprocessor/_multimodel/test_multimodel.py
Labels: release

#1860 [v2.7.1 bugfix release] Add sematic versioning: set the version number on the development branches to one minor version more than the previous release
  pyproject.toml
Labels: release

#1864 [v2.7.1 bugfix release] Update CEDA ESGF index node hostname ported to v2.7.1
  doc/quickstart/configure.rst
  esmvalcore/_config/_esgf_pyclient.py
  tests/integration/esgf/search_results/Amon_r1i1p1_historical,rcp85_INM-CM4_CMIP5_tas.json
  tests/integration/esgf/search_results/Amon_r1i1p1_historical_FIO-ESM_CMIP5_tas.json
  tests/integration/esgf/search_results/Amon_r1i1p1_rcp85_HadGEM2-CC_CMIP5_tas.json
  tests/unit/config/test_esgf_pyclient.py
Labels: release

#1858 [v2.7.1 bugfix release] Finalize v2.7.1 bugfix: add changelog for v2.7.1 bugfix release
  doc/changelog.rst
Labels: release

#1835 Add `esmvalcore.local`, a module to search data on the local filesystem
  doc/api/esmvalcore.local.rst
  doc/api/esmvalcore.rst
  doc/api/esmvalcore.typing.rst
  doc/develop/fixing_data.rst
  doc/quickstart/configure.rst
  doc/quickstart/find_data.rst
  esmvalcore/_provenance.py
  esmvalcore/_recipe.py
  esmvalcore/_recipe_checks.py
  esmvalcore/cmor/_fixes/ipslcm/ipsl_cm6.py
  esmvalcore/config-developer.yml
  esmvalcore/config/_config.py
  esmvalcore/esgf/_download.py
  esmvalcore/esgf/_search.py
  esmvalcore/local.py
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_ancillary_vars.py
  esmvalcore/preprocessor/_io.py
  esmvalcore/preprocessor/_regrid.py
  esmvalcore/typing.py
  tests/integration/conftest.py
  tests/integration/data_finder.yml
  tests/integration/test_data_finder.py
  tests/integration/test_local.py
  tests/integration/test_provenance.py
  tests/integration/test_recipe.py
  tests/integration/test_recipe_checks.py
  tests/sample_data/experimental/test_run_recipe.py
  tests/unit/local/__init__.py
  tests/unit/local/test_facets.py
  tests/unit/local/test_replace_tags.py
  tests/unit/local/test_select_files.py
  tests/unit/local/test_time.py
  tests/unit/test_data_finder.py
  tests/unit/test_recipe.py
Labels: enhancement, api

#1853 Add standard variable names for EMAC
  esmvalcore/cmor/_fixes/emac/emac.py
Labels: bug, fix for dataset, EMAC

#1871 Pin esmpy<8.4
  environment.yml
  setup.py
Labels: installation

#1765 Fix rotated coordinate grids and `tas` and `pr` for CORDEX datasets
  environment.yml
  esmvalcore/cmor/_fixes/cordex/__init__ .py
  esmvalcore/cmor/_fixes/cordex/cnrm_cerfacs_cnrm_cm5/__init__.py
  esmvalcore/cmor/_fixes/cordex/cnrm_cerfacs_cnrm_cm5/cnrm_aladin63.py
  esmvalcore/cmor/_fixes/cordex/cnrm_cerfacs_cnrm_cm5/mohc_hadrem3_ga7_05.py
  esmvalcore/cmor/_fixes/cordex/cordex_fixes.py
  esmvalcore/cmor/_fixes/cordex/ichec_ec_earth/__init__.py
  esmvalcore/cmor/_fixes/cordex/ichec_ec_earth/clmcom_cclm4_8_17.py
  esmvalcore/cmor/_fixes/cordex/ichec_ec_earth/gerics_remo2015.py
  esmvalcore/cmor/_fixes/cordex/ichec_ec_earth/knmi_racmo22e.py
  esmvalcore/cmor/_fixes/cordex/ichec_ec_earth/mohc_hadrem3_ga7_05.py
  esmvalcore/cmor/_fixes/cordex/ichec_ec_earth/smhi_rca4.py
  esmvalcore/cmor/_fixes/cordex/miroc_miroc5/__init__.py
  esmvalcore/cmor/_fixes/cordex/miroc_miroc5/clmcom_cclm4_8_17.py
  esmvalcore/cmor/_fixes/cordex/miroc_miroc5/gerics_remo2015.py
  esmvalcore/cmor/_fixes/cordex/miroc_miroc5/uhoh_wrf361h.py
  esmvalcore/cmor/_fixes/cordex/mohc_hadgem2_es/__init__.py
  esmvalcore/cmor/_fixes/cordex/mohc_hadgem2_es/dmi_hirham5.py
  esmvalcore/cmor/_fixes/cordex/mohc_hadgem2_es/gerics_remo2015.py
  esmvalcore/cmor/_fixes/cordex/mohc_hadgem2_es/mohc_hadrem3_ga7_05.py
  esmvalcore/cmor/_fixes/cordex/mohc_hadgem2_es/smhi_rca4.py
  esmvalcore/cmor/_fixes/cordex/mpi_m_mpi_esm_lr/__init__.py
  esmvalcore/cmor/_fixes/cordex/mpi_m_mpi_esm_lr/ictp_regcm4_6.py
  esmvalcore/cmor/_fixes/cordex/mpi_m_mpi_esm_lr/knmi_racmo22e.py
  esmvalcore/cmor/_fixes/cordex/mpi_m_mpi_esm_lr/mohc_hadrem3_ga7_05.py
  esmvalcore/cmor/_fixes/cordex/ncc_noresm1_m/__init__.py
  esmvalcore/cmor/_fixes/cordex/ncc_noresm1_m/gerics_remo2015.py
  esmvalcore/cmor/_fixes/cordex/ncc_noresm1_m/knmi_racmo22e.py
  esmvalcore/cmor/_fixes/cordex/ncc_noresm1_m/mohc_hadrem3_ga7_05.py
  esmvalcore/cmor/_fixes/cordex/ncc_noresm1_m/smhi_rca4.py
  esmvalcore/cmor/_fixes/fix.py
  esmvalcore/cmor/check.py
  setup.py
  tests/integration/cmor/_fixes/cordex/__init__.py
  tests/integration/cmor/_fixes/cordex/test_cnrm_cerfacs_cnrm_cm5.py
  tests/integration/cmor/_fixes/cordex/test_cordex_fixes.py
  tests/integration/cmor/_fixes/cordex/test_ichec_ec_earth.py
  tests/integration/cmor/_fixes/cordex/test_miroc_miroc5.py
  tests/integration/cmor/_fixes/cordex/test_mohc_hadgem2_es.py
  tests/integration/cmor/_fixes/cordex/test_mpi_m_mpi_esm_lr.py
  tests/integration/cmor/_fixes/cordex/test_ncc_noresm1_m.py
  tests/integration/cmor/_fixes/test_fix.py
  tests/unit/cmor/test_cmor_check.py
Labels: fix for dataset, cmor
