Repository ESMValGroup/ESMValCore, pull requests merged in 2022-09, with the labels that each got.

#1715 Core `_io.concatenate()` may fail due to case when one of the cubes is scalar - this fixes that
  esmvalcore/preprocessor/_io.py
  tests/integration/preprocessor/_io/test_concatenate.py
Labels: bug

#1709 add MO-paths to config file
  esmvalcore/config-user.yml
Labels: documentation, AutoAssess

#1718 Added tests for input/output filenames for ICON and EMAC on-the-fly CMORizer
  esmvalcore/_config/extra_facets/ipslcm-mappings.yml
  esmvalcore/config-developer.yml
  tests/integration/data_finder.yml
  tests/integration/test_data_finder.py
Labels: testing

#1724 Pin `netCDF4 != 1.6.1` since that seems to throw a flurry of Segmentation Faults
  environment.yml
  setup.py
Labels: installation, testing, bear at a dinner party

#1722 Remove `pytest_flake8` plugin and use `flake8` instead
  .circleci/config.yml
  .github/workflows/create-condalock-file.yml
  .github/workflows/install-from-condalock-file.yml
  .github/workflows/run-tests-comment.yml
  .github/workflows/run-tests.yml
  setup.cfg
  setup.py
Labels: enhancement, installation, testing
