Repository ESMValGroup/ESMValCore, pull requests merged in 2022-01, with the labels that each got.

#1419 remove accessing `.xml()` cube method from test
  tests/integration/cmor/_fixes/native6/test_era5.py
Labels: testing

#1420 Correct brackets in preprocessor documentation for list of seasons
  doc/recipe/preprocessor.rst
Labels: documentation

#1357 remove flag to use pip 2020 solver from Github Action pip install command on OSX
  .github/workflows/install-from-source.yml
  .github/workflows/run-tests-monitor.yml
  .github/workflows/run-tests.yml
Labels: testing

#1432 Add Python=3.10 to package info, update Circle CI auto install and documentation for Python=3.10
  .circleci/config.yml
  doc/quickstart/install.rst
  setup.py
Labels: documentation, enhancement, installation, testing, deployment

#1430 Add Python=3.10 to Github Actions and switch to Python=3.10 for the Github Action that builds the PyPi package
  .github/workflows/build-and-deploy-on-pypi.yml
  .github/workflows/install-from-conda.yml
  .github/workflows/install-from-pypi.yml
  .github/workflows/install-from-source.yml
  .github/workflows/run-tests-monitor.yml
  .github/workflows/run-tests.yml
Labels: testing

#1264 Filter tasks earlier
  esmvalcore/_recipe.py
  tests/integration/test_recipe.py
  tests/unit/test_recipe.py
Labels: enhancement

#1428 Fixing the broken derivation script for XCH4 (and XCO2)
  esmvalcore/preprocessor/_derive/_shared.py
Labels: bug, iris, preprocessor, variable derivation

#1251 Add `extract_location` preprocessor to extract town, city, mountains etc - anything specifiable by a location
  doc/recipe/preprocessor.rst
  doc/requirements.txt
  environment.yml
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_regrid.py
  package/meta.yaml
  setup.py
  tests/integration/preprocessor/_regrid/test_extract_location.py
Labels: enhancement, preprocessor

#1435 Added earlier validation for command line arguments
  esmvalcore/_main.py
  esmvalcore/_recipe.py
  esmvalcore/experimental/config/_config_validators.py
  esmvalcore/preprocessor/_derive/__init__.py
  tests/unit/main/test_esmvaltool.py
  tests/unit/test_recipe.py
Labels: enhancement

#1429 Renamed vertical regridding schemes
  doc/recipe/preprocessor.rst
  esmvalcore/preprocessor/_regrid.py
  tests/integration/preprocessor/_regrid/test_extract_levels.py
  tests/unit/preprocessor/_regrid/test_extract_levels.py
Labels: preprocessor, deprecated feature

#1434 Pin `flake8<4` to keep getting relevant error traces when tests fail with FLAKE8 issues
  package/meta.yaml
  setup.py
Labels: enhancement, testing

#1442 Fixed bug that caused automatic download to fail in rare cases
  esmvalcore/config-user.yml
  esmvalcore/esgf/_download.py
  tests/unit/esgf/test_download.py
Labels: bug
