Repository ESMValGroup/ESMValCore, pull requests merged in 2022-10, with the labels that each got.

#1689 Update `Making a release` section of the documentation
  doc/contributing.rst
Labels: documentation

#1678 Added CESM2 CMORizer
  doc/develop/fixing_data.rst
  doc/quickstart/configure.rst
  doc/quickstart/find_data.rst
  esmvalcore/_config/extra_facets/cesm-mappings.yml
  esmvalcore/_config/extra_facets/emac-mappings.yml
  esmvalcore/_config/extra_facets/icon-mappings.yml
  esmvalcore/_config/extra_facets/ipslcm-mappings.yml
  esmvalcore/cmor/_fixes/cesm/__init__.py
  esmvalcore/cmor/_fixes/cesm/cesm2.py
  esmvalcore/config-developer.yml
  tests/integration/cmor/_fixes/cesm/__init__.py
  tests/integration/cmor/_fixes/cesm/test_cesm2.py
  tests/integration/cmor/_fixes/test_data/cesm2_native.nc
  tests/integration/data_finder.yml
Labels: enhancement

#1749 pick up esmvalcore badge instead of esmvaltool one in README
  README.md
Labels: bug, documentation

#1726 Modernize and minimize pylint configuration
  .pylintrc
  pyproject.toml
Labels: enhancement

#1753 Remove deprecation warning for regrid schemes already deprecated for v2.7.0
  doc/recipe/preprocessor.rst
  esmvalcore/preprocessor/_regrid.py
  tests/unit/preprocessor/_regrid/test_extract_levels.py
Labels: deprecated feature, release

#1746 added changelog for v2.7.0
  doc/changelog.rst
Labels: documentation

#1755 Fix calculation of precipitation flux in EMAC on-the-fly CMORizer
  esmvalcore/_config/extra_facets/emac-mappings.yml
  esmvalcore/cmor/_fixes/emac/emac.py
  tests/integration/cmor/_fixes/emac/test_emac.py
Labels: bug

#1757 update CITATION.cff file with 2.7.0 release info
  CITATION.cff
Labels: documentation

#1759 fix anaconda badge in README
  README.md
Labels: documentation
