Repository ESMValGroup/ESMValCore, pull requests merged in 2022-11, with the labels that each got.

#1695 Add derivation of sea ice extent
  esmvalcore/cmor/tables/custom/CMOR_siextent.dat
  esmvalcore/preprocessor/_derive/siextent.py
  tests/unit/preprocessor/_derive/test_siextent.py
Labels: variable derivation

#1784 Fix mistake in the documentation of `esmvalcore.esgf.find_files`
  esmvalcore/esgf/_download.py
  esmvalcore/esgf/_search.py
Labels: documentation

#1790 set implicit optional to true in mypy config to avert side effects and test fails from new mypy version
  esmvalcore/_task.py
  setup.cfg
Labels: testing

#1791 remove duplicate implicit_optional = True line in setup.cfg
  setup.cfg
Labels: bug

#1797 Fix failing test due to missing sample data
  tests/sample_data/experimental/test_run_recipe.py
Labels: testing

#1608 Support linking to "stable" ESMValTool version on readthedocs
  doc/conf.py
Labels: documentation

#1798 Remove outdated cmor_table facet from data finder tests
  setup.cfg
  tests/integration/data_finder.yml
Labels: testing

#1805 Pin netCDF4<1.6.1
  environment.yml
  setup.py
Labels: installation

#1770 Unpin cf-units
  environment.yml
  esmvalcore/cmor/check.py
  esmvalcore/preprocessor/_multimodel.py
  setup.py
  tests/integration/cmor/_fixes/cmip5/test_access1_0.py
  tests/integration/cmor/_fixes/cmip5/test_access1_3.py
  tests/integration/cmor/_fixes/cmip5/test_fgoals_g2.py
  tests/sample_data/multimodel_statistics/test_multimodel.py
  tests/sample_data/multimodel_statistics/timeseries_daily_standard-full-mean.nc
  tests/sample_data/multimodel_statistics/timeseries_daily_standard-overlap-mean.nc
  tests/unit/preprocessor/_multimodel/test_multimodel.py
Labels: installation

#1814 Unpin NetCF4
  environment.yml
  setup.py
Labels: installation, testing

#1818 Create a session directory with suffix "-1", "-2", etc if it already exists
  esmvalcore/_main.py
  tests/unit/main/test_esmvaltool.py
Labels: enhancement

#1820 Unpin flake8
  environment.yml
  setup.py
Labels: installation, testing

#1811 Added scalar coords of input cubes to output of esmpy_regrid
  esmvalcore/preprocessor/_regrid.py
  esmvalcore/preprocessor/_regrid_esmpy.py
  tests/unit/preprocessor/_regrid_esmpy/test_regrid_esmpy.py
Labels: bug

#1809 Add iris-esmf-regrid as a dependency
  doc/recipe/preprocessor.rst
  environment.yml
  esmvalcore/preprocessor/_regrid.py
  setup.py
  tests/integration/preprocessor/_regrid/test_regrid.py
  tests/unit/preprocessor/_regrid/test_regrid.py
Labels: installation, preprocessor

#1819 No more sequential tests since SegFaults were not noticed anymore (knock on wood)
  .circleci/config.yml
  .github/workflows/create-condalock-file.yml
  .github/workflows/install-from-condalock-file.yml
  .github/workflows/run-tests-comment.yml
  .github/workflows/run-tests-monitor.yml
  .github/workflows/run-tests.yml
  setup.cfg
  tests/integration/cmor/_fixes/test_common.py
  tests/integration/cmor/_fixes/test_shared.py
Labels: testing

#1823 Fix severe bug in `mask_fillvalues`
  esmvalcore/preprocessor/_mask.py
  tests/integration/preprocessor/_mask/test_mask.py
Labels: bug

#1826 Remove deprecated features scheduled for removal in v2.8.0 or earlier
  esmvalcore/iris_helpers.py
  esmvalcore/preprocessor/_mask.py
  tests/integration/preprocessor/_mask/test_mask.py
  tests/integration/test_recipe.py
  tests/unit/test_iris_helpers.py
Labels: deprecated feature, backwards incompatible change

#1808 Allow `multi_model_statistics` on cubes with arbitrary dimensions
  doc/recipe/preprocessor.rst
  esmvalcore/preprocessor/_multimodel.py
  tests/sample_data/multimodel_statistics/test_multimodel.py
  tests/unit/preprocessor/_multimodel/test_multimodel.py
Labels: enhancement, preprocessor

#1834 Improve error handling if an esgf index node is offline
  esmvalcore/esgf/_search.py
Labels: bug
