Repository ESMValGroup/ESMValCore, pull requests merged in 2022-08, with the labels that each got.

#1692 Add Met Office Installation Method
  doc/quickstart/install.rst
Labels: documentation

#1698 pin `flake8<5.0.0` since Circle CI tests are failing copiously
  setup.py
Labels: testing

#1694 Refactored native model fixes by adding common base class `NativeDatasetFix`
  doc/develop/fixing_data.rst
  esmvalcore/cmor/_fixes/emac/_base_fixes.py
  esmvalcore/cmor/_fixes/emac/emac.py
  esmvalcore/cmor/_fixes/icon/_base_fixes.py
  esmvalcore/cmor/_fixes/icon/icon.py
  esmvalcore/cmor/_fixes/native_datasets.py
  tests/integration/cmor/_fixes/emac/test_emac.py
  tests/integration/cmor/_fixes/icon/test_icon.py
  tests/integration/cmor/_fixes/test_native_datasets.py
Labels: fix for dataset

#1700 Fixed type annotations for Python 3.8
  esmvalcore/cmor/_fixes/native_datasets.py
Labels: bug

#1705 Change default DRS for reading native ICON output
  doc/quickstart/find_data.rst
  esmvalcore/_config/extra_facets/icon-mappings.yml
  esmvalcore/cmor/_fixes/icon/_base_fixes.py
  esmvalcore/cmor/_fixes/icon/icon.py
  esmvalcore/config-developer.yml
  tests/integration/test_recipe.py
Labels: backwards incompatible change

#1702 New preprocessor function 'rolling_window_statistics'
  doc/recipe/preprocessor.rst
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_rolling_window.py
  tests/unit/preprocessor/_rolling_window/__init__.py
  tests/unit/preprocessor/_rolling_window/test_rolling_window.py
Labels: enhancement, preprocessor
