Repository ESMValGroup/ESMValCore, pull requests merged in 2022-04, with the labels that each got.

#1553 [Github Actions Docs] Full explanation on how to use the GA test triggered by PR comment and added docs link for GA hosted runners
  doc/contributing.rst
Labels: documentation

#1558 Add support for DKRZ-Levante
  esmvalcore/config-user.yml
Labels: documentation

#1559 Improved documentation on native dataset support
  doc/develop/fixing_data.rst
  doc/quickstart/configure.rst
  doc/quickstart/find_data.rst
Labels: documentation

#1564 Removed trailing whitespace in custom CMOR tables
  esmvalcore/cmor/tables/custom/CMOR_alb.dat
  esmvalcore/cmor/tables/custom/CMOR_albDiff.dat
  esmvalcore/cmor/tables/custom/CMOR_albDiffiTr13.dat
  esmvalcore/cmor/tables/custom/CMOR_amoc.dat
  esmvalcore/cmor/tables/custom/CMOR_bdalb.dat
  esmvalcore/cmor/tables/custom/CMOR_bhalb.dat
  esmvalcore/cmor/tables/custom/CMOR_clhmtisccp.dat
  esmvalcore/cmor/tables/custom/CMOR_clhtkisccp.dat
  esmvalcore/cmor/tables/custom/CMOR_clisccp.dat
  esmvalcore/cmor/tables/custom/CMOR_cllmtisccp.dat
  esmvalcore/cmor/tables/custom/CMOR_clltkisccp.dat
  esmvalcore/cmor/tables/custom/CMOR_clmmtisccp.dat
  esmvalcore/cmor/tables/custom/CMOR_clmtkisccp.dat
  esmvalcore/cmor/tables/custom/CMOR_cltStderr.dat
  esmvalcore/cmor/tables/custom/CMOR_dos.dat
  esmvalcore/cmor/tables/custom/CMOR_dosStderr.dat
  esmvalcore/cmor/tables/custom/CMOR_fapar.dat
  esmvalcore/cmor/tables/custom/CMOR_husStderr.dat
  esmvalcore/cmor/tables/custom/CMOR_iwpStderr.dat
  esmvalcore/cmor/tables/custom/CMOR_lvp.dat
  esmvalcore/cmor/tables/custom/CMOR_lwcre.dat
  esmvalcore/cmor/tables/custom/CMOR_lwp.dat
  esmvalcore/cmor/tables/custom/CMOR_lwpStderr.dat
  esmvalcore/cmor/tables/custom/CMOR_netcre.dat
  esmvalcore/cmor/tables/custom/CMOR_od550aerStderr.dat
  esmvalcore/cmor/tables/custom/CMOR_od870aerStderr.dat
  esmvalcore/cmor/tables/custom/CMOR_prStderr.dat
  esmvalcore/cmor/tables/custom/CMOR_rlnst.dat
  esmvalcore/cmor/tables/custom/CMOR_rlnstcs.dat
  esmvalcore/cmor/tables/custom/CMOR_rluscs.dat
  esmvalcore/cmor/tables/custom/CMOR_rsnst.dat
  esmvalcore/cmor/tables/custom/CMOR_rsnstcs.dat
  esmvalcore/cmor/tables/custom/CMOR_rsnt.dat
  esmvalcore/cmor/tables/custom/CMOR_rtnt.dat
  esmvalcore/cmor/tables/custom/CMOR_sm.dat
  esmvalcore/cmor/tables/custom/CMOR_smStderr.dat
  esmvalcore/cmor/tables/custom/CMOR_swcre.dat
  esmvalcore/cmor/tables/custom/CMOR_tasConf5.dat
  esmvalcore/cmor/tables/custom/CMOR_tasConf95.dat
  esmvalcore/cmor/tables/custom/CMOR_tasa.dat
  esmvalcore/cmor/tables/custom/CMOR_tasaga.dat
  esmvalcore/cmor/tables/custom/CMOR_toz.dat
  esmvalcore/cmor/tables/custom/CMOR_tozStderr.dat
  esmvalcore/cmor/tables/custom/CMOR_tro3prof.dat
  esmvalcore/cmor/tables/custom/CMOR_tro3profStderr.dat
  esmvalcore/cmor/tables/custom/CMOR_tsStderr.dat
  esmvalcore/cmor/tables/custom/CMOR_xch4.dat
  esmvalcore/cmor/tables/custom/CMOR_xco2.dat
Labels: enhancement

#1561 Try searching multiple ESGF index nodes
  doc/quickstart/configure.rst
  esmvalcore/_config/_esgf_pyclient.py
  esmvalcore/esgf/_logon.py
  esmvalcore/esgf/_search.py
  esmvalcore/esgf/facets.py
  tests/integration/esgf/test_search_download.py
  tests/unit/config/test_esgf_pyclient.py
  tests/unit/esgf/test_facet.py
  tests/unit/esgf/test_logon.py
  tests/unit/esgf/test_search.py
Labels: enhancement

#1560 Show all results on recipe results webpage
  esmvalcore/_recipe.py
  tests/sample_data/experimental/test_run_recipe.py
Labels: bug

#1566 Fixes of ocean variables in multiple CMIP6 datasets
  esmvalcore/cmor/_fixes/cmip6/bcc_csm2_mr.py
  esmvalcore/cmor/_fixes/cmip6/cesm2_fv2.py
  esmvalcore/cmor/_fixes/cmip6/cesm2_waccm.py
  esmvalcore/cmor/_fixes/cmip6/cesm2_waccm_fv2.py
  esmvalcore/cmor/_fixes/cmip6/cnrm_cm6_1.py
  esmvalcore/cmor/_fixes/cmip6/cnrm_esm2_1.py
  esmvalcore/cmor/_fixes/cmip6/fgoals_f3_l.py
  esmvalcore/cmor/_fixes/cmip6/gfdl_cm4.py
  esmvalcore/cmor/_fixes/cmip6/gfdl_esm4.py
  esmvalcore/cmor/_fixes/cmip6/ipsl_cm5a2_inca.py
  esmvalcore/cmor/_fixes/cmip6/ipsl_cm6a_lr_inca.py
  tests/integration/cmor/_fixes/cmip6/test_cesm2_fv2.py
  tests/integration/cmor/_fixes/cmip6/test_cesm2_waccm.py
  tests/integration/cmor/_fixes/cmip6/test_cesm2_waccm_fv2.py
  tests/integration/cmor/_fixes/cmip6/test_cnrm_cm6_1.py
  tests/integration/cmor/_fixes/cmip6/test_gfdl_cm4.py
Labels: fix for dataset
