Repository ESMValGroup/ESMValCore, pull requests merged in 2022-03, with the labels that each got.

#1510 [Tests fail `iris>=3.2.0`] Add a test module that runs tests of `iris` I/O everytime we notice serious bugs there
  .github/workflows/run-tests.yml
  tests/unit/test_iris_io.py
Labels: testing

#1514 Add `output2` to the `product` extra facet of CMIP5 data
  esmvalcore/_config/extra_facets/cmip5-product.yml
  tests/integration/test_recipe.py
  tests/unit/config/test_config.py
Labels: enhancement

#1512 Speed up ESGF search
  esmvalcore/esgf/_search.py
  package/meta.yaml
  setup.py
  tests/unit/esgf/test_search.py
Labels: enhancement

#1517 Fixed timerange selection for automatic downloads
  esmvalcore/_data_finder.py
  esmvalcore/_recipe.py
  esmvalcore/esgf/_search.py
  tests/integration/test_recipe.py
  tests/unit/test_data_finder.py
Labels: bug

#1519 Increased ESMValCore version to 2.5.0rc4
  CITATION.cff
  doc/changelog.rst
  esmvalcore/_version.py
  package/meta.yaml
Labels: documentation, release

#1524 Fixed chunking in `multi_model_statistics`
  esmvalcore/preprocessor/_multimodel.py
  tests/unit/preprocessor/_multimodel/test_multimodel.py
Labels: bug

#1525 Pinned iris<3.2.0
  environment.yml
  package/meta.yaml
  setup.py
Labels: installation, iris

#1526 add Github Actions Test badge in README
  README.md
Labels: documentation

#1520 [Github Actions] Trigger Github Actions tests (`run-tests.yml` workflow) from a comment in a PR
  .github/workflows/run-tests-comment.yml
  doc/contributing.rst
Labels: testing

#1448 Generic regridding preprocessor
  doc/conf.py
  doc/recipe/preprocessor.rst
  esmvalcore/preprocessor/_regrid.py
  tests/unit/preprocessor/_regrid/test_regrid.py
Labels: enhancement, preprocessor

#1529 Increased ESMValCore version to 2.5.0rc5
  CITATION.cff
  doc/changelog.rst
  esmvalcore/_version.py
  package/meta.yaml
Labels: documentation, release

#1530 Dropped Python 3.7
  .github/workflows/install-from-conda.yml
  .github/workflows/install-from-condalock-file.yml
  .github/workflows/install-from-pypi.yml
  .github/workflows/install-from-source.yml
  .github/workflows/run-tests-comment.yml
  .github/workflows/run-tests-monitor.yml
  .github/workflows/run-tests.yml
  doc/recipe/preprocessor.rst
  environment.yml
  package/meta.yaml
  setup.py
Labels: installation, release

#1532 Increased ESMValCore version to 2.5.0rc6
  CITATION.cff
  doc/changelog.rst
  esmvalcore/_version.py
  package/meta.yaml
Labels: documentation, release

#1534 Increased ESMValCore version to 2.5.0
  CITATION.cff
  doc/changelog.rst
  esmvalcore/_version.py
  package/meta.yaml
Labels: documentation, release

#1547 Added `start_year` and `end_year` attributes to derived variables
  esmvalcore/_recipe.py
  tests/integration/test_recipe.py
Labels: bug

#1540 Removed `package/meta.yml`
  doc/contributing.rst
  package/meta.yaml
  tests/unit/documentation/__init__.py
Labels: installation

#1552 Pinned iris>=3.2.1
  doc/contributing.rst
  environment.yml
  setup.py
Labels: installation, iris
