Repository ESMValGroup/ESMValCore, pull requests merged in 2022-02, with the labels that each got.

#1444 Add new `JULIA_LOAD_PATH` to diagnostic task test
  tests/unit/task/test_diagnostic_task.py
Labels: bug, testing

#1452 Reverted unintentional change in `.zenodo.json`
  .zenodo.json
Labels: documentation

#1453 Synchronized config-user.yml with version from ESMValTool
  esmvalcore/config-user.yml
  tests/unit/config/test_config.py
Labels: documentation

#1303 Update Cordex section in `config-developer.yml `
  esmvalcore/config-developer.yml
  tests/integration/test_recipe.py
Labels: ISENES, backwards incompatible change

#1441 Relocate `pytest-monitor` outputted database `.pymon` so `.pymon-journal` file should not be looked for by `pytest`
  .github/workflows/run-tests-monitor.yml
  tests/parse_pymon.py
  tests/unit/task/test_diagnostic_task.py
Labels: enhancement, testing

#1457 Solved issues in configuration files
  doc/quickstart/configure.rst
  esmvalcore/_config/_config.py
  esmvalcore/config-user.yml
  tests/unit/config/test_config.py
Labels: documentation

#1462 add direct link to download conda lock file in the install documentation
  doc/quickstart/install.rst
Labels: documentation

#1467 Local PR for #1459 CITATION.cff fix and automatic validation of your citation metadata
  .github/workflows/citation_file_validator.yml
  CITATION.cff
Labels: documentation, enhancement

#1468 Fix provenance file permissions
  esmvalcore/_provenance.py
Labels: bug

#1426 Updated documentation on how to deprecate features
  doc/contributing.rst
Labels: documentation

#1438 Switch to Mambaforge in Github Actions tests
  .github/workflows/install-from-conda.yml
  .github/workflows/install-from-pypi.yml
  .github/workflows/install-from-source.yml
  .github/workflows/run-tests-monitor.yml
  .github/workflows/run-tests.yml
Labels: enhancement, testing

#1473 added reference hook to conda lock shtuffs in documentation install section
  doc/quickstart/install.rst
Labels: documentation

#673 Add ensemble statistics preprocessor and 'groupby' option for multimodel
  doc/recipe/preprocessor.rst
  esmvalcore/_data_finder.py
  esmvalcore/_provenance.py
  esmvalcore/_recipe.py
  esmvalcore/_recipe_checks.py
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_multimodel.py
  esmvalcore/preprocessor/_other.py
  setup.cfg
  tests/__init__.py
  tests/integration/test_recipe.py
  tests/integration/test_recipe_checks.py
  tests/unit/preprocessor/_multimodel/test_multimodel.py
  tests/unit/preprocessor/_other/test_other.py
  tests/unit/preprocessor/test_runner.py
  tests/unit/test_recipe.py
Labels: preprocessor

#1477 Increased ESMValCore version to 2.5.0rc1
  CITATION.cff
  esmvalcore/_version.py
  package/meta.yaml
Labels: documentation

#1471 Removed scalar coordinates `p0` and `ptop` prior to merge in `multi_model_statistics`
  esmvalcore/cmor/_fixes/shared.py
  esmvalcore/preprocessor/_multimodel.py
  tests/integration/cmor/_fixes/test_common.py
  tests/integration/cmor/_fixes/test_shared.py
  tests/unit/preprocessor/_multimodel/test_multimodel.py
Labels: bug

#1472 Added fix for AIRS v2.1 (obs4mips)
  .github/workflows/install-from-pypi.yml
  esmvalcore/cmor/_fixes/obs4mips/airs_2_1.py
  tests/integration/cmor/_fixes/obs4mips/test_airs_2_1.py
Labels: fix for dataset

#1483 Added `dataset` and `alias` attributes to `multi_model_statistics` output
  esmvalcore/_recipe.py
  tests/__init__.py
  tests/unit/test_recipe.py
Labels: bug

#1476 Added changelog for v2.5.0 release
  CITATION.cff
  doc/changelog.rst
  doc/conf.py
  doc/recipe/preprocessor.rst
Labels: documentation

#1486 Fixed issues with multi-model-statistics timeranges
  doc/recipe/overview.rst
  esmvalcore/_recipe.py
  esmvalcore/preprocessor/_multimodel.py
  tests/unit/preprocessor/_multimodel/test_multimodel.py
  tests/unit/test_recipe.py
Labels: bug

#1487 Increased ESMValCore version to 2.5.0rc2
  CITATION.cff
  doc/changelog.rst
  esmvalcore/_version.py
  package/meta.yaml
Labels: documentation

#1489 turn off conda lock file creation on any push on `main` branch from Github Action test
  .github/workflows/create-condalock-file.yml
Labels: testing

#1491 Restored `scipy` intersphinx mapping
  doc/conf.py
Labels: documentation

#1490 Add DRS path test for IPSLCM files
  tests/integration/data_finder.yml
Labels: testing

#1494 Fixed output messages for CMOR logging
  esmvalcore/cmor/check.py
Labels: bug

#1497 Fixed `clip_timerange` if only a single time point is extracted
  esmvalcore/preprocessor/_time.py
  tests/unit/preprocessor/_time/test_time.py
Labels: bug

#1500 Fixed chunking in `multi_model_statistics`
  esmvalcore/preprocessor/_multimodel.py
  tests/unit/preprocessor/_multimodel/test_multimodel.py
Labels: bug

#1504 Increased ESMValCore version to 2.5.0rc3
  CITATION.cff
  doc/changelog.rst
  esmvalcore/_version.py
  package/meta.yaml
Labels: documentation

#1506 Fix download instructions for the MSWEP dataset
  doc/develop/fixing_data.rst
Labels: documentation

#1417 Documentation updated for the new cmorizer framework
  doc/quickstart/find_data.rst
Labels: documentation, release

#1511 Pinned `iris`
  environment.yml
  package/meta.yaml
  setup.py
Labels: installation, iris
