Repository ESMValGroup/ESMValCore, pull requests merged in 2023-02, with the labels that each got.

#1898 Refactored `regrid()` and removed unnecessary code not needed anymore due to new iris version
  environment.yml
  esmvalcore/preprocessor/_regrid.py
  setup.py
  tests/integration/preprocessor/_regrid/test_regrid.py
  tests/unit/preprocessor/_regrid/test_regrid.py
Labels: enhancement, iris

#1813 Smarter removal of coordinate metadata in `multi_model_statistics` preprocessor
  esmvalcore/preprocessor/_multimodel.py
  tests/unit/preprocessor/_multimodel/test_multimodel.py
Labels: enhancement

#1914 Updated URL of ICON grid file used for testing
  tests/integration/cmor/_fixes/icon/test_icon.py
  tests/integration/cmor/_fixes/test_data/icon_2d.nc
  tests/integration/cmor/_fixes/test_data/icon_3d.nc
  tests/integration/cmor/_fixes/test_data/icon_grid.nc
Labels: testing

#1912 Do not realise coordinates in `check.py`
  esmvalcore/cmor/check.py
  tests/unit/cmor/test_cmor_check.py
Labels: enhancement, cmor

#1919 Fixed `set_range_in_0_360` for dask arrays
  esmvalcore/cmor/check.py
  tests/unit/cmor/test_cmor_check.py
Labels: bug

#1783 Made equalized attributes in concatenated cubes consistent across runs
  esmvalcore/iris_helpers.py
  esmvalcore/preprocessor/_io.py
  esmvalcore/typing.py
  tests/integration/preprocessor/_io/test_concatenate.py
  tests/unit/test_iris_helpers.py
Labels: bug, iris

#1831 Message for users when they use esmvaltool executable from esmvalcore only
  esmvalcore/_main.py
Labels: UX

#1921 Allowed usage of `multi_model_statistics` on cubes with identical `name()` and `units` (but e.g. different long_name)
  esmvalcore/preprocessor/_multimodel.py
  tests/unit/preprocessor/_multimodel/test_multimodel.py
Labels: enhancement

#1922 Fix automatic download of ICON grid file and make ICON UGRIDization optional (default: true)
  doc/quickstart/find_data.rst
  environment.yml
  esmvalcore/cmor/_fixes/icon/_base_fixes.py
  esmvalcore/cmor/_fixes/icon/icon.py
  setup.py
  tests/integration/cmor/_fixes/icon/test_icon.py
Labels: enhancement

#1920 Improve reading facets from ESGF search results
  esmvalcore/esgf/_download.py
  esmvalcore/esgf/facets.py
  tests/integration/esgf/search_results/expected.yml
  tests/integration/esgf/search_results/historical_gn_r4i1p1f1_CMIP6_CESM2_Amon_tas.json
  tests/integration/esgf/search_results/obs4MIPs_GPCP-V2.3_pr.json
  tests/integration/esgf/test_search_download.py
Labels: bug, enhancement

#1928 Fix for FGOALS-f3-L clt
  esmvalcore/cmor/_fixes/cmip6/fgoals_f3_l.py
  tests/integration/cmor/_fixes/cmip6/test_fgoals_f3_l.py
Labels: fix for dataset

#1940 Replace timerange nested lists in docs with overview table
  doc/recipe/overview.rst
Labels: documentation

#1918 Updated section "backward compatibility" in contributing.rst
  doc/changelog.rst
  doc/contributing.rst
Labels: documentation

#1936 Fix issue with reading dates from files
  esmvalcore/_recipe/check.py
  esmvalcore/local.py
  tests/unit/local/test_time.py
Labels: bug

#1937 Add institute name used on ESGF for CMIP5 CanAM4, CanCM4, and CanESM2
  esmvalcore/config/extra_facets/cmip5-institutes.yml
  tests/unit/test_dataset.py
Labels: bug
