Repository ESMValGroup/ESMValCore, pull requests merged in 2023-11, with the labels that each got.

#2249 Add changelog and update version number for v2.10.0rc1
  CITATION.cff
  doc/changelog.rst
  doc/recipe/preprocessor.rst
Labels: documentation

#2252 [condalock] Manual update of the conda lock file
  conda-linux-64.lock
Labels: installation, condalock

#2236 Improve the exception message when an option within the rootpath section is missing from the user configuration file
  esmvalcore/local.py
  tests/unit/local/test_get_rootpath.py
Labels: enhancement, UX
