Repository ESMValGroup/ESMValCore, pull requests merged in 2023-06, with the labels that each got.

#2046 Respect `ignore_warnings` settings in `Dataset.load`
  doc/quickstart/configure.rst
  esmvalcore/_recipe/recipe.py
  esmvalcore/config/_config.py
  esmvalcore/dataset.py
  esmvalcore/preprocessor/_supplementary_vars.py
  tests/unit/config/test_config.py
  tests/unit/recipe/test_recipe.py
  tests/unit/test_dataset.py
Labels: bug

#2052 Fixed usage of custom location for custom tables
  esmvalcore/config/_config.py
  esmvalcore/config/_validated_config.py
  tests/unit/config/test_config.py
  tests/unit/config/test_config_validator.py
Labels: bug

#2043 Allow specifying `raw_units` for CESM2, EMAC, and ICON CMORizers
  doc/quickstart/find_data.rst
  esmvalcore/cmor/_fixes/emac/_base_fixes.py
  esmvalcore/cmor/_fixes/emac/emac.py
  esmvalcore/cmor/_fixes/icon/_base_fixes.py
  esmvalcore/cmor/_fixes/icon/icon.py
  esmvalcore/cmor/_fixes/native_datasets.py
  esmvalcore/config/extra_facets/emac-mappings.yml
  esmvalcore/config/extra_facets/icon-mappings.yml
  tests/integration/cmor/_fixes/emac/test_emac.py
  tests/integration/cmor/_fixes/icon/test_icon.py
  tests/integration/cmor/_fixes/test_native_datasets.py
Labels: enhancement

#2055 Fix issue with writing index.html when using --resume-from
  esmvalcore/experimental/recipe_output.py
  esmvalcore/experimental/templates/TaskOutput.j2
Labels: bug

#2038 Fixed bug in ICON CMORizer that lead to shifted time coordinates
  doc/quickstart/find_data.rst
  doc/recipe/overview.rst
  esmvalcore/cmor/_fixes/icon/icon.py
  tests/integration/cmor/_fixes/icon/test_icon.py
Labels: bug

#2077 Remove vectorized extra from shapely
  setup.py
Labels: installation

#2078 ICON: allow specifying horizontal grid file in recipe/extra facets
  doc/quickstart/find_data.rst
  environment.yml
  esmvalcore/cmor/_fixes/icon/_base_fixes.py
  tests/integration/cmor/_fixes/icon/test_icon.py
Labels: fix for dataset

#2079 Add changelog for v2.8.1
  doc/changelog.rst
Labels: documentation

#2080 Add v2.8.1 release notes
  doc/changelog.rst
Labels: documentation

#2008 Support IPCC AR6 regions in `extract_shape`
  doc/recipe/preprocessor.rst
  esmvalcore/_recipe/recipe.py
  esmvalcore/preprocessor/_area.py
  esmvalcore/preprocessor/shapefiles/ar6.LICENSE
  esmvalcore/preprocessor/shapefiles/ar6.dbf
  esmvalcore/preprocessor/shapefiles/ar6.prj
  esmvalcore/preprocessor/shapefiles/ar6.shp
  esmvalcore/preprocessor/shapefiles/ar6.shx
  tests/integration/recipe/test_recipe.py
  tests/unit/preprocessor/_area/test_area.py
  tests/unit/recipe/test_recipe.py
Labels: preprocessor

#2083 add python 3.11 to github actions tests installing deployed packages (conda and PyPI)
  .github/workflows/install-from-conda.yml
  .github/workflows/install-from-pypi.yml
Labels: testing

#2087 Fix regridding issue where target grid is more than 2D
  esmvalcore/preprocessor/_regrid.py
  tests/unit/preprocessor/_regrid/test_regrid.py
Labels: bug, preprocessor

#2088 Add changelog for v2.9.0
  CITATION.cff
  doc/changelog.rst
Labels: documentation

#2097 Include `-` in allowed characters for bibtex references
  esmvalcore/_citation.py
  tests/unit/test_citation.py
Labels: bug

#2109 Avoid realizing data in preprocessor function `concatenate` when cubes overlap
  esmvalcore/preprocessor/_io.py
Labels: preprocessor, dask

#2105 Do not raise an exception if the requested version of a file is not available for all matching files on ESGF
  esmvalcore/esgf/_search.py
  tests/unit/esgf/test_search.py
Labels: bug

#2100 Add fix for EC-Earth3-Veg tos calendar
  esmvalcore/cmor/_fixes/cmip6/ec_earth3_veg.py
  tests/integration/cmor/_fixes/cmip6/test_ec_earth3_veg.py
Labels: fix for dataset

#2099 Correct GISS-E2-1-G `tos` units
  esmvalcore/cmor/_fixes/cmip6/giss_e2_1_g.py
  tests/integration/cmor/_fixes/cmip6/test_giss_e2_1_g.py
Labels: fix for dataset

#2108 remove `with_mypy` or `with-mypy` extension/optional tool for prospector
  setup.py
Labels: installation

#2111 Improve preprocessor output sorting code
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_io.py
Labels: preprocessor

#2118 Fix gitter badge in README
  README.md
Labels: bug, documentation
