Repository ESMValGroup/ESMValCore, pull requests merged in 2023-12, with the labels that each got.

#2264 Faster coordinate checks and longitude fix
  esmvalcore/cmor/_fixes/fix.py
  esmvalcore/cmor/check.py
Labels: dask

#2267 [conda-lock] fix test installation from conda-lock file: use `pip` from lock file
  .github/workflows/install-from-condalock-file.yml
Labels: testing

#2269 make build and deploy to PyPI Github Action use PyPI's new trusted publishers authentication
  .github/workflows/build-and-deploy-on-pypi.yml
Labels: release

#2273 [CircleCI] Fix `build_documentation` test
  .circleci/config.yml
Labels: testing

#2263 Fixing missing height coordinates in MPI-ESM1-2-HR and MPI-ESM1-2-XR
  esmvalcore/cmor/_fixes/cmip6/mpi_esm1_2_hr.py
  esmvalcore/cmor/_fixes/cmip6/mpi_esm1_2_xr.py
  tests/integration/cmor/_fixes/cmip6/test_mpi_esm1_2_hr.py
Labels: fix for dataset, data issue

#2282 Add highlights to the v2.10 changelog
  CITATION.cff
  doc/changelog.rst
Labels: documentation

#2287 Use short links in changelog
  doc/changelog.rst
  doc/conf.py
  doc/quickstart/configure.rst
Labels: documentation

#2258 New preprocessor: `local_solar_time`
  doc/recipe/preprocessor.rst
  esmvalcore/iris_helpers.py
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_time.py
  tests/integration/preprocessor/_time/__init__.py
  tests/integration/preprocessor/_time/test_time.py
  tests/unit/preprocessor/_time/test_time.py
  tests/unit/test_iris_helpers.py
Labels: preprocessor
