Repository ESMValGroup/ESMValCore, pull requests merged in 2023-08, with the labels that each got.

#2166 re-add correctly region-extracted cell measures and ancillary variables after `extract_region` (for Changelog v2.10: authors: @valeriupredoi and @schlunma)
  esmvalcore/preprocessor/_area.py
  tests/integration/preprocessor/_extract_region/test_intersect.py
Labels: bug

#2160 Updated doc about fixes and added type hints to fix functions
  doc/conf.py
  doc/develop/fixing_data.rst
  doc/recipe/preprocessor.rst
  esmvalcore/cmor/_fixes/fix.py
  esmvalcore/cmor/fix.py
  esmvalcore/preprocessor/_io.py
Labels: fix for dataset

#2115 ERA5 on-the-fly CMORizer: changed sign of `evspsbl` and `evspsblpot`
  doc/quickstart/find_data.rst
  esmvalcore/cmor/_fixes/native6/era5.py
  esmvalcore/cmor/_fixes/native6/era5_land.py
  tests/integration/cmor/_fixes/native6/test_era5.py
Labels: fix for dataset, cmor

#2168 Add ch4 surface custom cmor table entry
  esmvalcore/cmor/tables/custom/CMOR_ch4s.dat
  tests/integration/cmor/test_table.py
Labels: cmor

#2169 Make preprocessors mask_above/below_threshold, mask_inside/outside_range lazy
  .zenodo.json
  CITATION.cff
  esmvalcore/preprocessor/_mask.py
Labels: enhancement, dask

#2182 Fix typo in citation file
  CITATION.cff
Labels: enhancement

#2139 Use smarter (units-aware) weights
  doc/recipe/preprocessor.rst
  esmvalcore/preprocessor/_area.py
  esmvalcore/preprocessor/_shared.py
  esmvalcore/preprocessor/_time.py
  esmvalcore/preprocessor/_volume.py
  tests/unit/preprocessor/_area/test_area.py
  tests/unit/preprocessor/_time/test_time.py
  tests/unit/preprocessor/_volume/test_volume.py
Labels: enhancement, iris, preprocessor, backwards incompatible change
