Repository ESMValGroup/ESMValCore, pull requests merged in 2023-01, with the labels that each got.

#1883 Remove an extra space character from a filename
  esmvalcore/cmor/_fixes/cordex/__init__.py
Labels: bug

#1876 Update esmpy import for ESMF v8.4.0
  esmvalcore/preprocessor/_regrid_esmpy.py
  tests/unit/preprocessor/_regrid_esmpy/test_regrid_esmpy.py
Labels: installation

#1866 Update filename template for obs4MIPs to better match filenames
  esmvalcore/config-developer.yml
Labels: bug, backwards incompatible change

#1869 Improve resilience of ESGF search
  esmvalcore/esgf/_search.py
  tests/unit/esgf/test_search.py
Labels: bug

#1880 Fix issue with no files found if timerange start/end differs in length
  esmvalcore/esgf/_search.py
  esmvalcore/local.py
  tests/unit/local/test_select_files.py
Labels: bug

#1886 Add `driver` and `sub_experiment` tags to generate dataset aliases
  esmvalcore/_recipe.py
  tests/integration/test_recipe.py
Labels: bug

#1849 Allowed usage of `multi_model_statistics` on single cubes/products
  esmvalcore/preprocessor/_multimodel.py
  tests/unit/preprocessor/_multimodel/test_multimodel.py
Labels: enhancement

#1877 Add `esmvalcore.dataset` module
  doc/api/esmvalcore.dataset.rst
  doc/api/esmvalcore.rst
  doc/conf.py
  doc/example-notebooks.rst
  doc/gensidebar.py
  doc/notebooks
  doc/quickstart/configure.rst
  environment.yml
  esmvalcore/_main.py
  esmvalcore/_recipe/__init__.py
  esmvalcore/_recipe/check.py
  esmvalcore/_recipe/from_datasets.py
  esmvalcore/_recipe/recipe.py
  esmvalcore/_recipe/recipe_schema.yml
  esmvalcore/cmor/table.py
  esmvalcore/config-user.yml
  esmvalcore/config/_config_validators.py
  esmvalcore/dataset.py
  esmvalcore/experimental/recipe.py
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_ancillary_vars.py
  notebooks/composing-recipes.ipynb
  notebooks/discovering-data.ipynb
  notebooks/loading-and-processing-data.ipynb
  pyproject.toml
  setup.cfg
  setup.py
  tests/integration/cmor/test_table.py
  tests/integration/dataset/__init__.py
  tests/integration/dataset/areacella.nc
  tests/integration/dataset/tas.nc
  tests/integration/dataset/test_dataset.py
  tests/integration/recipe/__init__.py
  tests/integration/recipe/test_check.py
  tests/integration/recipe/test_recipe.py
  tests/unit/config/test_config.py
  tests/unit/recipe/__init__.py
  tests/unit/recipe/test_from_datasets.py
  tests/unit/recipe/test_recipe.py
  tests/unit/test_dataset.py
Labels: enhancement, api

#1863 Fix issues with searching for files on ESGF
  esmvalcore/esgf/_download.py
  tests/unit/esgf/test_search.py
Labels: bug, api

#1903 Updated ICON doc with information on usage of extract_levels preprocessor
  doc/quickstart/find_data.rst
Labels: documentation

#1905 add changelog for latest released version v2.7.1
  doc/changelog.rst
Labels: documentation

#1908 Update preprocessor.rst due to renaming of NCEP dataset to NCEP-NCAR-R1
  doc/recipe/preprocessor.rst
Labels: documentation

#1772 Fixed time points of native CESM2 output
  esmvalcore/cmor/_fixes/cesm/cesm2.py
  esmvalcore/cmor/_fixes/fix.py
  esmvalcore/cmor/fix.py
  tests/integration/cmor/_fixes/cesm/test_cesm2.py
  tests/unit/cmor/test_fix.py
Labels: bug
