Repository ESMValGroup/ESMValCore, pull requests merged in 2023-05, with the labels that each got.

#1984 Make sure to only use provenance copies when using `product.wasderivedfrom()`
  esmvalcore/preprocessor/_mask.py
  tests/__init__.py
  tests/unit/preprocessor/_mask/test_mask_multimodel.py
Labels: enhancement

#1832 [Python] Add support for Python=3.11
  .circleci/config.yml
  .github/workflows/build-and-deploy-on-pypi.yml
  .github/workflows/create-condalock-file.yml
  .github/workflows/install-from-conda.yml
  .github/workflows/install-from-condalock-file.yml
  .github/workflows/install-from-pypi.yml
  .github/workflows/install-from-source.yml
  .github/workflows/run-tests-monitor.yml
  .github/workflows/run-tests.yml
  .readthedocs.yaml
  doc/api/esmvalcore.cmor.rst
  doc/conf.py
  environment.yml
  esmvalcore/cmor/check.py
  setup.py
Labels: installation, testing

#2020 Update pre-commit hooks
  .pre-commit-config.yaml
Labels: testing

#2022 Fix: Icon hourly data rounding issues
  esmvalcore/cmor/_fixes/icon/icon.py
  tests/integration/cmor/_fixes/icon/test_icon.py
Labels: bug

#2023 Use default SSL context when using geopy.geocoders.Nominatim
  esmvalcore/preprocessor/_regrid.py
  tests/integration/preprocessor/_regrid/test_extract_location.py
Labels: bug, preprocessor

#1971 Make time-related fixes work with time dimensions `time1`, `time2`, `time3`
  esmvalcore/cmor/_fixes/cesm/cesm2.py
  esmvalcore/cmor/_fixes/emac/emac.py
  esmvalcore/cmor/_fixes/icon/icon.py
  esmvalcore/cmor/_fixes/native_datasets.py
  esmvalcore/cmor/table.py
  tests/integration/cmor/_fixes/cesm/test_cesm2.py
  tests/integration/cmor/_fixes/emac/test_emac.py
  tests/integration/cmor/_fixes/icon/test_icon.py
  tests/integration/cmor/_fixes/test_native_datasets.py
  tests/unit/cmor/test_table.py
Labels: bug, cmor

#2027 [condalock] modernize conda lock file creation workflow with mamba, Mambaforge etc
  .github/workflows/create-condalock-file.yml
Labels: installation, condalock

#2030 Make sure to always create cache directory when using ICON grid files
  esmvalcore/cmor/_fixes/icon/_base_fixes.py
Labels: bug

#1999 Fixed altitude <--> pressure level conversion for masked arrays
  esmvalcore/cmor/_fixes/shared.py
  tests/integration/cmor/_fixes/test_shared.py
Labels: bug

#1961 Allowed ignoring of scalar time coords in `multi_model_statistics`
  esmvalcore/preprocessor/_multimodel.py
  tests/sample_data/multimodel_statistics/test_multimodel.py
  tests/unit/preprocessor/_multimodel/test_multimodel.py
Labels: bug

#2053 Drop support for Python 3.8
  .github/workflows/install-from-conda.yml
  .github/workflows/install-from-condalock-file.yml
  .github/workflows/install-from-pypi.yml
  .github/workflows/install-from-source.yml
  .github/workflows/run-tests-comment.yml
  .github/workflows/run-tests-monitor.yml
  .github/workflows/run-tests.yml
  environment.yml
  setup.py
Labels: installation

#2065 Show ESMValTool logo on PyPI webpage
  README.md
Labels: documentation

#1988 Introduce `Fix.session` to access `Session` in fixes
  doc/develop/fixing_data.rst
  esmvalcore/cmor/_fixes/fix.py
  esmvalcore/cmor/fix.py
  esmvalcore/dataset.py
  tests/integration/cmor/_fixes/test_fix.py
  tests/unit/cmor/test_fix.py
  tests/unit/test_dataset.py
Labels: enhancement, fix for dataset

#2056 Remove deprecated configuration options
  doc/api/esmvalcore.experimental.config.rst
  doc/api/esmvalcore.experimental.rst
  esmvalcore/_config/__init__.py
  esmvalcore/_config/config-logging.yml
  esmvalcore/config/_config_object.py
  esmvalcore/experimental/config/__init__.py
  tests/integration/test_deprecated_config.py
Labels: deprecated feature, backwards incompatible change

#1761 Make extract_levels preprocessor function lazy
  environment.yml
  esmvalcore/preprocessor/_other.py
  esmvalcore/preprocessor/_regrid.py
  setup.py
  tests/integration/preprocessor/_regrid/test_extract_levels.py
  tests/unit/preprocessor/_other/test_other.py
  tests/unit/preprocessor/_regrid/test_extract_levels.py
Labels: preprocessor

#2067 ICON: Allowed specifying vertical grid information in recipe
  doc/quickstart/find_data.rst
  esmvalcore/cmor/_fixes/icon/_base_fixes.py
  esmvalcore/cmor/_fixes/icon/icon.py
  esmvalcore/cmor/_fixes/native_datasets.py
  tests/integration/cmor/_fixes/icon/test_icon.py
  tests/integration/cmor/_fixes/test_native_datasets.py
Labels: enhancement

#2068 Added `period='hourly'` for `climate_statistics` and `anomalies`
  doc/recipe/preprocessor.rst
  esmvalcore/preprocessor/_time.py
  tests/unit/preprocessor/_time/test_time.py
Labels: enhancement, preprocessor
