Repository ESMValGroup/ESMValCore, pull requests merged in 2023-10, with the labels that each got.

#2215 Remove deprecated preprocessor function `cleanup`
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_io.py
  tests/integration/preprocessor/_io/test_cleanup.py
  tests/unit/preprocessor/test_preprocessor_file.py
Labels: backwards incompatible change

#2213 Removed deprecated configuration option `offline`
  esmvalcore/_main.py
  esmvalcore/config/_config_validators.py
  tests/integration/test_deprecated_config.py
  tests/integration/test_main.py
Labels: backwards incompatible change

#2214 Added `get_time_bounds` and `get_next_month` to public API
  esmvalcore/cmor/_fixes/cmip6/iitm_esm.py
  esmvalcore/cmor/_fixes/cmip6/kace_1_0_g.py
  esmvalcore/cmor/_fixes/fix.py
  esmvalcore/cmor/_fixes/shared.py
  esmvalcore/cmor/fixes.py
  esmvalcore/preprocessor/_time.py
  tests/integration/cmor/_fixes/test_shared.py
  tests/unit/cmor/test_fixes.py
  tests/unit/cmor/test_generic_fix.py
Labels: cmor

#2181 Cleaned and extended function that extracts datetimes from paths
  esmvalcore/dataset.py
  esmvalcore/esgf/_search.py
  esmvalcore/local.py
  tests/unit/local/test_time.py
Labels: enhancement

#2144 Relax concatenation checks for `--check_level=relax` and `--check_level=ignore`
  doc/quickstart/run.rst
  esmvalcore/dataset.py
  esmvalcore/preprocessor/_io.py
  tests/integration/preprocessor/_io/test_concatenate.py
  tests/unit/test_dataset.py
Labels: preprocessor

#2219 Add file encoding (and some read modes) at open file step
  doc/gensidebar.py
  esmvalcore/_citation.py
  esmvalcore/_main.py
  esmvalcore/_task.py
  esmvalcore/cmor/table.py
  esmvalcore/config/_config.py
  esmvalcore/config/_config_object.py
  esmvalcore/config/_diagnostics.py
  esmvalcore/config/_esgf_pyclient.py
  esmvalcore/config/_logging.py
  esmvalcore/esgf/_download.py
  esmvalcore/experimental/recipe.py
  esmvalcore/experimental/recipe_info.py
  esmvalcore/experimental/recipe_output.py
  esmvalcore/preprocessor/_io.py
  setup.py
  tests/integration/cmor/_fixes/icon/test_icon.py
  tests/integration/esgf/test_search_download.py
  tests/integration/recipe/test_recipe.py
  tests/integration/test_citation.py
  tests/integration/test_diagnostic_run.py
  tests/integration/test_local.py
  tests/integration/test_main.py
  tests/integration/test_task.py
  tests/unit/config/test_config.py
  tests/unit/config/test_esgf_pyclient.py
  tests/unit/documentation/test_changelog.py
  tests/unit/esgf/test_download.py
  tests/unit/task/test_diagnostic_task.py
  tests/unit/task/test_resume_task.py
Labels: enhancement

#2217 Check type of argument passed to `esmvalcore.cmor.table.read_cmor_tables`
  esmvalcore/cmor/table.py
  tests/integration/cmor/test_read_cmor_tables.py
Labels: api

#2062 Dynamic HTML output for monitoring
  esmvalcore/experimental/recipe_output.py
  esmvalcore/experimental/templates/RecipeOutput.j2
  esmvalcore/experimental/templates/TaskOutput.j2
  esmvalcore/experimental/templates/head.j2
  esmvalcore/experimental/templates/recipe_output_page.j2
  esmvalcore/experimental/templates/scripts.js
  tests/unit/experimental/test_recipe_output.py
Labels: enhancement

#2224 remove meercode badge from README because their API is broken
  README.md
Labels: enhancement

#2232 Correct usage help text of version command
  esmvalcore/_main.py
Labels: documentation

#2238 Fix a problem with sorting datasets that have a mix of facet types
  esmvalcore/_recipe/from_datasets.py
  tests/unit/recipe/test_from_datasets.py
Labels: bug

#2240 Fix `concatenate` preprocessor function
  esmvalcore/preprocessor/_io.py
Labels: bug

#2243 revisit the comment-triggered Github Actions test
  .github/workflows/run-tests-comment-v2.yml
  .github/workflows/run-tests-comment.yml
Labels: enhancement, testing

#2244 Remove workflow that runs Github Actions tests from PR comment
  .github/workflows/run-tests-comment-v2.yml
  doc/contributing.rst
Labels: enhancement, testing

#2245 Add `navigation_with_keys: True` to `html_theme_options` in Readthedocs `conf.py`
  doc/conf.py
Labels: documentation, testing

#2233 replace squarey badge with roundy shield for Anaconda sticker in README
  README.md
Labels: documentation

#2247 Fix time overlap handling in concatenation
  esmvalcore/preprocessor/_io.py
Labels: bug, preprocessor
