Repository ESMValGroup/ESMValCore, pull requests merged in 2023-09, with the labels that each got.

#2095 Fix sorting of ensemble members in `esmvalcore.dataset.datasets_to_recipe`
  esmvalcore/_recipe/from_datasets.py
  tests/unit/recipe/test_from_datasets.py
Labels: bug

#2146 Call coord.core_bounds() instead of coord.bounds in `check.py`
  esmvalcore/cmor/check.py
Labels: dask

#2204 Ensure compatible zstandard and zstd versions for .conda support
  .readthedocs.yaml
Labels: documentation

#2201 Remove deprecated way of calling ``esmvalcore.cmor.table.read_cmor_tables``
  esmvalcore/cmor/table.py
  tests/integration/cmor/test_read_cmor_tables.py
Labels: backwards incompatible change

#2205 Rechunk between preprocessor steps
  esmvalcore/preprocessor/__init__.py
Labels: dask

#2207 Remove deprecated callback argument from preprocessor ``load`` function
  esmvalcore/_recipe/recipe.py
  esmvalcore/dataset.py
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_io.py
  tests/integration/preprocessor/_io/test_load.py
  tests/integration/preprocessor/test_preprocessing_task.py
  tests/integration/recipe/test_recipe.py
  tests/unit/recipe/test_recipe.py
  tests/unit/test_dataset.py
Labels: preprocessor, backwards incompatible change

#2200 Reduce the size of the dask graph created by the ``anomalies`` preprocessor function
  esmvalcore/preprocessor/_time.py
  tests/unit/preprocessor/_time/test_time.py
Labels: dask

#2202 Remove the deprecated option ``use_legacy_supplementaries``
  doc/recipe/preprocessor.rst
  esmvalcore/_recipe/recipe.py
  esmvalcore/_recipe/to_datasets.py
  esmvalcore/config/_config_validators.py
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_supplementary_vars.py
  tests/integration/conftest.py
  tests/integration/preprocessor/_supplementary_vars/test_add_fx_variables.py
  tests/integration/preprocessor/_supplementary_vars/test_add_supplementary_variables.py
  tests/integration/recipe/test_recipe.py
  tests/integration/test_deprecated_config.py
  tests/unit/recipe/test_recipe.py
  tests/unit/test_dataset.py
Labels: backwards incompatible change

#2206 Update code coverage orbs
  .circleci/config.yml
Labels: testing

#2209 Restored usage of numpy in `_mask_with_shp`
  esmvalcore/preprocessor/_mask.py
Labels: bug

#2210 Remove outdated documentation
  doc/recipe/preprocessor.rst
Labels: documentation
