Repository ESMValGroup/ESMValCore, pull requests merged in 2024-08, with the labels that each got.

#2501 Extra facets added for EMAC to map o3, tro3 and aps
  esmvalcore/cmor/_fixes/emac/_base_fixes.py
  esmvalcore/config/extra_facets/emac-mappings.yml
  tests/integration/cmor/_fixes/emac/test_emac.py
Labels: fix for dataset

#2499 Introduction of the variable prodlnox for EMAC
  esmvalcore/cmor/_fixes/emac/emac.py
  esmvalcore/cmor/tables/custom/CMOR_prodlnox.dat
  esmvalcore/config/extra_facets/emac-mappings.yml
  tests/integration/cmor/_fixes/emac/test_emac.py
Labels: enhancement, variable derivation, EMAC

#2504 Pin dask to avoid 2024.8.0 - problems with masked fill/missing values
  environment.yml
  setup.py
Labels: testing

#2508 Remove ability to log on to ESGF
  doc/quickstart/configure.rst
  esmvalcore/_main.py
  esmvalcore/config/_esgf_pyclient.py
  esmvalcore/esgf/_download.py
  esmvalcore/esgf/_logon.py
  tests/unit/config/test_esgf_pyclient.py
  tests/unit/esgf/test_download.py
  tests/unit/esgf/test_logon.py
  tests/unit/main/test_esmvaltool.py
Labels: enhancement

#2500 Switch to new iris >= 3.10.0 API
  environment.yml
  esmvalcore/cmor/_fixes/icon/_base_fixes.py
  esmvalcore/preprocessor/_area.py
  esmvalcore/preprocessor/_regrid.py
  esmvalcore/preprocessor/_shared.py
  esmvalcore/preprocessor/_volume.py
  setup.py
  tests/integration/cmor/_fixes/icon/test_icon.py
  tests/integration/cmor/test_table.py
  tests/unit/preprocessor/_regrid/test_broadcast_to_shape.py
  tests/unit/preprocessor/test_shared.py
Labels: installation

#2507 Fix for CMIP6 AWI-ESM-1-1-LR parent time units
  esmvalcore/cmor/_fixes/cmip6/awi_esm_1_1_lr.py
Labels: fix for dataset
