Repository ESMValGroup/ESMValCore, pull requests merged in 2024-11, with the labels that each got.

#2560 Use our own unit conversion function in our fixes
  esmvalcore/cmor/_fixes/fix.py
  esmvalcore/cmor/_fixes/native6/era5.py
  esmvalcore/cmor/_fixes/native_datasets.py
  esmvalcore/iris_helpers.py
  esmvalcore/preprocessor/_units.py
  tests/unit/test_iris_helpers.py
Labels: fix for dataset

#2423 Optimize documentation about Earth mover distance in distance_metric preprocessor
  doc/recipe/preprocessor.rst
Labels: documentation

#2395 [Numpy2] Support for `numpy==2.0.0` (and pin `iris >=3.11`)
  environment.yml
  esmvalcore/preprocessor/_compare_with_refs.py
  esmvalcore/preprocessor/_derive/_shared.py
  esmvalcore/preprocessor/_derive/co2s.py
  esmvalcore/preprocessor/_regrid.py
  esmvalcore/preprocessor/_regrid_esmpy.py
  esmvalcore/preprocessor/_regrid_unstructured.py
  esmvalcore/preprocessor/_time.py
  pyproject.toml
  tests/unit/preprocessor/_compare_with_refs/test_compare_with_refs.py
  tests/unit/preprocessor/_derive/test_shared.py
  tests/unit/preprocessor/_regrid/__init__.py
  tests/unit/preprocessor/_regrid/test__create_cube.py
  tests/unit/preprocessor/_regrid/test_extract_levels.py
Labels: enhancement, testing, Numpy2, iris311

#2550 Add `prc` fix for native6 ERA5 CMORization
  esmvalcore/cmor/_fixes/native6/era5.py
Labels: fix for dataset, cmor, observations

#2578 Do not use `Path` objects as configuration dictionary keys to avoid errors in `dask.config.merge`
  esmvalcore/config/_config_validators.py
  esmvalcore/local.py
  tests/unit/config/test_config_validator.py
Labels: config

#2520 Miscellaneous lazy preprocessor improvements
  esmvalcore/preprocessor/_area.py
  esmvalcore/preprocessor/_io.py
  esmvalcore/preprocessor/_mask.py
  esmvalcore/preprocessor/_regrid.py
  esmvalcore/preprocessor/_shared.py
  esmvalcore/preprocessor/_time.py
  tests/unit/preprocessor/_area/test_area.py
  tests/unit/preprocessor/_mask/test_mask.py
  tests/unit/preprocessor/_regrid/test_extract_levels.py
  tests/unit/preprocessor/_time/test_time.py
  tests/unit/preprocessor/test_shared.py
Labels: preprocessor, dask

#2590 Update changelog and version to v2.11.1
  CITATION.cff
  doc/changelog.rst
Labels: release

#2566 Support Python 3.13
  .github/workflows/build-and-deploy-on-pypi.yml
  .github/workflows/create-condalock-file.yml
  .github/workflows/install-from-conda.yml
  .github/workflows/install-from-condalock-file.yml
  .github/workflows/install-from-pypi.yml
  .github/workflows/install-from-source.yml
  .github/workflows/run-tests-monitor.yml
  .github/workflows/run-tests.yml
  pyproject.toml
Labels: installation, iris311

#2595 Update `CFG` with configuration options given via command line
  esmvalcore/_main.py
  tests/unit/main/test_esmvaltool.py
Labels: bug
