Repository ESMValGroup/ESMValCore, pull requests merged in 2024-01, with the labels that each got.

#2297 Increase resources for testing installation from conda-forge
  .circleci/config.yml
Labels: testing

#2294 Fixing missing height 2m coordinates in GFDL-CM4 and KIOST-ESM
  esmvalcore/cmor/_fixes/cmip6/gfdl_cm4.py
  esmvalcore/cmor/_fixes/cmip6/kiost_esm.py
  tests/integration/cmor/_fixes/cmip6/test_gfdl_cm4.py
Labels: bug, fix for dataset

#2230 allow contiguous representation of extracted regions
  esmvalcore/preprocessor/_area.py
  tests/unit/preprocessor/_area/test_area.py
Labels: backwards incompatible change

#2303 Show files of supplementary variables explicitly in log
  esmvalcore/_recipe/recipe.py
Labels: enhancement

#2256 Read derived variables from other MIP tables
  doc/quickstart/configure.rst
  doc/recipe/preprocessor.rst
  esmvalcore/cmor/table.py
  tests/integration/cmor/test_table.py
Labels: preprocessor

#2279 Also read default custom CMOR tables if custom location is specified
  doc/quickstart/configure.rst
  esmvalcore/cmor/table.py
  tests/integration/cmor/test_read_cmor_tables.py
  tests/integration/cmor/test_table.py
Labels: cmor

#2281 National Computing Infrastructure (NCI), Site specific configuration
  esmvalcore/config-developer.yml
  esmvalcore/config-user.yml
  tests/integration/data_finder.yml
Labels: documentation, enhancement

#2277 Add custom CMOR table for total cloud water (tcw)
  esmvalcore/cmor/tables/custom/CMOR_tcw.dat
Labels: cmor, observations

#2305 Pin pandas to avoid broken `round` function
  environment.yml
  esmvalcore/cmor/_fixes/icon/icon.py
  setup.py
Labels: testing

#2307 remove team reviewers from conda lock generation workflow in Github Actions
  .github/workflows/create-condalock-file.yml
Labels: testing, condalock

#2292 Add height for sfcWindmax in MPI HighRes models
  esmvalcore/cmor/_fixes/cmip6/mpi_esm1_2_hr.py
  esmvalcore/cmor/_fixes/cmip6/mpi_esm1_2_xr.py
Labels: fix for dataset, cmor

#2270 Added special unit conversion m -> DU for total column ozone (toz)
  doc/recipe/preprocessor.rst
  esmvalcore/preprocessor/_units.py
  tests/unit/preprocessor/_units/test_convert_units.py
Labels: preprocessor

#2193 Remove mocking from tests in `tests/unit/preprocessor/_regrid/test_extract_point.py`
  tests/unit/preprocessor/_regrid/test_extract_point.py
Labels: testing

#2183 Allow cubes as input for `bias` preprocessor
  doc/recipe/preprocessor.rst
  esmvalcore/_recipe/check.py
  esmvalcore/_recipe/recipe.py
  esmvalcore/preprocessor/_bias.py
  tests/integration/recipe/test_recipe.py
  tests/unit/preprocessor/_bias/test_bias.py
Labels: preprocessor

#2315 Pin `pytest-mypy` plugin to `>=0.10.3` comply with new `pytest==8`
  environment.yml
  setup.py
Labels: testing
