Repository ESMValGroup/ESMValCore, pull requests merged in 2024-07, with the labels that each got.

#2470 New custom variable for tos uncertainty
  esmvalcore/cmor/tables/custom/CMOR_tosStderr.dat
  tests/integration/cmor/test_table.py
Labels: cmor

#2474 Update the release date and version number for v2.11.0
  CITATION.cff
Labels: release

#2447 [Merge after v2.11.0 Release] Remove support for Python 3.9
  .github/workflows/install-from-conda.yml
  .github/workflows/install-from-condalock-file.yml
  .github/workflows/install-from-pypi.yml
  .github/workflows/install-from-source.yml
  .github/workflows/run-tests-monitor.yml
  .github/workflows/run-tests.yml
  doc/quickstart/install.rst
  environment.yml
  setup.cfg
  setup.py
  tests/unit/preprocessor/_regrid_esmpy/test_regrid_esmpy.py
Labels: installation

#2430 on-the-fly cmoriser for ACCESS native data
  .zenodo.json
  CITATION.cff
  doc/quickstart/find_data.rst
  esmvalcore/cmor/_fixes/access/__init__.py
  esmvalcore/cmor/_fixes/access/_base_fix.py
  esmvalcore/cmor/_fixes/access/access_esm1_5.py
  esmvalcore/config-developer.yml
  esmvalcore/config/extra_facets/access-mappings.yml
  tests/integration/cmor/_fixes/access/__init__.py
  tests/integration/cmor/_fixes/access/test_access_esm1_5.py
  tests/integration/cmor/_fixes/test_data/access_native.nc
Labels: enhancement

#2480 Ignore autosummary warning in documentation build
  doc/conf.py
Labels: documentation

#2478 Run a nightly test with the development version of dependencies
  .circleci/config.yml
Labels: testing

#2352 Write settings.yml parameters in original order
  esmvalcore/_task.py
  tests/integration/test_task.py
Labels: enhancement

#2497 Fix type hint for new mypy version
  esmvalcore/_recipe/check.py
Labels: testing
