Repository ESMValGroup/ESMValCore, pull requests merged in 2024-12, with the labels that each got.

#2522 Save all files in a task at the same time to avoid recomputing intermediate results
  doc/quickstart/configure.rst
  environment.yml
  esmvalcore/_recipe/recipe.py
  esmvalcore/config/_config_validators.py
  esmvalcore/config/configurations/defaults/logging.yml
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_dask_progress.py
  esmvalcore/preprocessor/_io.py
  pyproject.toml
  tests/integration/preprocessor/_io/test_save.py
  tests/integration/preprocessor/test_preprocessing_task.py
  tests/integration/recipe/test_recipe.py
  tests/unit/config/test_config.py
  tests/unit/preprocessor/test_dask_progress.py
  tests/unit/preprocessor/test_preprocessor_file.py
  tests/unit/recipe/test_recipe.py
Labels: preprocessor, backwards incompatible change, dask

#2580 Avoid a crash when there is a timeout when shutting down the Dask cluster
  esmvalcore/config/_dask.py
  tests/unit/config/test_dask.py
Labels: bug

#2178 Add support for native ERA5 data in GRIB format
  doc/quickstart/configure.rst
  doc/quickstart/find_data.rst
  esmvalcore/_provenance.py
  esmvalcore/_recipe/recipe.py
  esmvalcore/cmor/_fixes/fix.py
  esmvalcore/cmor/_fixes/native6/era5.py
  esmvalcore/config-developer.yml
  esmvalcore/config/configurations/defaults/config-user.yml
  esmvalcore/config/extra_facets/native6-era5.yml
  esmvalcore/preprocessor/_io.py
  pyproject.toml
  tests/integration/cmor/_fixes/native6/test_era5.py
  tests/integration/cmor/test_fix.py
  tests/integration/conftest.py
  tests/integration/preprocessor/_io/test_load.py
  tests/integration/recipe/test_recipe.py
  tests/sample_data/iris-sample-data/LICENSE
  tests/sample_data/iris-sample-data/polar_stereo.grib2
  tests/unit/provenance/test_trackedfile.py
Labels: observations

#2606 switch back to Python 3.12 for conda lock file creation due to mamba<2 pin
  .github/workflows/create-condalock-file.yml
Labels: testing

#2603 Monotonicity fixes for Fgoals
  esmvalcore/cmor/_fixes/cmip6/fgoals_g3.py
  tests/integration/cmor/_fixes/cmip6/test_cesm2.py
  tests/integration/cmor/_fixes/cmip6/test_fgoals_g3.py
Labels: fix for dataset

#2617 Added more variables to EMAC extra facets
  esmvalcore/config/extra_facets/emac-mappings.yml
Labels: cmor, EMAC

#2619 Expand Amon fix of FIO-ESM-2-0 (CMIP6)
  esmvalcore/cmor/_fixes/cmip6/fio_esm_2_0.py
  tests/integration/cmor/_fixes/cmip6/test_fio_esm_2_0.py
Labels: fix for dataset

#2624 Always ignore user's configuration when running Dask tests
  tests/conftest.py
  tests/unit/config/test_dask.py
Labels: testing
