Repository ESMValGroup/ESMValCore, pull requests merged in 2024-02, with the labels that each got.

#2231 Refactor regridding
  doc/api/esmvalcore.regridding_schemes.rst
  doc/api/esmvalcore.rst
  doc/quickstart/find_data.rst
  doc/recipe/preprocessor.rst
  esmvalcore/_recipe/check.py
  esmvalcore/_recipe/recipe.py
  esmvalcore/cmor/_fixes/fix.py
  esmvalcore/cmor/_utils.py
  esmvalcore/cmor/check.py
  esmvalcore/iris_helpers.py
  esmvalcore/preprocessor/_io.py
  esmvalcore/preprocessor/_regrid.py
  esmvalcore/preprocessor/_regrid_esmpy.py
  esmvalcore/preprocessor/_regrid_unstructured.py
  esmvalcore/preprocessor/regrid_schemes.py
  tests/integration/preprocessor/_derive/test_sispeed.py
  tests/integration/preprocessor/_regrid/test_regrid.py
  tests/integration/preprocessor/_regrid/test_regrid_schemes.py
  tests/integration/preprocessor/_regrid/test_regrid_unstructured.py
  tests/integration/recipe/test_recipe.py
  tests/unit/preprocessor/_regrid/test__stock_cube.py
  tests/unit/preprocessor/_regrid/test_regrid.py
  tests/unit/preprocessor/_regrid_esmpy/test_regrid_esmpy.py
  tests/unit/test_iris_helpers.py
Labels: preprocessor, deprecated feature

#2319 Fix regridding test for unstructured nearest regridding on OSX
  tests/integration/preprocessor/_regrid/test_regrid_unstructured.py
  tests/unit/preprocessor/_regrid/test_extract_regional_grid.py
Labels: testing

#2322 Fix flaky regrid test by clearing LRU cache after each test
  tests/unit/preprocessor/_regrid/test__stock_cube.py
  tests/unit/preprocessor/_regrid/test_extract_regional_grid.py
Labels: testing

#2189 Add normalization with statistics to many statistics preprocessors
  doc/recipe/preprocessor.rst
  esmvalcore/preprocessor/_area.py
  esmvalcore/preprocessor/_shared.py
  esmvalcore/preprocessor/_volume.py
  tests/unit/preprocessor/_area/test_area.py
  tests/unit/preprocessor/_volume/test_volume.py
Labels: preprocessor

#2324 Allow deprecated regridding scheme `linear_extrapolate` in recipe checks
  esmvalcore/_recipe/check.py
  tests/integration/recipe/test_recipe.py
Labels: bug

#2321 Update `multi_model_statistics doc` with latest changes (new operators, etc.)
  esmvalcore/preprocessor/_multimodel.py
Labels: documentation

#2330 Added fix for wrong units of `clt` for CIESM and FIO-ESM-2-0
  esmvalcore/cmor/_fixes/cmip6/ciesm.py
  esmvalcore/cmor/_fixes/cmip6/fio_esm_2_0.py
  tests/integration/cmor/_fixes/cmip6/test_ciesm.py
  tests/integration/cmor/_fixes/cmip6/test_fio_esm_2_0.py
Labels: fix for dataset

#2313 Fix error message in variable definition check
  .zenodo.json
  CITATION.cff
  esmvalcore/_recipe/check.py
  esmvalcore/_recipe/recipe_schema.yml
  esmvalcore/_recipe/to_datasets.py
  tests/integration/recipe/test_recipe.py
Labels: bug

#2309 Do not read `~/.esmvaltool/config-user.yml` if `--config-file` is used
  esmvalcore/_main.py
  esmvalcore/config/__init__.py
  esmvalcore/config/_config_object.py
  tests/unit/config/test_config.py
  tests/unit/config/test_config_object.py
Labels: enhancement

#2325 More lazy fixes and preprocessing functions
  esmvalcore/cmor/_fixes/cesm/cesm2.py
  esmvalcore/cmor/_fixes/cmip5/hadgem2_cc.py
  esmvalcore/cmor/_fixes/cmip5/hadgem2_es.py
  esmvalcore/cmor/_fixes/cmip5/miroc_esm.py
  esmvalcore/cmor/_fixes/cmip6/access_esm1_5.py
  esmvalcore/cmor/_fixes/cmip6/cesm2.py
  esmvalcore/cmor/_fixes/cmip6/ec_earth3.py
  esmvalcore/cmor/_fixes/cmip6/ec_earth3_veg.py
  esmvalcore/cmor/_fixes/cmip6/giss_e2_1_g.py
  esmvalcore/cmor/_fixes/cmip6/miroc6.py
  esmvalcore/cmor/_fixes/common.py
  esmvalcore/cmor/_fixes/cordex/cordex_fixes.py
  esmvalcore/cmor/_fixes/emac/emac.py
  esmvalcore/cmor/_fixes/icon/_base_fixes.py
  esmvalcore/cmor/_fixes/native6/era5.py
  esmvalcore/cmor/_fixes/native6/mswep.py
  esmvalcore/cmor/_fixes/shared.py
  esmvalcore/preprocessor/_derive/sm.py
  esmvalcore/preprocessor/_units.py
  esmvalcore/preprocessor/_volume.py
  tests/integration/cmor/_fixes/cmip5/test_hadgem2_es.py
  tests/unit/preprocessor/_derive/test_sm.py
Labels: enhancement, preprocessor, dask

#2332 cmip6 gfdl_cm4: fix tas height fix to work for concatenated scenarios
  esmvalcore/cmor/_fixes/cmip6/gfdl_cm4.py
Labels: fix for dataset

#2336 Allow deprecated regridding scheme `unstructured_nearest` in recipe checks
  esmvalcore/_recipe/check.py
  tests/integration/recipe/test_recipe.py
Labels: deprecated feature

#2334 cordex GERICS REMO2015 lon differences above 10e-4
  esmvalcore/cmor/_fixes/cordex/cordex_fixes.py
Labels: fix for dataset

#2268 Made preprocessors mask_landsea, mask_landseaice and mask_glaciated lazy
  esmvalcore/preprocessor/_mask.py
  tests/unit/preprocessor/_mask/test_mask.py
Labels: dask

#2242 Adding sfcWind derivation from uas and vas
  esmvalcore/preprocessor/_derive/__init__.py
  esmvalcore/preprocessor/_derive/sfcwind.py
  tests/integration/cmor/_fixes/native6/test_era5.py
  tests/unit/preprocessor/_derive/test_sfcwind.py
Labels: preprocessor, variable derivation, observations

#2346 Use lazy weights for `climate_statistics` and `axis_statistics`
  esmvalcore/preprocessor/_time.py
  esmvalcore/preprocessor/_volume.py
  tests/unit/preprocessor/_time/test_time.py
  tests/unit/preprocessor/_volume/test_volume.py
Labels: dask

#2353 Pin pandas yet again avoid new `2.2.1` as well
  environment.yml
  setup.py
Labels: installation, testing
