Repository ESMValGroup/ESMValCore, pull requests merged in 2024-03, with the labels that each got.

#2363 xfail `tests/integration/cmor/_fixes/test_common.py::test_cl_hybrid_height_coord_fix_metadata` while Iris folk fix behaviour
  tests/integration/cmor/_fixes/test_common.py
Labels: testing

#2337 Support loading ICON grid from ICON rootpath
  doc/quickstart/find_data.rst
  esmvalcore/cmor/_fixes/icon/_base_fixes.py
  esmvalcore/cmor/_fixes/icon/icon.py
  tests/integration/cmor/_fixes/icon/test_icon.py
Labels: enhancement

#2356 Fixed potential memory leak in `local_solar_time`
  esmvalcore/preprocessor/_time.py
Labels: dask

#2367 Fixed 'positive' attribute in custom rtnt table
  esmvalcore/cmor/tables/custom/CMOR_rtnt.dat
Labels: cmor

#2366 Added ICON fix for rtnt
  esmvalcore/cmor/_fixes/icon/icon.py
  tests/integration/cmor/_fixes/icon/test_icon.py
Labels: fix for dataset

#2362 Update interval check in resample_hours
  esmvalcore/preprocessor/_time.py
  tests/unit/preprocessor/_time/test_time.py
Labels: preprocessor

#2379 Expanded ICON extra facets
  esmvalcore/config/extra_facets/icon-mappings.yml
Labels: fix for dataset

#2378 Handle warnings about invalid units for iris>=3.8
  esmvalcore/cmor/_fixes/icon/_base_fixes.py
  esmvalcore/preprocessor/_io.py
Labels: iris

#2382 Fix Codacy badge
  README.md
Labels: documentation
