Repository ESMValGroup/ESMValCore, pull requests merged in 2024-06, with the labels that each got.

#2445 Updated esmf-related pins
  environment.yml
  setup.py
Labels: installation

#2436 Make volume calculation in preprocessor function `volume_statistics` lazy
  esmvalcore/preprocessor/_volume.py
  tests/unit/preprocessor/_volume/test_volume.py
Labels: preprocessor, dask

#2340 Lazy mask_fillvalues preprocessor function
  environment.yml
  esmvalcore/preprocessor/_mask.py
  setup.py
  tests/integration/preprocessor/_mask/test_mask.py
  tests/unit/preprocessor/_mask/test_mask.py
Labels: preprocessor, dask

#2440 Add `interpolate` to `resample_hours`
  doc/recipe/preprocessor.rst
  esmvalcore/_recipe/check.py
  esmvalcore/_recipe/recipe.py
  esmvalcore/preprocessor/_time.py
  tests/integration/recipe/test_recipe.py
  tests/unit/preprocessor/_time/test_time.py
Labels: preprocessor

#2449 Preserve cube attribute global vs local when concatenating
  esmvalcore/iris_helpers.py
  tests/unit/test_iris_helpers.py
Labels: bug

#2453 Added iris-grib depedency
  environment.yml
  setup.py
Labels: installation, iris

#2464 Synchronize initial documentation page
  doc/index.rst
Labels: documentation

#2465 Fix units and `valid_range` of AIRS-2-0
  esmvalcore/cmor/_fixes/obs4mips/airs_2_0.py
  tests/integration/cmor/_fixes/obs4mips/test_airs_2_0.py
Labels: fix for dataset

#2462 Update the version number and release notes for v2.11.0rc2
  CITATION.cff
  doc/changelog.rst
Labels: documentation, release
