Repository ESMValGroup/ESMValCore, pull requests merged in 2024-09, with the labels that each got.

#2515 Optimize functions `mask_landsea()`, `mask_landseaice()` and `calculate_volume()` for lazy input
  esmvalcore/preprocessor/_mask.py
  esmvalcore/preprocessor/_shared.py
  esmvalcore/preprocessor/_volume.py
  tests/integration/preprocessor/_mask/test_mask.py
  tests/unit/preprocessor/_compare_with_refs/test_compare_with_refs.py
  tests/unit/preprocessor/_mask/test_mask.py
  tests/unit/preprocessor/_volume/test_volume.py
Labels: dask

#2519 Fix documentation build and broken link
  doc/quickstart/find_data.rst
Labels: documentation

#2343 cat experiments first, then do the time based cat :black_cat:
  esmvalcore/preprocessor/_io.py
  tests/integration/preprocessor/_io/test_concatenate.py
Labels: bug, preprocessor

#2532 Dark mode compatible logo
  README.md
  doc/conf.py
  doc/figures/ESMValTool-logo-2-dark.png
  doc/figures/ESMValTool-logo-2-glow.png
  doc/figures/ESMValTool-logo-2.png
Labels: documentation

#2529 Fix rounding of Pandas datetimes in ICON CMORizer
  environment.yml
  esmvalcore/cmor/_fixes/icon/icon.py
  setup.py
Labels: bug
