Repository ESMValGroup/ESMValCore, pull requests merged in 2024-04, with the labels that each got.

#2385 Add 10m height coordinate to SfcWind GFDL-CM4 instead of 2m height
  esmvalcore/cmor/_fixes/cmip6/gfdl_cm4.py
Labels: fix for dataset

#2327 change 'mean' to 'percentile' in doc strings of preprocessor statistics
  esmvalcore/preprocessor/_multimodel.py
Labels: documentation, preprocessor

#2387 Fixed typo in doc about weighted statistics
  doc/recipe/preprocessor.rst
Labels: documentation

#2333 cordex wrf381p: fix tas,tasmax,tasmin height
  esmvalcore/cmor/_fixes/cordex/cnrm_cerfacs_cnrm_cm5/wrf381p.py
  esmvalcore/cmor/_fixes/cordex/ichec_ec_earth/wrf381p.py
  esmvalcore/cmor/_fixes/cordex/ipsl_ipsl_cm5a_mr/__init__.py
  esmvalcore/cmor/_fixes/cordex/ipsl_ipsl_cm5a_mr/wrf381p.py
  esmvalcore/cmor/_fixes/cordex/mohc_hadgem2_es/wrf381p.py
  esmvalcore/cmor/_fixes/cordex/ncc_noresm1_m/wrf381p.py
  tests/integration/cmor/_fixes/cordex/test_cnrm_cerfacs_cnrm_cm5.py
  tests/integration/cmor/_fixes/cordex/test_ichec_ec_earth.py
  tests/integration/cmor/_fixes/cordex/test_ipsl_ipsl_cm5a_mr.py
  tests/integration/cmor/_fixes/cordex/test_mohc_hadgem2_es.py
  tests/integration/cmor/_fixes/cordex/test_ncc_noresm1_m.py
Labels: fix for dataset

#2380 Fix `positive` attributes in custom CMOR variables
  esmvalcore/cmor/tables/custom/CMOR_clhmtisccp.dat
  esmvalcore/cmor/tables/custom/CMOR_clhtkisccp.dat
  esmvalcore/cmor/tables/custom/CMOR_cllmtisccp.dat
  esmvalcore/cmor/tables/custom/CMOR_clltkisccp.dat
  esmvalcore/cmor/tables/custom/CMOR_clmmtisccp.dat
  esmvalcore/cmor/tables/custom/CMOR_clmtkisccp.dat
  esmvalcore/cmor/tables/custom/CMOR_lwcre.dat
  esmvalcore/cmor/tables/custom/CMOR_netcre.dat
  esmvalcore/cmor/tables/custom/CMOR_rsnt.dat
  esmvalcore/cmor/tables/custom/CMOR_swcre.dat
  esmvalcore/preprocessor/_derive/lwcre.py
  esmvalcore/preprocessor/_derive/netcre.py
  esmvalcore/preprocessor/_derive/rsnt.py
  esmvalcore/preprocessor/_derive/swcre.py
  tests/unit/preprocessor/_derive/test_lwcre.py
  tests/unit/preprocessor/_derive/test_netcre.py
  tests/unit/preprocessor/_derive/test_rsnt.py
  tests/unit/preprocessor/_derive/test_swcre.py
Labels: cmor

#2348 Broadcast properly `cell_measures` when using `extract_shape` with `decomposed: True`
  esmvalcore/preprocessor/_area.py
  tests/unit/preprocessor/_area/test_area.py
Labels: preprocessor

#2318 Compute volume from cell_area if available
  doc/recipe/preprocessor.rst
  esmvalcore/preprocessor/_volume.py
  tests/unit/preprocessor/_volume/test_volume.py
Labels: preprocessor

#2276 Added note on how to access `index.html` on remote server
  esmvalcore/experimental/recipe_output.py
  tests/sample_data/experimental/test_run_recipe.py
Labels: UX

#2374 Do not expand wildcards for datasets of derived variables where not all input variables are available
  esmvalcore/_recipe/recipe.py
  esmvalcore/_recipe/to_datasets.py
  tests/integration/conftest.py
  tests/integration/recipe/test_recipe.py
  tests/unit/recipe/test_to_datasets.py
Labels: preprocessor

#2388 update codacy reporter orb to latest version
  .circleci/config.yml
Labels: testing

#2391 add calls to `conda list` in Github Action test workflows to inspect environment
  .github/workflows/run-tests-monitor.yml
  .github/workflows/run-tests.yml
Labels: testing

#2392 Remove custom fix for concatenation of aux factories now that bug in iris is solved
  esmvalcore/preprocessor/_io.py
  tests/integration/preprocessor/_io/test_concatenate.py
Labels: iris

#2394 Pin blithering pandas yet again :panda_face: `test_icon` fails again with pandas=2.2.2
  environment.yml
  setup.py
Labels: testing

#2344 Cache regridding weights if possible
  doc/recipe/preprocessor.rst
  esmvalcore/preprocessor/_regrid.py
  esmvalcore/preprocessor/_regrid_esmpy.py
  esmvalcore/preprocessor/regrid_schemes.py
  tests/integration/preprocessor/_regrid/test_regrid.py
  tests/unit/preprocessor/_regrid/test_regrid.py
Labels: enhancement, preprocessor

#2354 Implement lazy area weights
  esmvalcore/preprocessor/_area.py
  tests/unit/preprocessor/_area/test_area.py
Labels: iris, dask

#2361 Log CMOR check and generic fix output to separate file
  esmvalcore/_main.py
  esmvalcore/cmor/_fixes/fix.py
  esmvalcore/config/_config_object.py
  esmvalcore/config/_logging.py
  esmvalcore/config/config-logging.yml
  esmvalcore/experimental/recipe_output.py
  tests/unit/main/test_esmvaltool.py
  tests/unit/test_logging.py
Labels: enhancement, cmor

#2311 Modernize `regrid_time` and allow setting a common calendar for decadal, yearly, and monthly data
  doc/recipe/preprocessor.rst
  esmvalcore/_recipe/recipe.py
  esmvalcore/cmor/_fixes/shared.py
  esmvalcore/preprocessor/_time.py
  tests/integration/cmor/_fixes/test_shared.py
  tests/unit/preprocessor/_time/test_time.py
Labels: enhancement, preprocessor

#2350 Added unstructured linear regridding
  doc/recipe/preprocessor.rst
  esmvalcore/iris_helpers.py
  esmvalcore/preprocessor/_area.py
  esmvalcore/preprocessor/_regrid.py
  esmvalcore/preprocessor/_regrid_unstructured.py
  esmvalcore/preprocessor/regrid_schemes.py
  tests/integration/preprocessor/_regrid/test_regrid.py
  tests/integration/preprocessor/_regrid/test_regrid_unstructured.py
  tests/unit/test_iris_helpers.py
Labels: preprocessor

#2398 Use `iris.FUTURE.save_split_attrs = True` to remove iris warning
  environment.yml
  esmvalcore/_provenance.py
  esmvalcore/preprocessor/_io.py
  setup.py
  tests/integration/conftest.py
  tests/integration/recipe/test_recipe.py
Labels: iris

#2400 Ignored iris warnings about global attributes
  esmvalcore/preprocessor/_io.py
Labels: iris
