Repository ESMValGroup/ESMValCore, pull requests merged in 2025-08, with the labels that each got.

#2794 Pass `chunks={}` to Xarray dataset loader for Zarr stores
  esmvalcore/preprocessor/_io.py
Labels: enhancement

#2792 update mamba and python (remove pins and allow for Python 3.13) conda-lock file creation Github Action - via ESMValTool_sample_data being a conda-forge package
  .github/workflows/create-condalock-file.yml
  conda-linux-64.lock
Labels: testing

#2789 Add preprocessor `align_metadata`
  doc/recipe/preprocessor.rst
  esmvalcore/_recipe/check.py
  esmvalcore/_recipe/recipe.py
  esmvalcore/cmor/table.py
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_other.py
  tests/integration/cmor/test_table.py
  tests/integration/recipe/test_recipe.py
  tests/unit/preprocessor/_other/test_other.py
Labels: preprocessor

#2799 Automatically open pull requests to update GitHub Actions
  .github/dependabot.yml
Labels: testing

#2804 use finer current version for pypa PyPI upload github action
  .github/workflows/build-and-deploy-on-pypi.yml
Labels: release

#2791 Align custom `lwp` table with CMIP6 version
  esmvalcore/cmor/tables/custom/CMOR_lwp.dat
Labels: cmor, backwards incompatible change

#2809 Enable ruff rule that checks unused arguments
  esmvalcore/cmor/_fixes/fix.py
  esmvalcore/cmor/table.py
  esmvalcore/experimental/_warnings.py
  esmvalcore/preprocessor/_dask_progress.py
  esmvalcore/preprocessor/_derive/alb.py
  esmvalcore/preprocessor/_derive/asr.py
  esmvalcore/preprocessor/_derive/chlora.py
  esmvalcore/preprocessor/_derive/clhmtisccp.py
  esmvalcore/preprocessor/_derive/clhtkisccp.py
  esmvalcore/preprocessor/_derive/cllmtisccp.py
  esmvalcore/preprocessor/_derive/clltkisccp.py
  esmvalcore/preprocessor/_derive/clmmtisccp.py
  esmvalcore/preprocessor/_derive/clmtkisccp.py
  esmvalcore/preprocessor/_derive/co2s.py
  esmvalcore/preprocessor/_derive/et.py
  esmvalcore/preprocessor/_derive/hfns.py
  esmvalcore/preprocessor/_derive/hurs.py
  esmvalcore/preprocessor/_derive/lvp.py
  esmvalcore/preprocessor/_derive/lwcre.py
  esmvalcore/preprocessor/_derive/lwp.py
  esmvalcore/preprocessor/_derive/netcre.py
  esmvalcore/preprocessor/_derive/qep.py
  esmvalcore/preprocessor/_derive/rlns.py
  esmvalcore/preprocessor/_derive/rlnst.py
  esmvalcore/preprocessor/_derive/rlnstcs.py
  esmvalcore/preprocessor/_derive/rlntcs.py
  esmvalcore/preprocessor/_derive/rlus.py
  esmvalcore/preprocessor/_derive/rsns.py
  esmvalcore/preprocessor/_derive/rsnst.py
  esmvalcore/preprocessor/_derive/rsnstcs.py
  esmvalcore/preprocessor/_derive/rsnstcsnorm.py
  esmvalcore/preprocessor/_derive/rsnt.py
  esmvalcore/preprocessor/_derive/rsntcs.py
  esmvalcore/preprocessor/_derive/rsus.py
  esmvalcore/preprocessor/_derive/rtnt.py
  esmvalcore/preprocessor/_derive/sfcwind.py
  esmvalcore/preprocessor/_derive/siextent.py
  esmvalcore/preprocessor/_derive/sithick.py
  esmvalcore/preprocessor/_derive/sm.py
  esmvalcore/preprocessor/_derive/swcre.py
  esmvalcore/preprocessor/_derive/toz.py
  esmvalcore/preprocessor/_derive/uajet.py
  esmvalcore/preprocessor/_derive/xch4.py
  esmvalcore/preprocessor/_derive/xco2.py
  esmvalcore/preprocessor/_io.py
  esmvalcore/preprocessor/_mask.py
  pyproject.toml
Labels: enhancement

#2810 Enable ruff rule to prevent print statements
  esmvalcore/_main.py
  esmvalcore/cmor/table.py
  esmvalcore/esgf/facets.py
  esmvalcore/exceptions.py
  pyproject.toml
Labels: enhancement

#2811 Enable ruff rule that enforces using items() to iterate over dict key/value pairs
  esmvalcore/_recipe/check.py
  esmvalcore/_task.py
  esmvalcore/config/_diagnostics.py
  esmvalcore/dataset.py
  esmvalcore/preprocessor/__init__.py
  pyproject.toml
  tests/unit/config/test_config.py
  tests/unit/recipe/test_recipe.py
Labels: enhancement

#2819 Remove mention of Julia in documentation ahead of discontinued support in v2.13
  doc/contributing.rst
  doc/recipe/overview.rst
Labels: documentation

#2808 Enable ruff rule that checks for commented out code
  esmvalcore/cmor/_fixes/cmip5/bnu_esm.py
  esmvalcore/cmor/_fixes/cmip5/miroc5.py
  esmvalcore/cmor/_fixes/cmip5/miroc_esm_chem.py
  esmvalcore/cmor/_fixes/cmip6/cesm2.py
  esmvalcore/cmor/_fixes/common.py
  esmvalcore/config/_config_object.py
  esmvalcore/config/_esgf_pyclient.py
  esmvalcore/preprocessor/_area.py
  esmvalcore/preprocessor/_compare_with_refs.py
  esmvalcore/preprocessor/_io.py
  esmvalcore/preprocessor/_mask.py
  esmvalcore/preprocessor/_other.py
  esmvalcore/preprocessor/_regrid_esmpy.py
  esmvalcore/preprocessor/_volume.py
  pyproject.toml
  tests/integration/cmor/_fixes/cesm/test_cesm2.py
  tests/integration/cmor/_fixes/emac/test_emac.py
  tests/integration/cmor/_fixes/icon/test_icon.py
  tests/integration/cmor/_fixes/icon/test_icon_xpp.py
  tests/integration/cmor/_fixes/native6/test_mswep.py
  tests/integration/conftest.py
  tests/integration/test_diagnostic_run.py
  tests/unit/config/test_esgf_pyclient.py
  tests/unit/preprocessor/_mask/test_mask.py
  tests/unit/preprocessor/_multimodel/test_multimodel.py
  tests/unit/preprocessor/_regrid/test_extract_regional_grid.py
Labels: enhancement

#2818 Remove use of prospector and related tools and Codacy
  .circleci/config.yml
  .codacy.yml
  .prospector.yml
  doc/contributing.rst
  environment.yml
  pyproject.toml
  setup.cfg
Labels: documentation, testing

#2822 Remove codacy badge
  README.md
  doc/contributing.rst
Labels: documentation

#2823 Change zarr exception test to GroupNotFoundError
  tests/integration/preprocessor/_io/test_zarr.py
Labels: testing
