Repository ESMValGroup/ESMValCore, pull requests merged in 2025-05, with the labels that each got.

#2722 Fix for obs4MIPs dataset C3S-GTO-ECV-9-0 (toz)
  esmvalcore/cmor/_fixes/obs4mips/c3s_gto_ecv_9_0.py
  tests/integration/cmor/_fixes/obs4mips/test_c3s_gto_ecv_9_0.py
Labels: fix for dataset, data issue

#2728 Use `netCDF4.Dataset` to read start and end date from files
  esmvalcore/local.py
  tests/unit/local/test_time.py
Labels: enhancement

#2659 Add on-the-fly CMORizer for ICON-XPP
  doc/develop/fixing_data.rst
  doc/quickstart/configure.rst
  doc/quickstart/find_data.rst
  esmvalcore/cmor/_fixes/emac/emac.py
  esmvalcore/cmor/_fixes/icon/_base_fixes.py
  esmvalcore/cmor/_fixes/icon/icon.py
  esmvalcore/cmor/_fixes/icon/icon_xpp.py
  esmvalcore/cmor/_fixes/native_datasets.py
  esmvalcore/cmor/check.py
  esmvalcore/config-developer.yml
  esmvalcore/config/extra_facets/icon-mappings.yml
  esmvalcore/iris_helpers.py
  esmvalcore/local.py
  pyproject.toml
  tests/integration/cmor/_fixes/icon/test_icon.py
  tests/integration/cmor/_fixes/icon/test_icon_xpp.py
  tests/integration/cmor/_fixes/test_data/icon_atm_2d.nc
  tests/integration/cmor/_fixes/test_data/icon_atm_3d.nc
  tests/integration/cmor/_fixes/test_data/icon_xpp_atm_2d.nc
  tests/integration/cmor/_fixes/test_data/icon_xpp_atm_3d.nc
  tests/integration/cmor/_fixes/test_data/icon_xpp_ocean_3d.nc
  tests/integration/cmor/_fixes/test_native_datasets.py
  tests/integration/data_finder.yml
  tests/unit/cmor/test_cmor_check.py
  tests/unit/test_dataset.py
Labels: fix for dataset

#2730 Remove support for python 3.10
  .github/workflows/install-from-conda.yml
  .github/workflows/install-from-condalock-file.yml
  .github/workflows/install-from-pypi.yml
  .github/workflows/install-from-source.yml
  .github/workflows/run-tests-monitor.yml
  .github/workflows/run-tests.yml
  environment.yml
  pyproject.toml
Labels: installation

#2708 explicitly export LC_ALL for sphinx builds
  doc/conf.py
Labels: documentation, testing

#2726 unpin dask, pin iris, in light of solved #2716 (iris saver not working well with latest Dask API)
  environment.yml
  pyproject.toml
Labels: installation

#2725 Allow reading facets from filenames
  esmvalcore/local.py
  tests/unit/local/test_facets.py
Labels: enhancement

#2733 Show external warnings only in debug log
  esmvalcore/config/_logging.py
  esmvalcore/config/config-logging.yml
  esmvalcore/exceptions.py
  tests/unit/test_logging.py
Labels: enhancement
