Repository ESMValGroup/ESMValCore, pull requests merged in 2025-02, with the labels that each got.

#2649 restrict runs of cron Github Actions on forks
  .github/workflows/citation_file_validator.yml
  .github/workflows/create-condalock-file.yml
  .github/workflows/install-from-conda.yml
  .github/workflows/install-from-condalock-file.yml
  .github/workflows/install-from-pypi.yml
  .github/workflows/install-from-source.yml
  .github/workflows/run-tests-monitor.yml
  .github/workflows/run-tests.yml
Labels: testing

#2442 Adding custom tables for ETCCDI indices
  esmvalcore/cmor/tables/custom/CMOR_rx1day.dat
  esmvalcore/cmor/tables/custom/CMOR_rx5day.dat
  esmvalcore/cmor/tables/custom/CMOR_tnn.dat
  esmvalcore/cmor/tables/custom/CMOR_txx.dat
Labels: cmor, AR6, observations

#2654 Pin dask
  environment.yml
  pyproject.toml
Labels: installation

#2658 Revise the `user-config.yml` to support updated MO user config requirements
  esmvalcore/config/configurations/defaults/config-user.yml
Labels: config

#2662 Add release notes for v2.12.0rc1
  doc/changelog.rst
Labels: release

#2665 Fix test that loads realistic GRIB file
  doc/develop/preprocessor_function.rst
  tests/integration/preprocessor/_io/test_load.py
Labels: testing

#2663 Fix failing test with Dask 2025.2: ours issue not theirs
  tests/unit/preprocessor/test_shared.py
Labels: testing

#2667 Add a fix for differing index coord long names in NorESM2-MM and EC-Earth3-Veg-LR
  esmvalcore/cmor/_fixes/cmip6/ec_earth3_veg_lr.py
  esmvalcore/cmor/_fixes/cmip6/noresm2_mm.py
  tests/integration/cmor/_fixes/cmip6/test_ec_earth3_veg_lr.py
  tests/integration/cmor/_fixes/cmip6/test_noresm2_mm.py
Labels: fix for dataset

#2672 Add option to ignore horizontal coordinates if there are multiple when regridding
  doc/recipe/preprocessor.rst
  esmvalcore/preprocessor/_regrid.py
  tests/integration/preprocessor/_regrid/test_regrid.py
  tests/unit/preprocessor/_regrid/__init__.py
  tests/unit/preprocessor/_regrid/test_regrid.py
Labels: preprocessor

#2673 Always write target coordinates to source cube after regridding
  esmvalcore/preprocessor/_regrid.py
  tests/unit/preprocessor/_regrid/test_regrid.py
Labels: bug

#2675 Increase version for v2.12.0rc2 and update changelog
  CITATION.cff
  doc/changelog.rst
Labels: release

#2668 Ignore overflow errors when converting branch times
  esmvalcore/cmor/_fixes/fix.py
  tests/integration/cmor/test_fix.py
Labels: cmor
