Repository ESMValGroup/ESMValCore, pull requests merged in 2025-01, with the labels that each got.

#2621 Correct incorrect time bounds in EMAC data
  doc/quickstart/find_data.rst
  esmvalcore/cmor/_fixes/emac/emac.py
  tests/integration/cmor/_fixes/emac/test_emac.py
Labels: fix for dataset, EMAC

#2625 Silence Iris warnings in ``area_statistics`` preprocessor function
  esmvalcore/preprocessor/_area.py
Labels: iris

#2633 Do not copy ICON horizontal grid every time it is used
  esmvalcore/cmor/_fixes/icon/_base_fixes.py
  esmvalcore/cmor/_fixes/icon/icon.py
  tests/integration/cmor/_fixes/icon/test_icon.py
Labels: fix for dataset

#2634 Fix `oh` for model: EC-Earth3-AerChem mip: AERMonZ
  esmvalcore/cmor/_fixes/cmip6/ec_earth3_aerchem.py
  tests/integration/cmor/_fixes/cmip6/test_ec_earth3_aerchem.py
Labels: fix for dataset

#2635 Update the `esmvaltool` command welcome message
  esmvalcore/_main.py
Labels: documentation

#2610 Only save data from one preprocessing task at a time with the Distributed scheduler
  esmvalcore/_task.py
  esmvalcore/preprocessor/__init__.py
  tests/integration/preprocessor/test_preprocessing_task.py
  tests/integration/test_task.py
Labels: dask

#2626 Use better defaults when using ``max_parallel_tasks`` with an unconfigured threaded scheduler
  doc/quickstart/configure.rst
  esmvalcore/_task.py
  tests/unit/task/test_taskset.py
Labels: dask

#2472 More reliable datasets to recipe conversion
  esmvalcore/_recipe/from_datasets.py
  tests/unit/recipe/test_from_datasets.py
Labels: bug

#2564 Avoid mutating the input cubes when building the combined cube in preprocessor function ``multi_model_statistics``
  esmvalcore/preprocessor/_multimodel.py
Labels: bug

#2637 Make sure that supplementary variables and weights have same chunks as parent cube
  esmvalcore/iris_helpers.py
  esmvalcore/preprocessor/_supplementary_vars.py
  esmvalcore/preprocessor/_volume.py
  tests/integration/preprocessor/_supplementary_vars/test_add_supplementary_variables.py
  tests/unit/preprocessor/_volume/test_volume.py
Labels: dask

#2397 Adding hurs (realtive humidity) derivation script
  esmvalcore/preprocessor/_derive/hurs.py
  tests/unit/preprocessor/_derive/test_hurs.py
Labels: enhancement, preprocessor, variable derivation, observations

#2642 Added cumulative sum preprocessor
  doc/recipe/preprocessor.rst
  esmvalcore/iris_helpers.py
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_other.py
  esmvalcore/preprocessor/_shared.py
  esmvalcore/preprocessor/_time.py
  esmvalcore/preprocessor/_volume.py
  tests/unit/preprocessor/_compare_with_refs/test_compare_with_refs.py
  tests/unit/preprocessor/_other/test_other.py
  tests/unit/preprocessor/_time/test_time.py
  tests/unit/preprocessor/_volume/test_volume.py
  tests/unit/preprocessor/test_shared.py
Labels: preprocessor

#2646 Unified ignoring of `iris.warnings.IrisVagueMetadataWarning` in preprocessors
  esmvalcore/cmor/_fixes/emac/emac.py
  esmvalcore/iris_helpers.py
  esmvalcore/preprocessor/_area.py
  esmvalcore/preprocessor/_compare_with_refs.py
  esmvalcore/preprocessor/_cycles.py
  esmvalcore/preprocessor/_derive/_shared.py
  esmvalcore/preprocessor/_derive/amoc.py
  esmvalcore/preprocessor/_derive/toz.py
  esmvalcore/preprocessor/_derive/troz.py
  esmvalcore/preprocessor/_derive/uajet.py
  esmvalcore/preprocessor/_mask.py
  esmvalcore/preprocessor/_multimodel.py
  esmvalcore/preprocessor/_other.py
  esmvalcore/preprocessor/_rolling_window.py
  esmvalcore/preprocessor/_shared.py
  esmvalcore/preprocessor/_time.py
  esmvalcore/preprocessor/_trend.py
  esmvalcore/preprocessor/_volume.py
  tests/unit/preprocessor/_derive/test_shared.py
  tests/unit/test_iris_helpers.py
Labels: preprocessor
