Repository ESMValGroup/ESMValCore, pull requests merged in 2025-04, with the labels that each got.

#2697 Add derivation of moisture flux into atmosphere
  esmvalcore/cmor/tables/custom/CMOR_qep.dat
  esmvalcore/preprocessor/_derive/qep.py
  tests/unit/preprocessor/_derive/test_qep.py
Labels: variable derivation

#2691 add evaporation flux to special unit conversion
  esmvalcore/iris_helpers.py
  esmvalcore/preprocessor/_units.py
  tests/unit/preprocessor/_units/test_convert_units.py
Labels: preprocessor

#2701 Remove accidentally added file
  yz9299_ESMValTool.yml
Labels: bear at a dinner party

#2700 [NOT FOR CHANGELOG; PR NOT IN MAIN] adding lai and gpp to icon xpp
  esmvalcore/cmor/_fixes/icon/icon_xpp.py
  esmvalcore/config/extra_facets/icon-mappings.yml
  tests/integration/cmor/_fixes/icon/test_icon_xpp.py
Labels: fix for dataset

#2702 [NOT FOR CHANGELOG; PR NOT IN MAIN] Add mappings for ocean variables
  esmvalcore/config/extra_facets/icon-mappings.yml
Labels: fix for dataset

#2710 Use --no-deps in upstream tests to avoid installation problems caused by upper pins
  .circleci/config.yml
Labels: testing

#2717 Temporary pin dask `!=2025.4.0`
  environment.yml
  pyproject.toml
Labels: testing
